// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debt.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (
    store_id,
    customer_id,
    sale_id,
    amount_owed,
    amount_remaining,
    due_date,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, store_id, customer_id, sale_id, amount_owed, amount_paid, amount_remaining, due_date, status, created_at, updated_at
`

type CreateDebtParams struct {
	StoreID         pgtype.UUID    `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID    `db:"customer_id" json:"customer_id"`
	SaleID          pgtype.UUID    `db:"sale_id" json:"sale_id"`
	AmountOwed      pgtype.Numeric `db:"amount_owed" json:"amount_owed"`
	AmountRemaining pgtype.Numeric `db:"amount_remaining" json:"amount_remaining"`
	DueDate         pgtype.Date    `db:"due_date" json:"due_date"`
	Status          pgtype.Text    `db:"status" json:"status"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.StoreID,
		arg.CustomerID,
		arg.SaleID,
		arg.AmountOwed,
		arg.AmountRemaining,
		arg.DueDate,
		arg.Status,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CustomerID,
		&i.SaleID,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.AmountRemaining,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createDebtPayment = `-- name: CreateDebtPayment :one

INSERT INTO debt_payments (
    debt_id,
    amount_paid,
    payment_method,
    received_by,
    notes
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, debt_id, amount_paid, payment_method, payment_date, received_by, notes
`

type CreateDebtPaymentParams struct {
	DebtID        pgtype.UUID    `db:"debt_id" json:"debt_id"`
	AmountPaid    pgtype.Numeric `db:"amount_paid" json:"amount_paid"`
	PaymentMethod pgtype.Text    `db:"payment_method" json:"payment_method"`
	ReceivedBy    pgtype.UUID    `db:"received_by" json:"received_by"`
	Notes         pgtype.Text    `db:"notes" json:"notes"`
}

// Debt Payments queries
func (q *Queries) CreateDebtPayment(ctx context.Context, arg CreateDebtPaymentParams) (DebtPayment, error) {
	row := q.db.QueryRow(ctx, createDebtPayment,
		arg.DebtID,
		arg.AmountPaid,
		arg.PaymentMethod,
		arg.ReceivedBy,
		arg.Notes,
	)
	var i DebtPayment
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.AmountPaid,
		&i.PaymentMethod,
		&i.PaymentDate,
		&i.ReceivedBy,
		&i.Notes,
	)
	return i, err
}

const deleteDebt = `-- name: DeleteDebt :exec
DELETE FROM debts WHERE id = $1 AND store_id = $2
`

type DeleteDebtParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeleteDebt(ctx context.Context, arg DeleteDebtParams) error {
	_, err := q.db.Exec(ctx, deleteDebt, arg.ID, arg.StoreID)
	return err
}

const deleteDebtPayment = `-- name: DeleteDebtPayment :exec
DELETE FROM debt_payments WHERE id = $1
`

func (q *Queries) DeleteDebtPayment(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteDebtPayment, id)
	return err
}

const getDebtById = `-- name: GetDebtById :one
SELECT d.id, d.store_id, d.customer_id, d.sale_id, d.amount_owed, d.amount_paid, d.amount_remaining, d.due_date, d.status, d.created_at, d.updated_at,
       c.name as customer_name,
       c.phone as customer_phone
FROM debts d
JOIN customers c ON d.customer_id = c.id
WHERE d.id = $1 AND d.store_id = $2
`

type GetDebtByIdParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

type GetDebtByIdRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleID          pgtype.UUID        `db:"sale_id" json:"sale_id"`
	AmountOwed      pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid      pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	AmountRemaining pgtype.Numeric     `db:"amount_remaining" json:"amount_remaining"`
	DueDate         pgtype.Date        `db:"due_date" json:"due_date"`
	Status          pgtype.Text        `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName    string             `db:"customer_name" json:"customer_name"`
	CustomerPhone   pgtype.Text        `db:"customer_phone" json:"customer_phone"`
}

func (q *Queries) GetDebtById(ctx context.Context, arg GetDebtByIdParams) (GetDebtByIdRow, error) {
	row := q.db.QueryRow(ctx, getDebtById, arg.ID, arg.StoreID)
	var i GetDebtByIdRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CustomerID,
		&i.SaleID,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.AmountRemaining,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CustomerName,
		&i.CustomerPhone,
	)
	return i, err
}

const getDebtPaymentById = `-- name: GetDebtPaymentById :one
SELECT dp.id, dp.debt_id, dp.amount_paid, dp.payment_method, dp.payment_date, dp.received_by, dp.notes,
       u.name as received_by_name
FROM debt_payments dp
LEFT JOIN users u ON dp.received_by = u.id
WHERE dp.id = $1
`

type GetDebtPaymentByIdRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	DebtID         pgtype.UUID        `db:"debt_id" json:"debt_id"`
	AmountPaid     pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	PaymentMethod  pgtype.Text        `db:"payment_method" json:"payment_method"`
	PaymentDate    pgtype.Timestamptz `db:"payment_date" json:"payment_date"`
	ReceivedBy     pgtype.UUID        `db:"received_by" json:"received_by"`
	Notes          pgtype.Text        `db:"notes" json:"notes"`
	ReceivedByName pgtype.Text        `db:"received_by_name" json:"received_by_name"`
}

func (q *Queries) GetDebtPaymentById(ctx context.Context, id pgtype.UUID) (GetDebtPaymentByIdRow, error) {
	row := q.db.QueryRow(ctx, getDebtPaymentById, id)
	var i GetDebtPaymentByIdRow
	err := row.Scan(
		&i.ID,
		&i.DebtID,
		&i.AmountPaid,
		&i.PaymentMethod,
		&i.PaymentDate,
		&i.ReceivedBy,
		&i.Notes,
		&i.ReceivedByName,
	)
	return i, err
}

const getDebtPayments = `-- name: GetDebtPayments :many
SELECT dp.id, dp.debt_id, dp.amount_paid, dp.payment_method, dp.payment_date, dp.received_by, dp.notes,
       u.name as received_by_name
FROM debt_payments dp
LEFT JOIN users u ON dp.received_by = u.id
WHERE dp.debt_id = $1
ORDER BY dp.payment_date DESC
`

type GetDebtPaymentsRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	DebtID         pgtype.UUID        `db:"debt_id" json:"debt_id"`
	AmountPaid     pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	PaymentMethod  pgtype.Text        `db:"payment_method" json:"payment_method"`
	PaymentDate    pgtype.Timestamptz `db:"payment_date" json:"payment_date"`
	ReceivedBy     pgtype.UUID        `db:"received_by" json:"received_by"`
	Notes          pgtype.Text        `db:"notes" json:"notes"`
	ReceivedByName pgtype.Text        `db:"received_by_name" json:"received_by_name"`
}

func (q *Queries) GetDebtPayments(ctx context.Context, debtID pgtype.UUID) ([]GetDebtPaymentsRow, error) {
	rows, err := q.db.Query(ctx, getDebtPayments, debtID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDebtPaymentsRow
	for rows.Next() {
		var i GetDebtPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.DebtID,
			&i.AmountPaid,
			&i.PaymentMethod,
			&i.PaymentDate,
			&i.ReceivedBy,
			&i.Notes,
			&i.ReceivedByName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebtSummary = `-- name: GetDebtSummary :one
SELECT 
    COUNT(*) as total_debts,
    COALESCE(SUM(amount_remaining), 0) as total_amount_remaining,
    COALESCE(SUM(CASE WHEN status = 'overdue' THEN amount_remaining ELSE 0 END), 0) as overdue_amount
FROM debts
WHERE store_id = $1 AND status IN ('pending', 'partial', 'overdue')
`

type GetDebtSummaryRow struct {
	TotalDebts           int64       `db:"total_debts" json:"total_debts"`
	TotalAmountRemaining interface{} `db:"total_amount_remaining" json:"total_amount_remaining"`
	OverdueAmount        interface{} `db:"overdue_amount" json:"overdue_amount"`
}

func (q *Queries) GetDebtSummary(ctx context.Context, storeID pgtype.UUID) (GetDebtSummaryRow, error) {
	row := q.db.QueryRow(ctx, getDebtSummary, storeID)
	var i GetDebtSummaryRow
	err := row.Scan(&i.TotalDebts, &i.TotalAmountRemaining, &i.OverdueAmount)
	return i, err
}

const listDebts = `-- name: ListDebts :many
SELECT d.id, d.store_id, d.customer_id, d.sale_id, d.amount_owed, d.amount_paid, d.amount_remaining, d.due_date, d.status, d.created_at, d.updated_at,
       c.name as customer_name,
       c.phone as customer_phone
FROM debts d
JOIN customers c ON d.customer_id = c.id
WHERE d.store_id = $1
ORDER BY d.due_date ASC
LIMIT $2 OFFSET $3
`

type ListDebtsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListDebtsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleID          pgtype.UUID        `db:"sale_id" json:"sale_id"`
	AmountOwed      pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid      pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	AmountRemaining pgtype.Numeric     `db:"amount_remaining" json:"amount_remaining"`
	DueDate         pgtype.Date        `db:"due_date" json:"due_date"`
	Status          pgtype.Text        `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName    string             `db:"customer_name" json:"customer_name"`
	CustomerPhone   pgtype.Text        `db:"customer_phone" json:"customer_phone"`
}

func (q *Queries) ListDebts(ctx context.Context, arg ListDebtsParams) ([]ListDebtsRow, error) {
	rows, err := q.db.Query(ctx, listDebts, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebtsRow
	for rows.Next() {
		var i ListDebtsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CustomerID,
			&i.SaleID,
			&i.AmountOwed,
			&i.AmountPaid,
			&i.AmountRemaining,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtsByCustomer = `-- name: ListDebtsByCustomer :many
SELECT d.id, d.store_id, d.customer_id, d.sale_id, d.amount_owed, d.amount_paid, d.amount_remaining, d.due_date, d.status, d.created_at, d.updated_at
FROM debts d
WHERE d.customer_id = $1 AND d.store_id = $2
ORDER BY d.due_date ASC
`

type ListDebtsByCustomerParams struct {
	CustomerID pgtype.UUID `db:"customer_id" json:"customer_id"`
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) ListDebtsByCustomer(ctx context.Context, arg ListDebtsByCustomerParams) ([]Debt, error) {
	rows, err := q.db.Query(ctx, listDebtsByCustomer, arg.CustomerID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Debt
	for rows.Next() {
		var i Debt
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CustomerID,
			&i.SaleID,
			&i.AmountOwed,
			&i.AmountPaid,
			&i.AmountRemaining,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDebtsByStatus = `-- name: ListDebtsByStatus :many
SELECT d.id, d.store_id, d.customer_id, d.sale_id, d.amount_owed, d.amount_paid, d.amount_remaining, d.due_date, d.status, d.created_at, d.updated_at,
       c.name as customer_name,
       c.phone as customer_phone
FROM debts d
JOIN customers c ON d.customer_id = c.id
WHERE d.store_id = $1 AND d.status = $2
ORDER BY d.due_date ASC
`

type ListDebtsByStatusParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Status  pgtype.Text `db:"status" json:"status"`
}

type ListDebtsByStatusRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleID          pgtype.UUID        `db:"sale_id" json:"sale_id"`
	AmountOwed      pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid      pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	AmountRemaining pgtype.Numeric     `db:"amount_remaining" json:"amount_remaining"`
	DueDate         pgtype.Date        `db:"due_date" json:"due_date"`
	Status          pgtype.Text        `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName    string             `db:"customer_name" json:"customer_name"`
	CustomerPhone   pgtype.Text        `db:"customer_phone" json:"customer_phone"`
}

func (q *Queries) ListDebtsByStatus(ctx context.Context, arg ListDebtsByStatusParams) ([]ListDebtsByStatusRow, error) {
	rows, err := q.db.Query(ctx, listDebtsByStatus, arg.StoreID, arg.Status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDebtsByStatusRow
	for rows.Next() {
		var i ListDebtsByStatusRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CustomerID,
			&i.SaleID,
			&i.AmountOwed,
			&i.AmountPaid,
			&i.AmountRemaining,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueDebts = `-- name: ListOverdueDebts :many
SELECT d.id, d.store_id, d.customer_id, d.sale_id, d.amount_owed, d.amount_paid, d.amount_remaining, d.due_date, d.status, d.created_at, d.updated_at,
       c.name as customer_name,
       c.phone as customer_phone
FROM debts d
JOIN customers c ON d.customer_id = c.id
WHERE d.store_id = $1 
  AND d.due_date < CURRENT_DATE
  AND d.status IN ('pending', 'partial')
ORDER BY d.due_date ASC
`

type ListOverdueDebtsRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleID          pgtype.UUID        `db:"sale_id" json:"sale_id"`
	AmountOwed      pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid      pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	AmountRemaining pgtype.Numeric     `db:"amount_remaining" json:"amount_remaining"`
	DueDate         pgtype.Date        `db:"due_date" json:"due_date"`
	Status          pgtype.Text        `db:"status" json:"status"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	CustomerName    string             `db:"customer_name" json:"customer_name"`
	CustomerPhone   pgtype.Text        `db:"customer_phone" json:"customer_phone"`
}

func (q *Queries) ListOverdueDebts(ctx context.Context, storeID pgtype.UUID) ([]ListOverdueDebtsRow, error) {
	rows, err := q.db.Query(ctx, listOverdueDebts, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListOverdueDebtsRow
	for rows.Next() {
		var i ListOverdueDebtsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.CustomerID,
			&i.SaleID,
			&i.AmountOwed,
			&i.AmountPaid,
			&i.AmountRemaining,
			&i.DueDate,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateDebt = `-- name: UpdateDebt :one
UPDATE debts SET
    amount_paid = $2,
    amount_remaining = $3,
    status = $4,
    updated_at = NOW()
WHERE id = $1
RETURNING id, store_id, customer_id, sale_id, amount_owed, amount_paid, amount_remaining, due_date, status, created_at, updated_at
`

type UpdateDebtParams struct {
	ID              pgtype.UUID    `db:"id" json:"id"`
	AmountPaid      pgtype.Numeric `db:"amount_paid" json:"amount_paid"`
	AmountRemaining pgtype.Numeric `db:"amount_remaining" json:"amount_remaining"`
	Status          pgtype.Text    `db:"status" json:"status"`
}

func (q *Queries) UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, updateDebt,
		arg.ID,
		arg.AmountPaid,
		arg.AmountRemaining,
		arg.Status,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CustomerID,
		&i.SaleID,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.AmountRemaining,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateDebtStatus = `-- name: UpdateDebtStatus :one
UPDATE debts SET
    status = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, store_id, customer_id, sale_id, amount_owed, amount_paid, amount_remaining, due_date, status, created_at, updated_at
`

type UpdateDebtStatusParams struct {
	ID     pgtype.UUID `db:"id" json:"id"`
	Status pgtype.Text `db:"status" json:"status"`
}

func (q *Queries) UpdateDebtStatus(ctx context.Context, arg UpdateDebtStatusParams) (Debt, error) {
	row := q.db.QueryRow(ctx, updateDebtStatus, arg.ID, arg.Status)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CustomerID,
		&i.SaleID,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.AmountRemaining,
		&i.DueDate,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
