// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type User struct {
	ID                  pgtype.UUID        `db:"id" json:"id"`
	Name                string             `db:"name" json:"name"`
	Email               string             `db:"email" json:"email"`
	Password            string             `db:"password" json:"password"`
	Phone               pgtype.Text        `db:"phone" json:"phone"`
	Status              string             `db:"status" json:"status"`
	EmailVerified       bool               `db:"email_verified" json:"email_verified"`
	LastLogin           pgtype.Timestamptz `db:"last_login" json:"last_login"`
	FailedLoginAttempts int32              `db:"failed_login_attempts" json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	CreatedAt           pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
