// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product_expiration.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductExpiration = `-- name: CreateProductExpiration :one
INSERT INTO product_expirations (
    product_id,
    batch_number,
    expiration_date,
    quantity
) VALUES (
    $1, $2, $3, $4
) RETURNING id, product_id, batch_number, expiration_date, quantity, created_at
`

type CreateProductExpirationParams struct {
	ProductID      pgtype.UUID `db:"product_id" json:"product_id"`
	BatchNumber    pgtype.Text `db:"batch_number" json:"batch_number"`
	ExpirationDate pgtype.Date `db:"expiration_date" json:"expiration_date"`
	Quantity       int32       `db:"quantity" json:"quantity"`
}

func (q *Queries) CreateProductExpiration(ctx context.Context, arg CreateProductExpirationParams) (ProductExpiration, error) {
	row := q.db.QueryRow(ctx, createProductExpiration,
		arg.ProductID,
		arg.BatchNumber,
		arg.ExpirationDate,
		arg.Quantity,
	)
	var i ProductExpiration
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ExpirationDate,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProductExpiration = `-- name: DeleteProductExpiration :exec
DELETE FROM product_expirations WHERE id = $1
`

func (q *Queries) DeleteProductExpiration(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductExpiration, id)
	return err
}

const getProductExpirationById = `-- name: GetProductExpirationById :one
SELECT pe.id, pe.product_id, pe.batch_number, pe.expiration_date, pe.quantity, pe.created_at,
       p.name as product_name,
       p.code as product_code
FROM product_expirations pe
JOIN products p ON pe.product_id = p.id
WHERE pe.id = $1
`

type GetProductExpirationByIdRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ProductID      pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber    pgtype.Text        `db:"batch_number" json:"batch_number"`
	ExpirationDate pgtype.Date        `db:"expiration_date" json:"expiration_date"`
	Quantity       int32              `db:"quantity" json:"quantity"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProductName    string             `db:"product_name" json:"product_name"`
	ProductCode    string             `db:"product_code" json:"product_code"`
}

func (q *Queries) GetProductExpirationById(ctx context.Context, id pgtype.UUID) (GetProductExpirationByIdRow, error) {
	row := q.db.QueryRow(ctx, getProductExpirationById, id)
	var i GetProductExpirationByIdRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ExpirationDate,
		&i.Quantity,
		&i.CreatedAt,
		&i.ProductName,
		&i.ProductCode,
	)
	return i, err
}

const listExpirationsByProduct = `-- name: ListExpirationsByProduct :many
SELECT id, product_id, batch_number, expiration_date, quantity, created_at FROM product_expirations
WHERE product_id = $1
ORDER BY expiration_date ASC
`

func (q *Queries) ListExpirationsByProduct(ctx context.Context, productID pgtype.UUID) ([]ProductExpiration, error) {
	rows, err := q.db.Query(ctx, listExpirationsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductExpiration
	for rows.Next() {
		var i ProductExpiration
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ExpirationDate,
			&i.Quantity,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiredProducts = `-- name: ListExpiredProducts :many
SELECT pe.id, pe.product_id, pe.batch_number, pe.expiration_date, pe.quantity, pe.created_at,
       p.name as product_name,
       p.code as product_code
FROM product_expirations pe
JOIN products p ON pe.product_id = p.id
WHERE p.store_id = $1 
  AND pe.expiration_date < CURRENT_DATE
  AND pe.quantity > 0
ORDER BY pe.expiration_date ASC
`

type ListExpiredProductsRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ProductID      pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber    pgtype.Text        `db:"batch_number" json:"batch_number"`
	ExpirationDate pgtype.Date        `db:"expiration_date" json:"expiration_date"`
	Quantity       int32              `db:"quantity" json:"quantity"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProductName    string             `db:"product_name" json:"product_name"`
	ProductCode    string             `db:"product_code" json:"product_code"`
}

func (q *Queries) ListExpiredProducts(ctx context.Context, storeID pgtype.UUID) ([]ListExpiredProductsRow, error) {
	rows, err := q.db.Query(ctx, listExpiredProducts, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiredProductsRow
	for rows.Next() {
		var i ListExpiredProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ExpirationDate,
			&i.Quantity,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpiringSoon = `-- name: ListExpiringSoon :many
SELECT pe.id, pe.product_id, pe.batch_number, pe.expiration_date, pe.quantity, pe.created_at,
       p.name as product_name,
       p.code as product_code,
       p.store_id
FROM product_expirations pe
JOIN products p ON pe.product_id = p.id
WHERE p.store_id = $1 
  AND pe.expiration_date <= $2
  AND pe.quantity > 0
ORDER BY pe.expiration_date ASC
`

type ListExpiringSoonParams struct {
	StoreID        pgtype.UUID `db:"store_id" json:"store_id"`
	ExpirationDate pgtype.Date `db:"expiration_date" json:"expiration_date"`
}

type ListExpiringSoonRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ProductID      pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber    pgtype.Text        `db:"batch_number" json:"batch_number"`
	ExpirationDate pgtype.Date        `db:"expiration_date" json:"expiration_date"`
	Quantity       int32              `db:"quantity" json:"quantity"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProductName    string             `db:"product_name" json:"product_name"`
	ProductCode    string             `db:"product_code" json:"product_code"`
	StoreID        pgtype.UUID        `db:"store_id" json:"store_id"`
}

func (q *Queries) ListExpiringSoon(ctx context.Context, arg ListExpiringSoonParams) ([]ListExpiringSoonRow, error) {
	rows, err := q.db.Query(ctx, listExpiringSoon, arg.StoreID, arg.ExpirationDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpiringSoonRow
	for rows.Next() {
		var i ListExpiringSoonRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ExpirationDate,
			&i.Quantity,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductCode,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductExpirations = `-- name: ListProductExpirations :many
SELECT pe.id, pe.product_id, pe.batch_number, pe.expiration_date, pe.quantity, pe.created_at,
       p.name as product_name,
       p.code as product_code
FROM product_expirations pe
JOIN products p ON pe.product_id = p.id
WHERE p.store_id = $1
ORDER BY pe.expiration_date ASC
LIMIT $2 OFFSET $3
`

type ListProductExpirationsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListProductExpirationsRow struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	ProductID      pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber    pgtype.Text        `db:"batch_number" json:"batch_number"`
	ExpirationDate pgtype.Date        `db:"expiration_date" json:"expiration_date"`
	Quantity       int32              `db:"quantity" json:"quantity"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ProductName    string             `db:"product_name" json:"product_name"`
	ProductCode    string             `db:"product_code" json:"product_code"`
}

func (q *Queries) ListProductExpirations(ctx context.Context, arg ListProductExpirationsParams) ([]ListProductExpirationsRow, error) {
	rows, err := q.db.Query(ctx, listProductExpirations, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductExpirationsRow
	for rows.Next() {
		var i ListProductExpirationsRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ExpirationDate,
			&i.Quantity,
			&i.CreatedAt,
			&i.ProductName,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductExpiration = `-- name: UpdateProductExpiration :one
UPDATE product_expirations SET
    batch_number = COALESCE($1, batch_number),
    expiration_date = COALESCE($2, expiration_date),
    quantity = COALESCE($3, quantity)
WHERE id = $4
RETURNING id, product_id, batch_number, expiration_date, quantity, created_at
`

type UpdateProductExpirationParams struct {
	BatchNumber    pgtype.Text `db:"batch_number" json:"batch_number"`
	ExpirationDate pgtype.Date `db:"expiration_date" json:"expiration_date"`
	Quantity       pgtype.Int4 `db:"quantity" json:"quantity"`
	ID             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateProductExpiration(ctx context.Context, arg UpdateProductExpirationParams) (ProductExpiration, error) {
	row := q.db.QueryRow(ctx, updateProductExpiration,
		arg.BatchNumber,
		arg.ExpirationDate,
		arg.Quantity,
		arg.ID,
	)
	var i ProductExpiration
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ExpirationDate,
		&i.Quantity,
		&i.CreatedAt,
	)
	return i, err
}
