// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateCategory(ctx context.Context, arg CreateCategoryParams) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error)
	// Debt Payments queries
	CreateDebtPayment(ctx context.Context, arg CreateDebtPaymentParams) (DebtPayment, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductExpiration(ctx context.Context, arg CreateProductExpirationParams) (ProductExpiration, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	// Sale Items queries
	CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error)
	CreateStockChange(ctx context.Context, arg CreateStockChangeParams) (StockChange, error)
	CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error)
	CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	DeleteCategory(ctx context.Context, id pgtype.UUID) (Category, error)
	DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) (Customer, error)
	DeleteDebt(ctx context.Context, arg DeleteDebtParams) error
	DeleteDebtPayment(ctx context.Context, id pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	DeleteProductExpiration(ctx context.Context, id pgtype.UUID) error
	DeleteSale(ctx context.Context, arg DeleteSaleParams) error
	DeleteSaleItem(ctx context.Context, id pgtype.UUID) error
	DeleteStore(ctx context.Context, id pgtype.UUID) (Store, error)
	DeleteSupplier(ctx context.Context, id pgtype.UUID) (Supplier, error)
	DeleteUser(ctx context.Context, id pgtype.UUID) error
	GetCategories(ctx context.Context, isActive bool) ([]Category, error)
	GetCategoryById(ctx context.Context, id pgtype.UUID) (Category, error)
	GetCategoryBySlug(ctx context.Context, slug string) (Category, error)
	GetCustomerById(ctx context.Context, arg GetCustomerByIdParams) (Customer, error)
	GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error)
	GetCustomersWithDebt(ctx context.Context, arg GetCustomersWithDebtParams) ([]Customer, error)
	GetDebtById(ctx context.Context, arg GetDebtByIdParams) (GetDebtByIdRow, error)
	GetDebtPaymentById(ctx context.Context, id pgtype.UUID) (GetDebtPaymentByIdRow, error)
	GetDebtPayments(ctx context.Context, debtID pgtype.UUID) ([]GetDebtPaymentsRow, error)
	GetDebtSummary(ctx context.Context, storeID pgtype.UUID) (GetDebtSummaryRow, error)
	GetProductByCode(ctx context.Context, code string) (Product, error)
	GetProductById(ctx context.Context, id pgtype.UUID) (GetProductByIdRow, error)
	GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error)
	GetProductExpirationById(ctx context.Context, id pgtype.UUID) (GetProductExpirationByIdRow, error)
	GetSaleById(ctx context.Context, arg GetSaleByIdParams) (GetSaleByIdRow, error)
	GetSaleItemById(ctx context.Context, id pgtype.UUID) (SaleItem, error)
	GetSaleItems(ctx context.Context, saleID pgtype.UUID) ([]GetSaleItemsRow, error)
	GetSalesTotalByDateRange(ctx context.Context, arg GetSalesTotalByDateRangeParams) (GetSalesTotalByDateRangeRow, error)
	GetStockChangeById(ctx context.Context, id pgtype.UUID) (GetStockChangeByIdRow, error)
	GetStoreById(ctx context.Context, id pgtype.UUID) (Store, error)
	GetStoreBySlug(ctx context.Context, slug string) (Store, error)
	GetStoresByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Store, error)
	GetSupplierById(ctx context.Context, id pgtype.UUID) (Supplier, error)
	GetSupplierBySlug(ctx context.Context, slug string) (Supplier, error)
	GetSupplierProducts(ctx context.Context, supplierID pgtype.UUID) ([]Product, error)
	GetUser(ctx context.Context, id pgtype.UUID) (User, error)
	GetUserByEmail(ctx context.Context, email string) (User, error)
	GetUserStores(ctx context.Context, userID pgtype.UUID) ([]Store, error)
	HardDeleteProduct(ctx context.Context, id pgtype.UUID) error
	HardDeleteStore(ctx context.Context, id pgtype.UUID) error
	HardDeleteSupplier(ctx context.Context, id pgtype.UUID) error
	ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error)
	ListDebts(ctx context.Context, arg ListDebtsParams) ([]ListDebtsRow, error)
	ListDebtsByCustomer(ctx context.Context, arg ListDebtsByCustomerParams) ([]Debt, error)
	ListDebtsByStatus(ctx context.Context, arg ListDebtsByStatusParams) ([]ListDebtsByStatusRow, error)
	ListExpirationsByProduct(ctx context.Context, productID pgtype.UUID) ([]ProductExpiration, error)
	ListExpiredProducts(ctx context.Context, storeID pgtype.UUID) ([]ListExpiredProductsRow, error)
	ListExpiringSoon(ctx context.Context, arg ListExpiringSoonParams) ([]ListExpiringSoonRow, error)
	ListLowStockProducts(ctx context.Context) ([]ListLowStockProductsRow, error)
	ListOverdueDebts(ctx context.Context, storeID pgtype.UUID) ([]ListOverdueDebtsRow, error)
	ListProductExpirations(ctx context.Context, arg ListProductExpirationsParams) ([]ListProductExpirationsRow, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error)
	ListProductsByCategory(ctx context.Context, categoryID pgtype.UUID) ([]ListProductsByCategoryRow, error)
	ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error)
	ListSalesByCustomer(ctx context.Context, arg ListSalesByCustomerParams) ([]ListSalesByCustomerRow, error)
	ListSalesByDateRange(ctx context.Context, arg ListSalesByDateRangeParams) ([]ListSalesByDateRangeRow, error)
	ListStockChanges(ctx context.Context, arg ListStockChangesParams) ([]ListStockChangesRow, error)
	ListStockChangesByDateRange(ctx context.Context, arg ListStockChangesByDateRangeParams) ([]ListStockChangesByDateRangeRow, error)
	ListStockChangesByProduct(ctx context.Context, productID pgtype.UUID) ([]ListStockChangesByProductRow, error)
	ListStockChangesByType(ctx context.Context, arg ListStockChangesByTypeParams) ([]ListStockChangesByTypeRow, error)
	ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error)
	ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error)
	SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error)
	SearchSuppliers(ctx context.Context, arg SearchSuppliersParams) ([]Supplier, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerTotals(ctx context.Context, arg UpdateCustomerTotalsParams) (Customer, error)
	UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error)
	UpdateDebtStatus(ctx context.Context, arg UpdateDebtStatusParams) (Debt, error)
	UpdateLoginAttempts(ctx context.Context, arg UpdateLoginAttemptsParams) (User, error)
	UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductExpiration(ctx context.Context, arg UpdateProductExpirationParams) (ProductExpiration, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateSale(ctx context.Context, arg UpdateSaleParams) (Sale, error)
	UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error)
	VerifyEmail(ctx context.Context, id pgtype.UUID) (User, error)
}

var _ Querier = (*Queries)(nil)
