// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stock_change.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockChange = `-- name: CreateStockChange :one
INSERT INTO stock_changes (
    product_id,
    user_id,
    change_type,
    quantity,
    previous_quantity,
    new_quantity,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, product_id, user_id, change_type, quantity, previous_quantity, new_quantity, change_date, notes
`

type CreateStockChangeParams struct {
	ProductID        pgtype.UUID `db:"product_id" json:"product_id"`
	UserID           pgtype.UUID `db:"user_id" json:"user_id"`
	ChangeType       string      `db:"change_type" json:"change_type"`
	Quantity         int32       `db:"quantity" json:"quantity"`
	PreviousQuantity int32       `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity      int32       `db:"new_quantity" json:"new_quantity"`
	Notes            pgtype.Text `db:"notes" json:"notes"`
}

func (q *Queries) CreateStockChange(ctx context.Context, arg CreateStockChangeParams) (StockChange, error) {
	row := q.db.QueryRow(ctx, createStockChange,
		arg.ProductID,
		arg.UserID,
		arg.ChangeType,
		arg.Quantity,
		arg.PreviousQuantity,
		arg.NewQuantity,
		arg.Notes,
	)
	var i StockChange
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.ChangeType,
		&i.Quantity,
		&i.PreviousQuantity,
		&i.NewQuantity,
		&i.ChangeDate,
		&i.Notes,
	)
	return i, err
}

const getStockChangeById = `-- name: GetStockChangeById :one
SELECT sc.id, sc.product_id, sc.user_id, sc.change_type, sc.quantity, sc.previous_quantity, sc.new_quantity, sc.change_date, sc.notes,
       p.name as product_name,
       p.code as product_code,
       u.name as user_name
FROM stock_changes sc
LEFT JOIN products p ON sc.product_id = p.id
LEFT JOIN users u ON sc.user_id = u.id
WHERE sc.id = $1
`

type GetStockChangeByIdRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	ProductID        pgtype.UUID        `db:"product_id" json:"product_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	ChangeType       string             `db:"change_type" json:"change_type"`
	Quantity         int32              `db:"quantity" json:"quantity"`
	PreviousQuantity int32              `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity      int32              `db:"new_quantity" json:"new_quantity"`
	ChangeDate       pgtype.Timestamptz `db:"change_date" json:"change_date"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ProductName      pgtype.Text        `db:"product_name" json:"product_name"`
	ProductCode      pgtype.Text        `db:"product_code" json:"product_code"`
	UserName         pgtype.Text        `db:"user_name" json:"user_name"`
}

func (q *Queries) GetStockChangeById(ctx context.Context, id pgtype.UUID) (GetStockChangeByIdRow, error) {
	row := q.db.QueryRow(ctx, getStockChangeById, id)
	var i GetStockChangeByIdRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.UserID,
		&i.ChangeType,
		&i.Quantity,
		&i.PreviousQuantity,
		&i.NewQuantity,
		&i.ChangeDate,
		&i.Notes,
		&i.ProductName,
		&i.ProductCode,
		&i.UserName,
	)
	return i, err
}

const listStockChanges = `-- name: ListStockChanges :many
SELECT sc.id, sc.product_id, sc.user_id, sc.change_type, sc.quantity, sc.previous_quantity, sc.new_quantity, sc.change_date, sc.notes,
       p.name as product_name,
       p.code as product_code,
       u.name as user_name
FROM stock_changes sc
LEFT JOIN products p ON sc.product_id = p.id
LEFT JOIN users u ON sc.user_id = u.id
WHERE p.store_id = $1
ORDER BY sc.change_date DESC
LIMIT $2 OFFSET $3
`

type ListStockChangesParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListStockChangesRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	ProductID        pgtype.UUID        `db:"product_id" json:"product_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	ChangeType       string             `db:"change_type" json:"change_type"`
	Quantity         int32              `db:"quantity" json:"quantity"`
	PreviousQuantity int32              `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity      int32              `db:"new_quantity" json:"new_quantity"`
	ChangeDate       pgtype.Timestamptz `db:"change_date" json:"change_date"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ProductName      pgtype.Text        `db:"product_name" json:"product_name"`
	ProductCode      pgtype.Text        `db:"product_code" json:"product_code"`
	UserName         pgtype.Text        `db:"user_name" json:"user_name"`
}

func (q *Queries) ListStockChanges(ctx context.Context, arg ListStockChangesParams) ([]ListStockChangesRow, error) {
	rows, err := q.db.Query(ctx, listStockChanges, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockChangesRow
	for rows.Next() {
		var i ListStockChangesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.ChangeType,
			&i.Quantity,
			&i.PreviousQuantity,
			&i.NewQuantity,
			&i.ChangeDate,
			&i.Notes,
			&i.ProductName,
			&i.ProductCode,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockChangesByDateRange = `-- name: ListStockChangesByDateRange :many
SELECT sc.id, sc.product_id, sc.user_id, sc.change_type, sc.quantity, sc.previous_quantity, sc.new_quantity, sc.change_date, sc.notes,
       p.name as product_name,
       p.code as product_code,
       u.name as user_name
FROM stock_changes sc
LEFT JOIN products p ON sc.product_id = p.id
LEFT JOIN users u ON sc.user_id = u.id
WHERE p.store_id = $1 
  AND sc.change_date >= $2 
  AND sc.change_date <= $3
ORDER BY sc.change_date DESC
`

type ListStockChangesByDateRangeParams struct {
	StoreID      pgtype.UUID        `db:"store_id" json:"store_id"`
	ChangeDate   pgtype.Timestamptz `db:"change_date" json:"change_date"`
	ChangeDate_2 pgtype.Timestamptz `db:"change_date_2" json:"change_date_2"`
}

type ListStockChangesByDateRangeRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	ProductID        pgtype.UUID        `db:"product_id" json:"product_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	ChangeType       string             `db:"change_type" json:"change_type"`
	Quantity         int32              `db:"quantity" json:"quantity"`
	PreviousQuantity int32              `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity      int32              `db:"new_quantity" json:"new_quantity"`
	ChangeDate       pgtype.Timestamptz `db:"change_date" json:"change_date"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ProductName      pgtype.Text        `db:"product_name" json:"product_name"`
	ProductCode      pgtype.Text        `db:"product_code" json:"product_code"`
	UserName         pgtype.Text        `db:"user_name" json:"user_name"`
}

func (q *Queries) ListStockChangesByDateRange(ctx context.Context, arg ListStockChangesByDateRangeParams) ([]ListStockChangesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listStockChangesByDateRange, arg.StoreID, arg.ChangeDate, arg.ChangeDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockChangesByDateRangeRow
	for rows.Next() {
		var i ListStockChangesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.ChangeType,
			&i.Quantity,
			&i.PreviousQuantity,
			&i.NewQuantity,
			&i.ChangeDate,
			&i.Notes,
			&i.ProductName,
			&i.ProductCode,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockChangesByProduct = `-- name: ListStockChangesByProduct :many
SELECT sc.id, sc.product_id, sc.user_id, sc.change_type, sc.quantity, sc.previous_quantity, sc.new_quantity, sc.change_date, sc.notes,
       u.name as user_name
FROM stock_changes sc
LEFT JOIN users u ON sc.user_id = u.id
WHERE sc.product_id = $1
ORDER BY sc.change_date DESC
`

type ListStockChangesByProductRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	ProductID        pgtype.UUID        `db:"product_id" json:"product_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	ChangeType       string             `db:"change_type" json:"change_type"`
	Quantity         int32              `db:"quantity" json:"quantity"`
	PreviousQuantity int32              `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity      int32              `db:"new_quantity" json:"new_quantity"`
	ChangeDate       pgtype.Timestamptz `db:"change_date" json:"change_date"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	UserName         pgtype.Text        `db:"user_name" json:"user_name"`
}

func (q *Queries) ListStockChangesByProduct(ctx context.Context, productID pgtype.UUID) ([]ListStockChangesByProductRow, error) {
	rows, err := q.db.Query(ctx, listStockChangesByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockChangesByProductRow
	for rows.Next() {
		var i ListStockChangesByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.ChangeType,
			&i.Quantity,
			&i.PreviousQuantity,
			&i.NewQuantity,
			&i.ChangeDate,
			&i.Notes,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockChangesByType = `-- name: ListStockChangesByType :many
SELECT sc.id, sc.product_id, sc.user_id, sc.change_type, sc.quantity, sc.previous_quantity, sc.new_quantity, sc.change_date, sc.notes,
       p.name as product_name,
       p.code as product_code,
       u.name as user_name
FROM stock_changes sc
LEFT JOIN products p ON sc.product_id = p.id
LEFT JOIN users u ON sc.user_id = u.id
WHERE p.store_id = $1 AND sc.change_type = $2
ORDER BY sc.change_date DESC
LIMIT $3 OFFSET $4
`

type ListStockChangesByTypeParams struct {
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
	ChangeType string      `db:"change_type" json:"change_type"`
	Limit      int32       `db:"limit" json:"limit"`
	Offset     int32       `db:"offset" json:"offset"`
}

type ListStockChangesByTypeRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	ProductID        pgtype.UUID        `db:"product_id" json:"product_id"`
	UserID           pgtype.UUID        `db:"user_id" json:"user_id"`
	ChangeType       string             `db:"change_type" json:"change_type"`
	Quantity         int32              `db:"quantity" json:"quantity"`
	PreviousQuantity int32              `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity      int32              `db:"new_quantity" json:"new_quantity"`
	ChangeDate       pgtype.Timestamptz `db:"change_date" json:"change_date"`
	Notes            pgtype.Text        `db:"notes" json:"notes"`
	ProductName      pgtype.Text        `db:"product_name" json:"product_name"`
	ProductCode      pgtype.Text        `db:"product_code" json:"product_code"`
	UserName         pgtype.Text        `db:"user_name" json:"user_name"`
}

func (q *Queries) ListStockChangesByType(ctx context.Context, arg ListStockChangesByTypeParams) ([]ListStockChangesByTypeRow, error) {
	rows, err := q.db.Query(ctx, listStockChangesByType,
		arg.StoreID,
		arg.ChangeType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockChangesByTypeRow
	for rows.Next() {
		var i ListStockChangesByTypeRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.UserID,
			&i.ChangeType,
			&i.Quantity,
			&i.PreviousQuantity,
			&i.NewQuantity,
			&i.ChangeDate,
			&i.Notes,
			&i.ProductName,
			&i.ProductCode,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
