ALTER TABLE categories ADD COLUMN slug VARCHAR(50) NOT NULL UNIQUE;
ALTER TABLE suppliers ADD COLUMN slug VARCHAR(50) NOT NULL UNIQUE;
ALTER TABLE products ADD COLUMN slug VARCHAR(50) NOT NULL UNIQUE;