ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS bank_name VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS account_name VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS account_number VARCHAR(50);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS branch VARCHAR(100);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS swift_code VARCHAR(20);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS esewa_id VARCHAR(50);
ALTER TABLE suppliers ADD COLUMN IF NOT EXISTS khalti_id VARCHAR(50);
