// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: 12_product_variants.sql

package db

import (
	"context"
	"encoding/json"

	"github.com/jackc/pgx/v5/pgtype"
)

const archiveProductVariant = `-- name: ArchiveProductVariant :exec
UPDATE product_variants
SET archived_at = CURRENT_TIMESTAMP
WHERE id = $1
`

func (q *Queries) ArchiveProductVariant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, archiveProductVariant, id)
	return err
}

const createProductVariant = `-- name: CreateProductVariant :one
INSERT INTO product_variants (
    product_id,
    sku,
    barcode,
    attributes,
    cost_price,
    selling_price,
    stock_level,
    image_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, product_id, sku, barcode, attributes, cost_price, selling_price, stock_level, image_url, archived_at, created_at, updated_at
`

type CreateProductVariantParams struct {
	ProductID    pgtype.UUID     `db:"product_id" json:"product_id"`
	Sku          string          `db:"sku" json:"sku"`
	Barcode      pgtype.Text     `db:"barcode" json:"barcode"`
	Attributes   json.RawMessage `db:"attributes" json:"attributes"`
	CostPrice    pgtype.Numeric  `db:"cost_price" json:"cost_price"`
	SellingPrice pgtype.Numeric  `db:"selling_price" json:"selling_price"`
	StockLevel   int32           `db:"stock_level" json:"stock_level"`
	ImageUrl     pgtype.Text     `db:"image_url" json:"image_url"`
}

func (q *Queries) CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, createProductVariant,
		arg.ProductID,
		arg.Sku,
		arg.Barcode,
		arg.Attributes,
		arg.CostPrice,
		arg.SellingPrice,
		arg.StockLevel,
		arg.ImageUrl,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.CostPrice,
		&i.SellingPrice,
		&i.StockLevel,
		&i.ImageUrl,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductVariant = `-- name: DeleteProductVariant :exec
DELETE FROM product_variants
WHERE id = $1 AND archived_at IS NULL
`

func (q *Queries) DeleteProductVariant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProductVariant, id)
	return err
}

const deleteVariantsByProduct = `-- name: DeleteVariantsByProduct :exec
DELETE FROM product_variants
WHERE product_id = $1
`

func (q *Queries) DeleteVariantsByProduct(ctx context.Context, productID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVariantsByProduct, productID)
	return err
}

const getProductVariant = `-- name: GetProductVariant :one
SELECT id, product_id, sku, barcode, attributes, cost_price, selling_price, stock_level, image_url, archived_at, created_at, updated_at FROM product_variants
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProductVariant(ctx context.Context, id pgtype.UUID) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getProductVariant, id)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.CostPrice,
		&i.SellingPrice,
		&i.StockLevel,
		&i.ImageUrl,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantByBarcodeOrSKU = `-- name: GetVariantByBarcodeOrSKU :one
SELECT id, product_id, sku, barcode, attributes, cost_price, selling_price, stock_level, image_url, archived_at, created_at, updated_at FROM product_variants
WHERE barcode = $1 OR sku = $1 LIMIT 1
`

func (q *Queries) GetVariantByBarcodeOrSKU(ctx context.Context, barcode pgtype.Text) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantByBarcodeOrSKU, barcode)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.CostPrice,
		&i.SellingPrice,
		&i.StockLevel,
		&i.ImageUrl,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getVariantBySKU = `-- name: GetVariantBySKU :one
SELECT id, product_id, sku, barcode, attributes, cost_price, selling_price, stock_level, image_url, archived_at, created_at, updated_at FROM product_variants
WHERE sku = $1 LIMIT 1
`

func (q *Queries) GetVariantBySKU(ctx context.Context, sku string) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, getVariantBySKU, sku)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.CostPrice,
		&i.SellingPrice,
		&i.StockLevel,
		&i.ImageUrl,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listVariantsByProduct = `-- name: ListVariantsByProduct :many
SELECT id, product_id, sku, barcode, attributes, cost_price, selling_price, stock_level, image_url, archived_at, created_at, updated_at FROM product_variants
WHERE product_id = $1 AND archived_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListVariantsByProduct(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProduct, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Attributes,
			&i.CostPrice,
			&i.SellingPrice,
			&i.StockLevel,
			&i.ImageUrl,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVariantsByProducts = `-- name: ListVariantsByProducts :many
SELECT id, product_id, sku, barcode, attributes, cost_price, selling_price, stock_level, image_url, archived_at, created_at, updated_at FROM product_variants
WHERE product_id = ANY($1::uuid[]) AND archived_at IS NULL
ORDER BY product_id, created_at ASC
`

func (q *Queries) ListVariantsByProducts(ctx context.Context, dollar_1 []pgtype.UUID) ([]ProductVariant, error) {
	rows, err := q.db.Query(ctx, listVariantsByProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ProductVariant
	for rows.Next() {
		var i ProductVariant
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.Sku,
			&i.Barcode,
			&i.Attributes,
			&i.CostPrice,
			&i.SellingPrice,
			&i.StockLevel,
			&i.ImageUrl,
			&i.ArchivedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProductVariant = `-- name: UpdateProductVariant :one
UPDATE product_variants
SET 
    sku = COALESCE($2, sku),
    barcode = COALESCE($3, barcode),
    attributes = COALESCE($4, attributes),
    cost_price = COALESCE($5, cost_price),
    selling_price = COALESCE($6, selling_price),
    stock_level = COALESCE($7, stock_level),
    image_url = COALESCE($8, image_url),
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, product_id, sku, barcode, attributes, cost_price, selling_price, stock_level, image_url, archived_at, created_at, updated_at
`

type UpdateProductVariantParams struct {
	ID           pgtype.UUID     `db:"id" json:"id"`
	Sku          string          `db:"sku" json:"sku"`
	Barcode      pgtype.Text     `db:"barcode" json:"barcode"`
	Attributes   json.RawMessage `db:"attributes" json:"attributes"`
	CostPrice    pgtype.Numeric  `db:"cost_price" json:"cost_price"`
	SellingPrice pgtype.Numeric  `db:"selling_price" json:"selling_price"`
	StockLevel   int32           `db:"stock_level" json:"stock_level"`
	ImageUrl     pgtype.Text     `db:"image_url" json:"image_url"`
}

func (q *Queries) UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateProductVariant,
		arg.ID,
		arg.Sku,
		arg.Barcode,
		arg.Attributes,
		arg.CostPrice,
		arg.SellingPrice,
		arg.StockLevel,
		arg.ImageUrl,
	)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.CostPrice,
		&i.SellingPrice,
		&i.StockLevel,
		&i.ImageUrl,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateVariantStock = `-- name: UpdateVariantStock :one
UPDATE product_variants
SET 
    stock_level = stock_level - $2,
    updated_at = CURRENT_TIMESTAMP
WHERE id = $1
RETURNING id, product_id, sku, barcode, attributes, cost_price, selling_price, stock_level, image_url, archived_at, created_at, updated_at
`

type UpdateVariantStockParams struct {
	ID         pgtype.UUID `db:"id" json:"id"`
	StockLevel int32       `db:"stock_level" json:"stock_level"`
}

func (q *Queries) UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) (ProductVariant, error) {
	row := q.db.QueryRow(ctx, updateVariantStock, arg.ID, arg.StockLevel)
	var i ProductVariant
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.Sku,
		&i.Barcode,
		&i.Attributes,
		&i.CostPrice,
		&i.SellingPrice,
		&i.StockLevel,
		&i.ImageUrl,
		&i.ArchivedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
