// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: categories.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCategories = `-- name: CreateCategories :one
INSERT INTO categories(
    name,
    description,
    store_id
) VALUES (
    $1, $2, $3
) RETURNING id, name, description, store_id, created_at, updated_at
`

type CreateCategoriesParams struct {
	Name        string      `db:"name" json:"name"`
	Description pgtype.Text `db:"description" json:"description"`
	StoreID     pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error) {
	row := q.db.QueryRow(ctx, createCategories, arg.Name, arg.Description, arg.StoreID)
	var i Category
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Description,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCategories = `-- name: GetCategories :many
SELECT id, name, description, store_id, created_at, updated_at FROM categories WHERE store_id = $1
`

func (q *Queries) GetCategories(ctx context.Context, storeID pgtype.UUID) ([]Category, error) {
	rows, err := q.db.Query(ctx, getCategories, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Category
	for rows.Next() {
		var i Category
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.StoreID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
