// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    name,
    phone,
    store_id
) VALUES (
    $1, $2, $3
)
RETURNING id, name, phone, created_at, store_id
`

type CreateCustomerParams struct {
	Name    string      `db:"name" json:"name"`
	Phone   string      `db:"phone" json:"phone"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer, arg.Name, arg.Phone, arg.StoreID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.StoreID,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, name, phone, created_at, store_id FROM customers
WHERE phone = $1 AND store_id = $2
`

type GetCustomerByPhoneParams struct {
	Phone   string      `db:"phone" json:"phone"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, arg.Phone, arg.StoreID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Phone,
		&i.CreatedAt,
		&i.StoreID,
	)
	return i, err
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, name, phone, created_at, store_id FROM customers
WHERE store_id = $1
ORDER BY name
`

func (q *Queries) ListCustomers(ctx context.Context, storeID pgtype.UUID) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Phone,
			&i.CreatedAt,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
