// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: customer.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createCustomer = `-- name: CreateCustomer :one
INSERT INTO customers (
    store_id,
    name,
    phone,
    email,
    address,
    notification_token
) VALUES (
    $1, $2, $3, $4, $5, $6
) RETURNING id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at
`

type CreateCustomerParams struct {
	StoreID           pgtype.UUID `db:"store_id" json:"store_id"`
	Name              string      `db:"name" json:"name"`
	Phone             pgtype.Text `db:"phone" json:"phone"`
	Email             pgtype.Text `db:"email" json:"email"`
	Address           pgtype.Text `db:"address" json:"address"`
	NotificationToken pgtype.Text `db:"notification_token" json:"notification_token"`
}

func (q *Queries) CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, createCustomer,
		arg.StoreID,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.NotificationToken,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.NotificationToken,
		&i.TotalPurchases,
		&i.TotalDebt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteCustomer = `-- name: DeleteCustomer :one
UPDATE customers SET is_active = false, updated_at = NOW()
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at
`

type DeleteCustomerParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeleteCustomer(ctx context.Context, arg DeleteCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, deleteCustomer, arg.ID, arg.StoreID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.NotificationToken,
		&i.TotalPurchases,
		&i.TotalDebt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerById = `-- name: GetCustomerById :one
SELECT id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at FROM customers WHERE id = $1 AND store_id = $2
`

type GetCustomerByIdParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) GetCustomerById(ctx context.Context, arg GetCustomerByIdParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerById, arg.ID, arg.StoreID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.NotificationToken,
		&i.TotalPurchases,
		&i.TotalDebt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomerByPhone = `-- name: GetCustomerByPhone :one
SELECT id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at FROM customers WHERE phone = $1 AND store_id = $2
`

type GetCustomerByPhoneParams struct {
	Phone   pgtype.Text `db:"phone" json:"phone"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error) {
	row := q.db.QueryRow(ctx, getCustomerByPhone, arg.Phone, arg.StoreID)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.NotificationToken,
		&i.TotalPurchases,
		&i.TotalDebt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getCustomersWithDebt = `-- name: GetCustomersWithDebt :many
SELECT id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at FROM customers
WHERE store_id = $1 AND total_debt > 0 AND is_active = true
ORDER BY total_debt DESC
LIMIT $2 OFFSET $3
`

type GetCustomersWithDebtParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetCustomersWithDebt(ctx context.Context, arg GetCustomersWithDebtParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, getCustomersWithDebt, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.NotificationToken,
			&i.TotalPurchases,
			&i.TotalDebt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCustomers = `-- name: ListCustomers :many
SELECT id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at FROM customers 
WHERE store_id = $1 AND is_active = true
ORDER BY name
LIMIT $2 OFFSET $3
`

type ListCustomersParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListCustomers(ctx context.Context, arg ListCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, listCustomers, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.NotificationToken,
			&i.TotalPurchases,
			&i.TotalDebt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchCustomers = `-- name: SearchCustomers :many
SELECT id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at FROM customers
WHERE store_id = $1 
  AND (LOWER(name) LIKE LOWER($2) OR phone LIKE $2)
  AND is_active = true
ORDER BY name
LIMIT $3 OFFSET $4
`

type SearchCustomersParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Lower   string      `db:"lower" json:"lower"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error) {
	rows, err := q.db.Query(ctx, searchCustomers,
		arg.StoreID,
		arg.Lower,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Customer
	for rows.Next() {
		var i Customer
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Name,
			&i.Phone,
			&i.Email,
			&i.Address,
			&i.NotificationToken,
			&i.TotalPurchases,
			&i.TotalDebt,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateCustomer = `-- name: UpdateCustomer :one
UPDATE customers SET
    name = COALESCE($1, name),
    phone = COALESCE($2, phone),
    email = COALESCE($3, email),
    address = COALESCE($4, address),
    notification_token = COALESCE($5, notification_token),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $7 AND store_id = $8
RETURNING id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at
`

type UpdateCustomerParams struct {
	Name              pgtype.Text `db:"name" json:"name"`
	Phone             pgtype.Text `db:"phone" json:"phone"`
	Email             pgtype.Text `db:"email" json:"email"`
	Address           pgtype.Text `db:"address" json:"address"`
	NotificationToken pgtype.Text `db:"notification_token" json:"notification_token"`
	IsActive          pgtype.Bool `db:"is_active" json:"is_active"`
	ID                pgtype.UUID `db:"id" json:"id"`
	StoreID           pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomer,
		arg.Name,
		arg.Phone,
		arg.Email,
		arg.Address,
		arg.NotificationToken,
		arg.IsActive,
		arg.ID,
		arg.StoreID,
	)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.NotificationToken,
		&i.TotalPurchases,
		&i.TotalDebt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateCustomerTotals = `-- name: UpdateCustomerTotals :one
UPDATE customers SET
    total_purchases = $2,
    total_debt = $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, store_id, name, phone, email, address, notification_token, total_purchases, total_debt, is_active, created_at, updated_at
`

type UpdateCustomerTotalsParams struct {
	ID             pgtype.UUID    `db:"id" json:"id"`
	TotalPurchases pgtype.Numeric `db:"total_purchases" json:"total_purchases"`
	TotalDebt      pgtype.Numeric `db:"total_debt" json:"total_debt"`
}

func (q *Queries) UpdateCustomerTotals(ctx context.Context, arg UpdateCustomerTotalsParams) (Customer, error) {
	row := q.db.QueryRow(ctx, updateCustomerTotals, arg.ID, arg.TotalPurchases, arg.TotalDebt)
	var i Customer
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Name,
		&i.Phone,
		&i.Email,
		&i.Address,
		&i.NotificationToken,
		&i.TotalPurchases,
		&i.TotalDebt,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
