// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: debts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createDebt = `-- name: CreateDebt :one
INSERT INTO debts (
    store_id,
    customer_id,
    sale_id,
    amount_owed,
    amount_paid,
    due_date,
    status,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, store_id, customer_id, sale_id, amount_owed, amount_paid, due_date, status, notes, created_at, updated_at
`

type CreateDebtParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleID     pgtype.UUID        `db:"sale_id" json:"sale_id"`
	AmountOwed pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	DueDate    pgtype.Timestamptz `db:"due_date" json:"due_date"`
	Status     DebtStatus         `db:"status" json:"status"`
	Notes      pgtype.Text        `db:"notes" json:"notes"`
}

func (q *Queries) CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error) {
	row := q.db.QueryRow(ctx, createDebt,
		arg.StoreID,
		arg.CustomerID,
		arg.SaleID,
		arg.AmountOwed,
		arg.AmountPaid,
		arg.DueDate,
		arg.Status,
		arg.Notes,
	)
	var i Debt
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.CustomerID,
		&i.SaleID,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.DueDate,
		&i.Status,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
