// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (store_id, category, description, amount, expense_date, payment_method, receipt_url)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, store_id, category, description, amount, expense_date, payment_method, receipt_url, created_at
`

type CreateExpenseParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	Category      string             `db:"category" json:"category"`
	Description   pgtype.Text        `db:"description" json:"description"`
	Amount        pgtype.Numeric     `db:"amount" json:"amount"`
	ExpenseDate   pgtype.Timestamptz `db:"expense_date" json:"expense_date"`
	PaymentMethod pgtype.Text        `db:"payment_method" json:"payment_method"`
	ReceiptUrl    pgtype.Text        `db:"receipt_url" json:"receipt_url"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.StoreID,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.ExpenseDate,
		arg.PaymentMethod,
		arg.ReceiptUrl,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.ExpenseDate,
		&i.PaymentMethod,
		&i.ReceiptUrl,
		&i.CreatedAt,
	)
	return i, err
}

const deleteExpense = `-- name: DeleteExpense :exec
DELETE FROM expenses
WHERE id = $1 AND store_id = $2
`

type DeleteExpenseParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error {
	_, err := q.db.Exec(ctx, deleteExpense, arg.ID, arg.StoreID)
	return err
}

const getDailyExpenses = `-- name: GetDailyExpenses :many
SELECT 
    DATE(expense_date)::VARCHAR as expense_date,
    COALESCE(SUM(amount), 0)::DECIMAL(12,2) as daily_total
FROM expenses
WHERE store_id = $1 AND expense_date BETWEEN $2 AND $3
GROUP BY DATE(expense_date)
ORDER BY DATE(expense_date)
`

type GetDailyExpensesParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	ExpenseDate   pgtype.Timestamptz `db:"expense_date" json:"expense_date"`
	ExpenseDate_2 pgtype.Timestamptz `db:"expense_date_2" json:"expense_date_2"`
}

type GetDailyExpensesRow struct {
	ExpenseDate string         `db:"expense_date" json:"expense_date"`
	DailyTotal  pgtype.Numeric `db:"daily_total" json:"daily_total"`
}

func (q *Queries) GetDailyExpenses(ctx context.Context, arg GetDailyExpensesParams) ([]GetDailyExpensesRow, error) {
	rows, err := q.db.Query(ctx, getDailyExpenses, arg.StoreID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailyExpensesRow
	for rows.Next() {
		var i GetDailyExpensesRow
		if err := rows.Scan(&i.ExpenseDate, &i.DailyTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpense = `-- name: GetExpense :one
SELECT id, store_id, category, description, amount, expense_date, payment_method, receipt_url, created_at FROM expenses
WHERE id = $1 AND store_id = $2
`

type GetExpenseParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpense, arg.ID, arg.StoreID)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.ExpenseDate,
		&i.PaymentMethod,
		&i.ReceiptUrl,
		&i.CreatedAt,
	)
	return i, err
}

const getExpenseSummary = `-- name: GetExpenseSummary :one
SELECT 
    COUNT(*) as total_count,
    COALESCE(SUM(amount), 0)::DECIMAL(12,2) as total_amount
FROM expenses
WHERE store_id = $1 AND expense_date BETWEEN $2 AND $3
`

type GetExpenseSummaryParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	ExpenseDate   pgtype.Timestamptz `db:"expense_date" json:"expense_date"`
	ExpenseDate_2 pgtype.Timestamptz `db:"expense_date_2" json:"expense_date_2"`
}

type GetExpenseSummaryRow struct {
	TotalCount  int64          `db:"total_count" json:"total_count"`
	TotalAmount pgtype.Numeric `db:"total_amount" json:"total_amount"`
}

func (q *Queries) GetExpenseSummary(ctx context.Context, arg GetExpenseSummaryParams) (GetExpenseSummaryRow, error) {
	row := q.db.QueryRow(ctx, getExpenseSummary, arg.StoreID, arg.ExpenseDate, arg.ExpenseDate_2)
	var i GetExpenseSummaryRow
	err := row.Scan(&i.TotalCount, &i.TotalAmount)
	return i, err
}

const getExpenseTotalsByCategory = `-- name: GetExpenseTotalsByCategory :many
SELECT 
    category,
    COUNT(*) as count,
    COALESCE(SUM(amount), 0)::DECIMAL(12,2) as total
FROM expenses
WHERE store_id = $1 AND expense_date BETWEEN $2 AND $3
GROUP BY category
ORDER BY total DESC
`

type GetExpenseTotalsByCategoryParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	ExpenseDate   pgtype.Timestamptz `db:"expense_date" json:"expense_date"`
	ExpenseDate_2 pgtype.Timestamptz `db:"expense_date_2" json:"expense_date_2"`
}

type GetExpenseTotalsByCategoryRow struct {
	Category string         `db:"category" json:"category"`
	Count    int64          `db:"count" json:"count"`
	Total    pgtype.Numeric `db:"total" json:"total"`
}

func (q *Queries) GetExpenseTotalsByCategory(ctx context.Context, arg GetExpenseTotalsByCategoryParams) ([]GetExpenseTotalsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getExpenseTotalsByCategory, arg.StoreID, arg.ExpenseDate, arg.ExpenseDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpenseTotalsByCategoryRow
	for rows.Next() {
		var i GetExpenseTotalsByCategoryRow
		if err := rows.Scan(&i.Category, &i.Count, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalExpensesForPeriod = `-- name: GetTotalExpensesForPeriod :one
SELECT 
    COALESCE(SUM(amount), 0)::DECIMAL(12,2) as total_expenses
FROM expenses
WHERE store_id = $1 AND expense_date BETWEEN $2 AND $3
`

type GetTotalExpensesForPeriodParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	ExpenseDate   pgtype.Timestamptz `db:"expense_date" json:"expense_date"`
	ExpenseDate_2 pgtype.Timestamptz `db:"expense_date_2" json:"expense_date_2"`
}

func (q *Queries) GetTotalExpensesForPeriod(ctx context.Context, arg GetTotalExpensesForPeriodParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalExpensesForPeriod, arg.StoreID, arg.ExpenseDate, arg.ExpenseDate_2)
	var total_expenses pgtype.Numeric
	err := row.Scan(&total_expenses)
	return total_expenses, err
}

const listExpenses = `-- name: ListExpenses :many
SELECT id, store_id, category, description, amount, expense_date, payment_method, receipt_url, created_at FROM expenses
WHERE store_id = $1
  AND expense_date BETWEEN $2 AND $3
  AND ($4::TEXT = '' OR category = $4)
ORDER BY expense_date DESC
`

type ListExpensesParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	ExpenseDate   pgtype.Timestamptz `db:"expense_date" json:"expense_date"`
	ExpenseDate_2 pgtype.Timestamptz `db:"expense_date_2" json:"expense_date_2"`
	Column4       string             `db:"column_4" json:"column_4"`
}

func (q *Queries) ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpenses,
		arg.StoreID,
		arg.ExpenseDate,
		arg.ExpenseDate_2,
		arg.Column4,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Category,
			&i.Description,
			&i.Amount,
			&i.ExpenseDate,
			&i.PaymentMethod,
			&i.ReceiptUrl,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET category = $2, description = $3, amount = $4, expense_date = $5, payment_method = $6
WHERE id = $1 AND store_id = $7
RETURNING id, store_id, category, description, amount, expense_date, payment_method, receipt_url, created_at
`

type UpdateExpenseParams struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Category      string             `db:"category" json:"category"`
	Description   pgtype.Text        `db:"description" json:"description"`
	Amount        pgtype.Numeric     `db:"amount" json:"amount"`
	ExpenseDate   pgtype.Timestamptz `db:"expense_date" json:"expense_date"`
	PaymentMethod pgtype.Text        `db:"payment_method" json:"payment_method"`
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Category,
		arg.Description,
		arg.Amount,
		arg.ExpenseDate,
		arg.PaymentMethod,
		arg.StoreID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Category,
		&i.Description,
		&i.Amount,
		&i.ExpenseDate,
		&i.PaymentMethod,
		&i.ReceiptUrl,
		&i.CreatedAt,
	)
	return i, err
}
