// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: inventory_reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getExpiringProductsReport = `-- name: GetExpiringProductsReport :many
SELECT
    p.id as product_id,
    p.name as product_name,
    c.name as category_name,
    p.stock_quantity,
    p.expires_at,
    p.cost_price,
    (p.stock_quantity * p.cost_price)::DECIMAL(12,2) as capital_at_risk,
    EXTRACT(DAY FROM (p.expires_at - NOW()))::INT as days_until_expiry
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.store_id = $1
    AND p.status IN ('active', 'expiring')
    AND p.expires_at IS NOT NULL
    AND p.expires_at <= NOW() + INTERVAL '30 days'
ORDER BY p.expires_at ASC
`

type GetExpiringProductsReportRow struct {
	ProductID       pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName     string             `db:"product_name" json:"product_name"`
	CategoryName    pgtype.Text        `db:"category_name" json:"category_name"`
	StockQuantity   int32              `db:"stock_quantity" json:"stock_quantity"`
	ExpiresAt       pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	CostPrice       pgtype.Numeric     `db:"cost_price" json:"cost_price"`
	CapitalAtRisk   pgtype.Numeric     `db:"capital_at_risk" json:"capital_at_risk"`
	DaysUntilExpiry int32              `db:"days_until_expiry" json:"days_until_expiry"`
}

func (q *Queries) GetExpiringProductsReport(ctx context.Context, storeID pgtype.UUID) ([]GetExpiringProductsReportRow, error) {
	rows, err := q.db.Query(ctx, getExpiringProductsReport, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiringProductsReportRow
	for rows.Next() {
		var i GetExpiringProductsReportRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.CategoryName,
			&i.StockQuantity,
			&i.ExpiresAt,
			&i.CostPrice,
			&i.CapitalAtRisk,
			&i.DaysUntilExpiry,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryValuation = `-- name: GetInventoryValuation :many
SELECT
    p.id as product_id,
    p.name as product_name,
    c.name as category_name,
    p.stock_quantity,
    p.cost_price,
    p.price as selling_price,
    (p.stock_quantity * p.cost_price)::DECIMAL(12,2) as cost_value,
    (p.stock_quantity * p.price)::DECIMAL(12,2) as retail_value,
    ((p.price - p.cost_price) * p.stock_quantity)::DECIMAL(12,2) as potential_profit
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.store_id = $1 AND p.status = 'active'
ORDER BY cost_value DESC
`

type GetInventoryValuationRow struct {
	ProductID       pgtype.UUID    `db:"product_id" json:"product_id"`
	ProductName     string         `db:"product_name" json:"product_name"`
	CategoryName    pgtype.Text    `db:"category_name" json:"category_name"`
	StockQuantity   int32          `db:"stock_quantity" json:"stock_quantity"`
	CostPrice       pgtype.Numeric `db:"cost_price" json:"cost_price"`
	SellingPrice    pgtype.Numeric `db:"selling_price" json:"selling_price"`
	CostValue       pgtype.Numeric `db:"cost_value" json:"cost_value"`
	RetailValue     pgtype.Numeric `db:"retail_value" json:"retail_value"`
	PotentialProfit pgtype.Numeric `db:"potential_profit" json:"potential_profit"`
}

func (q *Queries) GetInventoryValuation(ctx context.Context, storeID pgtype.UUID) ([]GetInventoryValuationRow, error) {
	rows, err := q.db.Query(ctx, getInventoryValuation, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryValuationRow
	for rows.Next() {
		var i GetInventoryValuationRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.CategoryName,
			&i.StockQuantity,
			&i.CostPrice,
			&i.SellingPrice,
			&i.CostValue,
			&i.RetailValue,
			&i.PotentialProfit,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryValuationByCategory = `-- name: GetInventoryValuationByCategory :many
SELECT
    c.id as category_id,
    c.name as category_name,
    COUNT(p.id) as product_count,
    SUM(p.stock_quantity)::INT as total_units,
    COALESCE(SUM(p.stock_quantity * p.cost_price), 0)::DECIMAL(12,2) as total_cost_value,
    COALESCE(SUM(p.stock_quantity * p.price), 0)::DECIMAL(12,2) as total_retail_value
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.store_id = $1 AND p.status = 'active'
GROUP BY c.id, c.name
ORDER BY total_cost_value DESC
`

type GetInventoryValuationByCategoryRow struct {
	CategoryID       pgtype.UUID    `db:"category_id" json:"category_id"`
	CategoryName     string         `db:"category_name" json:"category_name"`
	ProductCount     int64          `db:"product_count" json:"product_count"`
	TotalUnits       int32          `db:"total_units" json:"total_units"`
	TotalCostValue   pgtype.Numeric `db:"total_cost_value" json:"total_cost_value"`
	TotalRetailValue pgtype.Numeric `db:"total_retail_value" json:"total_retail_value"`
}

func (q *Queries) GetInventoryValuationByCategory(ctx context.Context, storeID pgtype.UUID) ([]GetInventoryValuationByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getInventoryValuationByCategory, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInventoryValuationByCategoryRow
	for rows.Next() {
		var i GetInventoryValuationByCategoryRow
		if err := rows.Scan(
			&i.CategoryID,
			&i.CategoryName,
			&i.ProductCount,
			&i.TotalUnits,
			&i.TotalCostValue,
			&i.TotalRetailValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryValuationSummary = `-- name: GetInventoryValuationSummary :one
SELECT
    COUNT(*) as total_products,
    SUM(stock_quantity)::INT as total_units,
    COALESCE(SUM(stock_quantity * cost_price), 0)::DECIMAL(12,2) as total_cost_value,
    COALESCE(SUM(stock_quantity * price), 0)::DECIMAL(12,2) as total_retail_value,
    COALESCE(SUM((price - cost_price) * stock_quantity), 0)::DECIMAL(12,2) as total_potential_profit
FROM products
WHERE store_id = $1 AND status = 'active'
`

type GetInventoryValuationSummaryRow struct {
	TotalProducts        int64          `db:"total_products" json:"total_products"`
	TotalUnits           int32          `db:"total_units" json:"total_units"`
	TotalCostValue       pgtype.Numeric `db:"total_cost_value" json:"total_cost_value"`
	TotalRetailValue     pgtype.Numeric `db:"total_retail_value" json:"total_retail_value"`
	TotalPotentialProfit pgtype.Numeric `db:"total_potential_profit" json:"total_potential_profit"`
}

func (q *Queries) GetInventoryValuationSummary(ctx context.Context, storeID pgtype.UUID) (GetInventoryValuationSummaryRow, error) {
	row := q.db.QueryRow(ctx, getInventoryValuationSummary, storeID)
	var i GetInventoryValuationSummaryRow
	err := row.Scan(
		&i.TotalProducts,
		&i.TotalUnits,
		&i.TotalCostValue,
		&i.TotalRetailValue,
		&i.TotalPotentialProfit,
	)
	return i, err
}

const getLowStockReport = `-- name: GetLowStockReport :many
SELECT
    p.id as product_id,
    p.name as product_name,
    c.name as category_name,
    p.stock_quantity,
    p.low_stock_threshold,
    (p.low_stock_threshold - p.stock_quantity)::INT as units_below_threshold,
    p.cost_price,
    (p.cost_price * (p.low_stock_threshold - p.stock_quantity))::DECIMAL(12,2) as reorder_cost
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
WHERE p.store_id = $1
    AND p.status = 'active'
    AND p.stock_quantity <= p.low_stock_threshold
ORDER BY units_below_threshold DESC
`

type GetLowStockReportRow struct {
	ProductID           pgtype.UUID    `db:"product_id" json:"product_id"`
	ProductName         string         `db:"product_name" json:"product_name"`
	CategoryName        pgtype.Text    `db:"category_name" json:"category_name"`
	StockQuantity       int32          `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold   pgtype.Int4    `db:"low_stock_threshold" json:"low_stock_threshold"`
	UnitsBelowThreshold int32          `db:"units_below_threshold" json:"units_below_threshold"`
	CostPrice           pgtype.Numeric `db:"cost_price" json:"cost_price"`
	ReorderCost         pgtype.Numeric `db:"reorder_cost" json:"reorder_cost"`
}

func (q *Queries) GetLowStockReport(ctx context.Context, storeID pgtype.UUID) ([]GetLowStockReportRow, error) {
	rows, err := q.db.Query(ctx, getLowStockReport, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLowStockReportRow
	for rows.Next() {
		var i GetLowStockReportRow
		if err := rows.Scan(
			&i.ProductID,
			&i.ProductName,
			&i.CategoryName,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.UnitsBelowThreshold,
			&i.CostPrice,
			&i.ReorderCost,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
