// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type DebtStatus string

const (
	DebtStatusPaid       DebtStatus = "paid"
	DebtStatusPending    DebtStatus = "pending"
	DebtStatusPartial    DebtStatus = "partial"
	DebtStatusWrittenOff DebtStatus = "written-off"
)

func (e *DebtStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DebtStatus(s)
	case string:
		*e = DebtStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for DebtStatus: %T", src)
	}
	return nil
}

type NullDebtStatus struct {
	DebtStatus DebtStatus `json:"debt_status"`
	Valid      bool       `json:"valid"` // Valid is true if DebtStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDebtStatus) Scan(value interface{}) error {
	if value == nil {
		ns.DebtStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DebtStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDebtStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DebtStatus), nil
}

type LoyaltyStatus string

const (
	LoyaltyStatusRegular LoyaltyStatus = "regular"
	LoyaltyStatusLoyal   LoyaltyStatus = "loyal"
	LoyaltyStatusVip     LoyaltyStatus = "vip"
)

func (e *LoyaltyStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LoyaltyStatus(s)
	case string:
		*e = LoyaltyStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LoyaltyStatus: %T", src)
	}
	return nil
}

type NullLoyaltyStatus struct {
	LoyaltyStatus LoyaltyStatus `json:"loyalty_status"`
	Valid         bool          `json:"valid"` // Valid is true if LoyaltyStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLoyaltyStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LoyaltyStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LoyaltyStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLoyaltyStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LoyaltyStatus), nil
}

type NotificationStatus string

const (
	NotificationStatusUnread    NotificationStatus = "unread"
	NotificationStatusRead      NotificationStatus = "read"
	NotificationStatusDismissed NotificationStatus = "dismissed"
)

func (e *NotificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationStatus(s)
	case string:
		*e = NotificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationStatus: %T", src)
	}
	return nil
}

type NullNotificationStatus struct {
	NotificationStatus NotificationStatus `json:"notification_status"`
	Valid              bool               `json:"valid"` // Valid is true if NotificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationStatus), nil
}

type NotificationType string

const (
	NotificationTypeDebtDue         NotificationType = "debt_due"
	NotificationTypeLowStock        NotificationType = "low_stock"
	NotificationTypeExpiringProduct NotificationType = "expiring_product"
	NotificationTypeSystem          NotificationType = "system"
)

func (e *NotificationType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = NotificationType(s)
	case string:
		*e = NotificationType(s)
	default:
		return fmt.Errorf("unsupported scan type for NotificationType: %T", src)
	}
	return nil
}

type NullNotificationType struct {
	NotificationType NotificationType `json:"notification_type"`
	Valid            bool             `json:"valid"` // Valid is true if NotificationType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullNotificationType) Scan(value interface{}) error {
	if value == nil {
		ns.NotificationType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.NotificationType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullNotificationType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.NotificationType), nil
}

type ProductStatus string

const (
	ProductStatusActive       ProductStatus = "active"
	ProductStatusOutOfStock   ProductStatus = "out_of_stock"
	ProductStatusDiscontinued ProductStatus = "discontinued"
	ProductStatusExpiring     ProductStatus = "expiring"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type SalesTypes string

const (
	SalesTypesCash   SalesTypes = "cash"
	SalesTypesCredit SalesTypes = "credit"
	SalesTypesOnline SalesTypes = "online"
	SalesTypesMixed  SalesTypes = "mixed"
)

func (e *SalesTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SalesTypes(s)
	case string:
		*e = SalesTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for SalesTypes: %T", src)
	}
	return nil
}

type NullSalesTypes struct {
	SalesTypes SalesTypes `json:"sales_types"`
	Valid      bool       `json:"valid"` // Valid is true if SalesTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSalesTypes) Scan(value interface{}) error {
	if value == nil {
		ns.SalesTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SalesTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSalesTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SalesTypes), nil
}

type Category struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	StoreID     pgtype.UUID        `db:"store_id" json:"store_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Customer struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	Phone          string             `db:"phone" json:"phone"`
	LoyaltyStatus  LoyaltyStatus      `db:"loyalty_status" json:"loyalty_status"`
	PurchaseCount  int32              `db:"purchase_count" json:"purchase_count"`
	LoyaltyPoints  int32              `db:"loyalty_points" json:"loyalty_points"`
	LastPurchaseAt pgtype.Timestamptz `db:"last_purchase_at" json:"last_purchase_at"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StoreID        pgtype.UUID        `db:"store_id" json:"store_id"`
}

type Debt struct {
	ID         pgtype.UUID        `db:"id" json:"id"`
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleID     pgtype.UUID        `db:"sale_id" json:"sale_id"`
	AmountOwed pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	DueDate    pgtype.Timestamptz `db:"due_date" json:"due_date"`
	Status     DebtStatus         `db:"status" json:"status"`
	Notes      pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Notification struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	Type          NotificationType   `db:"type" json:"type"`
	Title         string             `db:"title" json:"title"`
	Message       string             `db:"message" json:"message"`
	ReferenceID   pgtype.UUID        `db:"reference_id" json:"reference_id"`
	ReferenceType pgtype.Text        `db:"reference_type" json:"reference_type"`
	Status        NotificationStatus `db:"status" json:"status"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type OtpToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserEmail string             `db:"user_email" json:"user_email"`
	Otp       string             `db:"otp" json:"otp"`
	Purpose   string             `db:"purpose" json:"purpose"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type PaymentRecord struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	SaleID      pgtype.UUID        `db:"sale_id" json:"sale_id"`
	Amount      pgtype.Numeric     `db:"amount" json:"amount"`
	PaymentType SalesTypes         `db:"payment_type" json:"payment_type"`
	Provider    pgtype.Text        `db:"provider" json:"provider"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

type Product struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	CostPrice         pgtype.Numeric     `db:"cost_price" json:"cost_price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold pgtype.Int4        `db:"low_stock_threshold" json:"low_stock_threshold"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status            NullProductStatus  `db:"status" json:"status"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
	IsTracked         pgtype.Bool        `db:"is_tracked" json:"is_tracked"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type ProductVariant struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	ProductID    pgtype.UUID        `db:"product_id" json:"product_id"`
	Sku          string             `db:"sku" json:"sku"`
	Barcode      pgtype.Text        `db:"barcode" json:"barcode"`
	Attributes   []byte             `db:"attributes" json:"attributes"`
	CostPrice    pgtype.Numeric     `db:"cost_price" json:"cost_price"`
	SellingPrice pgtype.Numeric     `db:"selling_price" json:"selling_price"`
	StockLevel   int32              `db:"stock_level" json:"stock_level"`
	ImageUrl     pgtype.Text        `db:"image_url" json:"image_url"`
	ArchivedAt   pgtype.Timestamptz `db:"archived_at" json:"archived_at"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Sale struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SalesType       SalesTypes         `db:"sales_type" json:"sales_type"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric     `db:"discount_applied" json:"discount_applied"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
}

type SaleItem struct {
	ID         pgtype.UUID    `db:"id" json:"id"`
	SaleID     pgtype.UUID    `db:"sale_id" json:"sale_id"`
	ProductID  pgtype.UUID    `db:"product_id" json:"product_id"`
	VariantID  pgtype.UUID    `db:"variant_id" json:"variant_id"`
	Quantity   int32          `db:"quantity" json:"quantity"`
	UnitPrice  pgtype.Numeric `db:"unit_price" json:"unit_price"`
	TotalPrice pgtype.Numeric `db:"total_price" json:"total_price"`
}

type StoreInfo struct {
	ID                        pgtype.UUID        `db:"id" json:"id"`
	Name                      string             `db:"name" json:"name"`
	Address                   string             `db:"address" json:"address"`
	CurrencyCode              string             `db:"currency_code" json:"currency_code"`
	OwnerID                   pgtype.UUID        `db:"owner_id" json:"owner_id"`
	LoyaltyProgressTarget     int32              `db:"loyalty_progress_target" json:"loyalty_progress_target"`
	LoyaltyDiscountPercentage pgtype.Numeric     `db:"loyalty_discount_percentage" json:"loyalty_discount_percentage"`
	CreatedAt                 pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt                 pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StoreOwner struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	Email          string             `db:"email" json:"email"`
	Password       string             `db:"password" json:"password"`
	Emailverified  bool               `db:"emailverified" json:"emailverified"`
	Phone          string             `db:"phone" json:"phone"`
	Role           string             `db:"role" json:"role"`
	ProfilePicture string             `db:"profile_picture" json:"profile_picture"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Supplier struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        pgtype.Text        `db:"name" json:"name"`
	Address     pgtype.Text        `db:"address" json:"address"`
	PhoneNumber pgtype.Text        `db:"phone_number" json:"phone_number"`
	Email       pgtype.Text        `db:"email" json:"email"`
	StoreID     pgtype.UUID        `db:"store_id" json:"store_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
