// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ProductStatus string

const (
	ProductStatusActive       ProductStatus = "active"
	ProductStatusOutOfStock   ProductStatus = "out_of_stock"
	ProductStatusDiscontinued ProductStatus = "discontinued"
)

func (e *ProductStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductStatus(s)
	case string:
		*e = ProductStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductStatus: %T", src)
	}
	return nil
}

type NullProductStatus struct {
	ProductStatus ProductStatus `json:"product_status"`
	Valid         bool          `json:"valid"` // Valid is true if ProductStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProductStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductStatus), nil
}

type SalesTypes string

const (
	SalesTypesCash   SalesTypes = "cash"
	SalesTypesCredit SalesTypes = "credit"
	SalesTypesOnline SalesTypes = "online"
)

func (e *SalesTypes) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SalesTypes(s)
	case string:
		*e = SalesTypes(s)
	default:
		return fmt.Errorf("unsupported scan type for SalesTypes: %T", src)
	}
	return nil
}

type NullSalesTypes struct {
	SalesTypes SalesTypes `json:"sales_types"`
	Valid      bool       `json:"valid"` // Valid is true if SalesTypes is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSalesTypes) Scan(value interface{}) error {
	if value == nil {
		ns.SalesTypes, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SalesTypes.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSalesTypes) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SalesTypes), nil
}

type Category struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description pgtype.Text        `db:"description" json:"description"`
	StoreID     pgtype.UUID        `db:"store_id" json:"store_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Customer struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Phone     string             `db:"phone" json:"phone"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	StoreID   pgtype.UUID        `db:"store_id" json:"store_id"`
}

type OtpToken struct {
	ID        pgtype.UUID        `db:"id" json:"id"`
	UserEmail string             `db:"user_email" json:"user_email"`
	Otp       string             `db:"otp" json:"otp"`
	Purpose   string             `db:"purpose" json:"purpose"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ExpiresAt pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
}

type Product struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold pgtype.Int4        `db:"low_stock_threshold" json:"low_stock_threshold"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status            NullProductStatus  `db:"status" json:"status"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Sale struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SalesType       SalesTypes         `db:"sales_type" json:"sales_type"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric     `db:"discount_applied" json:"discount_applied"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
}

type SaleItem struct {
	ID         pgtype.UUID    `db:"id" json:"id"`
	SaleID     pgtype.UUID    `db:"sale_id" json:"sale_id"`
	ProductID  pgtype.UUID    `db:"product_id" json:"product_id"`
	Quantity   int32          `db:"quantity" json:"quantity"`
	UnitPrice  pgtype.Numeric `db:"unit_price" json:"unit_price"`
	TotalPrice pgtype.Numeric `db:"total_price" json:"total_price"`
}

type StoreInfo struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	Name         string             `db:"name" json:"name"`
	Address      string             `db:"address" json:"address"`
	CurrencyCode string             `db:"currency_code" json:"currency_code"`
	OwnerID      pgtype.UUID        `db:"owner_id" json:"owner_id"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type StoreOwner struct {
	ID             pgtype.UUID        `db:"id" json:"id"`
	Name           string             `db:"name" json:"name"`
	Email          string             `db:"email" json:"email"`
	Password       string             `db:"password" json:"password"`
	Emailverified  bool               `db:"emailverified" json:"emailverified"`
	Phone          string             `db:"phone" json:"phone"`
	Role           string             `db:"role" json:"role"`
	ProfilePicture string             `db:"profile_picture" json:"profile_picture"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt      pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

type Supplier struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Name        pgtype.Text        `db:"name" json:"name"`
	Address     pgtype.Text        `db:"address" json:"address"`
	PhoneNumber pgtype.Text        `db:"phone_number" json:"phone_number"`
	Email       pgtype.Text        `db:"email" json:"email"`
	StoreID     pgtype.UUID        `db:"store_id" json:"store_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}
