// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: notifications.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const checkNotificationExists = `-- name: CheckNotificationExists :one
SELECT EXISTS(
    SELECT 1 FROM notifications
    WHERE store_id = $1 
      AND type = $2 
      AND reference_id = $3
      AND status = 'unread'
      AND created_at > NOW() - INTERVAL '24 hours'
)
`

type CheckNotificationExistsParams struct {
	StoreID     pgtype.UUID      `db:"store_id" json:"store_id"`
	Type        NotificationType `db:"type" json:"type"`
	ReferenceID pgtype.UUID      `db:"reference_id" json:"reference_id"`
}

func (q *Queries) CheckNotificationExists(ctx context.Context, arg CheckNotificationExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkNotificationExists, arg.StoreID, arg.Type, arg.ReferenceID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const createNotification = `-- name: CreateNotification :one
INSERT INTO notifications (
    store_id,
    type,
    title,
    message,
    reference_id,
    reference_type,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, store_id, type, title, message, reference_id, reference_type, status, created_at, updated_at
`

type CreateNotificationParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	Type          NotificationType   `db:"type" json:"type"`
	Title         string             `db:"title" json:"title"`
	Message       string             `db:"message" json:"message"`
	ReferenceID   pgtype.UUID        `db:"reference_id" json:"reference_id"`
	ReferenceType pgtype.Text        `db:"reference_type" json:"reference_type"`
	Status        NotificationStatus `db:"status" json:"status"`
}

func (q *Queries) CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, createNotification,
		arg.StoreID,
		arg.Type,
		arg.Title,
		arg.Message,
		arg.ReferenceID,
		arg.ReferenceType,
		arg.Status,
	)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteNotification = `-- name: DeleteNotification :exec
DELETE FROM notifications
WHERE id = $1 AND store_id = $2
`

type DeleteNotificationParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error {
	_, err := q.db.Exec(ctx, deleteNotification, arg.ID, arg.StoreID)
	return err
}

const deleteOldNotifications = `-- name: DeleteOldNotifications :exec
DELETE FROM notifications
WHERE store_id = $1 
  AND status = 'dismissed' 
  AND created_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteOldNotifications(ctx context.Context, storeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOldNotifications, storeID)
	return err
}

const dismissNotification = `-- name: DismissNotification :one
UPDATE notifications
SET status = 'dismissed', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, type, title, message, reference_id, reference_type, status, created_at, updated_at
`

type DismissNotificationParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DismissNotification(ctx context.Context, arg DismissNotificationParams) (Notification, error) {
	row := q.db.QueryRow(ctx, dismissNotification, arg.ID, arg.StoreID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getNotifications = `-- name: GetNotifications :many
SELECT id, store_id, type, title, message, reference_id, reference_type, status, created_at, updated_at FROM notifications
WHERE store_id = $1
ORDER BY 
    CASE WHEN status = 'unread' THEN 0 ELSE 1 END,
    created_at DESC
LIMIT $2 OFFSET $3
`

type GetNotificationsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getNotifications, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUnreadCount = `-- name: GetUnreadCount :one
SELECT COUNT(*) FROM notifications
WHERE store_id = $1 AND status = 'unread'
`

func (q *Queries) GetUnreadCount(ctx context.Context, storeID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getUnreadCount, storeID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getUnreadNotifications = `-- name: GetUnreadNotifications :many
SELECT id, store_id, type, title, message, reference_id, reference_type, status, created_at, updated_at FROM notifications
WHERE store_id = $1 AND status = 'unread'
ORDER BY created_at DESC
`

func (q *Queries) GetUnreadNotifications(ctx context.Context, storeID pgtype.UUID) ([]Notification, error) {
	rows, err := q.db.Query(ctx, getUnreadNotifications, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Notification
	for rows.Next() {
		var i Notification
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.Type,
			&i.Title,
			&i.Message,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markAllNotificationsAsRead = `-- name: MarkAllNotificationsAsRead :exec
UPDATE notifications
SET status = 'read', updated_at = CURRENT_TIMESTAMP
WHERE store_id = $1 AND status = 'unread'
`

func (q *Queries) MarkAllNotificationsAsRead(ctx context.Context, storeID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, markAllNotificationsAsRead, storeID)
	return err
}

const markNotificationAsRead = `-- name: MarkNotificationAsRead :one
UPDATE notifications
SET status = 'read', updated_at = CURRENT_TIMESTAMP
WHERE id = $1 AND store_id = $2
RETURNING id, store_id, type, title, message, reference_id, reference_type, status, created_at, updated_at
`

type MarkNotificationAsReadParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error) {
	row := q.db.QueryRow(ctx, markNotificationAsRead, arg.ID, arg.StoreID)
	var i Notification
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.Type,
		&i.Title,
		&i.Message,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
