// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: otp_token.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOTPToken = `-- name: CreateOTPToken :one
INSERT INTO otp_tokens (user_email, otp, purpose, expires_at)
VALUES ($1, $2, $3, NOW() + INTERVAL '10 minutes')
RETURNING id, user_email, otp, purpose, created_at, expires_at
`

type CreateOTPTokenParams struct {
	UserEmail string `db:"user_email" json:"user_email"`
	Otp       string `db:"otp" json:"otp"`
	Purpose   string `db:"purpose" json:"purpose"`
}

func (q *Queries) CreateOTPToken(ctx context.Context, arg CreateOTPTokenParams) (OtpToken, error) {
	row := q.db.QueryRow(ctx, createOTPToken, arg.UserEmail, arg.Otp, arg.Purpose)
	var i OtpToken
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Otp,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}

const deleteExpiredOTPs = `-- name: DeleteExpiredOTPs :exec
DELETE FROM otp_tokens WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredOTPs(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredOTPs)
	return err
}

const deleteOTPToken = `-- name: DeleteOTPToken :exec
DELETE FROM otp_tokens WHERE id = $1
`

func (q *Queries) DeleteOTPToken(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteOTPToken, id)
	return err
}

const verifyOTP = `-- name: VerifyOTP :one
SELECT id, user_email, otp, purpose, created_at, expires_at FROM otp_tokens 
WHERE user_email = $1 AND otp = $2 AND purpose = $3 AND expires_at > NOW()
`

type VerifyOTPParams struct {
	UserEmail string `db:"user_email" json:"user_email"`
	Otp       string `db:"otp" json:"otp"`
	Purpose   string `db:"purpose" json:"purpose"`
}

func (q *Queries) VerifyOTP(ctx context.Context, arg VerifyOTPParams) (OtpToken, error) {
	row := q.db.QueryRow(ctx, verifyOTP, arg.UserEmail, arg.Otp, arg.Purpose)
	var i OtpToken
	err := row.Scan(
		&i.ID,
		&i.UserEmail,
		&i.Otp,
		&i.Purpose,
		&i.CreatedAt,
		&i.ExpiresAt,
	)
	return i, err
}
