// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: payments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPaymentRecord = `-- name: CreatePaymentRecord :one
INSERT INTO payment_records (
    sale_id,
    amount,
    payment_type,
    provider
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, sale_id, amount, payment_type, provider, created_at
`

type CreatePaymentRecordParams struct {
	SaleID      pgtype.UUID    `db:"sale_id" json:"sale_id"`
	Amount      pgtype.Numeric `db:"amount" json:"amount"`
	PaymentType SalesTypes     `db:"payment_type" json:"payment_type"`
	Provider    pgtype.Text    `db:"provider" json:"provider"`
}

func (q *Queries) CreatePaymentRecord(ctx context.Context, arg CreatePaymentRecordParams) (PaymentRecord, error) {
	row := q.db.QueryRow(ctx, createPaymentRecord,
		arg.SaleID,
		arg.Amount,
		arg.PaymentType,
		arg.Provider,
	)
	var i PaymentRecord
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.Amount,
		&i.PaymentType,
		&i.Provider,
		&i.CreatedAt,
	)
	return i, err
}

const getPaymentTotalsByStore = `-- name: GetPaymentTotalsByStore :many
SELECT payment_type, SUM(amount) as total_amount
FROM payment_records pr
JOIN sales s ON pr.sale_id = s.id
WHERE s.store_id = $1
GROUP BY payment_type
`

type GetPaymentTotalsByStoreRow struct {
	PaymentType SalesTypes `db:"payment_type" json:"payment_type"`
	TotalAmount int64      `db:"total_amount" json:"total_amount"`
}

func (q *Queries) GetPaymentTotalsByStore(ctx context.Context, storeID pgtype.UUID) ([]GetPaymentTotalsByStoreRow, error) {
	rows, err := q.db.Query(ctx, getPaymentTotalsByStore, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPaymentTotalsByStoreRow
	for rows.Next() {
		var i GetPaymentTotalsByStoreRow
		if err := rows.Scan(&i.PaymentType, &i.TotalAmount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentsBySale = `-- name: ListPaymentsBySale :many
SELECT id, sale_id, amount, payment_type, provider, created_at FROM payment_records
WHERE sale_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListPaymentsBySale(ctx context.Context, saleID pgtype.UUID) ([]PaymentRecord, error) {
	rows, err := q.db.Query(ctx, listPaymentsBySale, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaymentRecord
	for rows.Next() {
		var i PaymentRecord
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.Amount,
			&i.PaymentType,
			&i.Provider,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
