// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pos.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getPOSCatalog = `-- name: GetPOSCatalog :many
SELECT 
    p.id,
    p.name,
    p.barcode,
    p.price,
    p.cost_price,
    p.stock_quantity,
    p.category_id,
    p.image_url,
    COALESCE(
        json_agg(
            json_build_object(
                'id', v.id,
                'sku', v.sku,
                'attributes', v.attributes,
                'cost_price', v.cost_price,
                'selling_price', v.selling_price,
                'stock_level', v.stock_level
            )
        ) FILTER (WHERE v.id IS NOT NULL),
        '[]'
    )::json as variants
FROM products p
LEFT JOIN product_variants v ON p.id = v.product_id AND v.archived_at IS NULL
WHERE p.store_id = $1 AND p.status != 'discontinued'
GROUP BY p.id
ORDER BY p.name ASC
`

type GetPOSCatalogRow struct {
	ID            pgtype.UUID    `db:"id" json:"id"`
	Name          string         `db:"name" json:"name"`
	Barcode       pgtype.Text    `db:"barcode" json:"barcode"`
	Price         pgtype.Numeric `db:"price" json:"price"`
	CostPrice     pgtype.Numeric `db:"cost_price" json:"cost_price"`
	StockQuantity int32          `db:"stock_quantity" json:"stock_quantity"`
	CategoryID    pgtype.UUID    `db:"category_id" json:"category_id"`
	ImageUrl      pgtype.Text    `db:"image_url" json:"image_url"`
	Variants      []byte         `db:"variants" json:"variants"`
}

func (q *Queries) GetPOSCatalog(ctx context.Context, storeID pgtype.UUID) ([]GetPOSCatalogRow, error) {
	rows, err := q.db.Query(ctx, getPOSCatalog, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPOSCatalogRow
	for rows.Next() {
		var i GetPOSCatalogRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.CostPrice,
			&i.StockQuantity,
			&i.CategoryID,
			&i.ImageUrl,
			&i.Variants,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
