// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: product_batches.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProductBatch = `-- name: CreateProductBatch :one
INSERT INTO product_batches (
    product_id, batch_number, manufacturing_date,
    expiry_date, quantity, notes
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, product_id, batch_number, manufacturing_date, expiry_date, quantity, notes, created_at, updated_at
`

type CreateProductBatchParams struct {
	ProductID         pgtype.UUID `db:"product_id" json:"product_id"`
	BatchNumber       string      `db:"batch_number" json:"batch_number"`
	ManufacturingDate pgtype.Date `db:"manufacturing_date" json:"manufacturing_date"`
	ExpiryDate        pgtype.Date `db:"expiry_date" json:"expiry_date"`
	Quantity          int32       `db:"quantity" json:"quantity"`
	Notes             pgtype.Text `db:"notes" json:"notes"`
}

func (q *Queries) CreateProductBatch(ctx context.Context, arg CreateProductBatchParams) (ProductBatch, error) {
	row := q.db.QueryRow(ctx, createProductBatch,
		arg.ProductID,
		arg.BatchNumber,
		arg.ManufacturingDate,
		arg.ExpiryDate,
		arg.Quantity,
		arg.Notes,
	)
	var i ProductBatch
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ManufacturingDate,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProductBatch = `-- name: DeleteProductBatch :exec
DELETE FROM product_batches pb
USING products p
WHERE pb.id = $1 AND pb.product_id = p.id AND p.store_id = $2
`

type DeleteProductBatchParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeleteProductBatch(ctx context.Context, arg DeleteProductBatchParams) error {
	_, err := q.db.Exec(ctx, deleteProductBatch, arg.ID, arg.StoreID)
	return err
}

const getBatchesByProductWithStore = `-- name: GetBatchesByProductWithStore :many
SELECT pb.id, pb.product_id, pb.batch_number, pb.manufacturing_date, pb.expiry_date, pb.quantity, pb.notes, pb.created_at, pb.updated_at, p.name as product_name, p.store_id
FROM product_batches pb
JOIN products p ON pb.product_id = p.id
WHERE pb.product_id = $1 AND p.store_id = $2
ORDER BY pb.created_at DESC
`

type GetBatchesByProductWithStoreParams struct {
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
	StoreID   pgtype.UUID `db:"store_id" json:"store_id"`
}

type GetBatchesByProductWithStoreRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber       string             `db:"batch_number" json:"batch_number"`
	ManufacturingDate pgtype.Date        `db:"manufacturing_date" json:"manufacturing_date"`
	ExpiryDate        pgtype.Date        `db:"expiry_date" json:"expiry_date"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	Notes             pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductName       string             `db:"product_name" json:"product_name"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
}

func (q *Queries) GetBatchesByProductWithStore(ctx context.Context, arg GetBatchesByProductWithStoreParams) ([]GetBatchesByProductWithStoreRow, error) {
	rows, err := q.db.Query(ctx, getBatchesByProductWithStore, arg.ProductID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBatchesByProductWithStoreRow
	for rows.Next() {
		var i GetBatchesByProductWithStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ManufacturingDate,
			&i.ExpiryDate,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredBatches = `-- name: GetExpiredBatches :many
SELECT pb.id, pb.product_id, pb.batch_number, pb.manufacturing_date, pb.expiry_date, pb.quantity, pb.notes, pb.created_at, pb.updated_at, p.name as product_name
FROM product_batches pb
JOIN products p ON pb.product_id = p.id
WHERE p.store_id = $1
    AND pb.expiry_date IS NOT NULL
    AND pb.expiry_date <= NOW()
ORDER BY pb.expiry_date ASC
`

type GetExpiredBatchesRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber       string             `db:"batch_number" json:"batch_number"`
	ManufacturingDate pgtype.Date        `db:"manufacturing_date" json:"manufacturing_date"`
	ExpiryDate        pgtype.Date        `db:"expiry_date" json:"expiry_date"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	Notes             pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductName       string             `db:"product_name" json:"product_name"`
}

func (q *Queries) GetExpiredBatches(ctx context.Context, storeID pgtype.UUID) ([]GetExpiredBatchesRow, error) {
	rows, err := q.db.Query(ctx, getExpiredBatches, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredBatchesRow
	for rows.Next() {
		var i GetExpiredBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ManufacturingDate,
			&i.ExpiryDate,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiringBatches = `-- name: GetExpiringBatches :many
SELECT pb.id, pb.product_id, pb.batch_number, pb.manufacturing_date, pb.expiry_date, pb.quantity, pb.notes, pb.created_at, pb.updated_at, p.name as product_name
FROM product_batches pb
JOIN products p ON pb.product_id = p.id
WHERE p.store_id = $1
    AND pb.expiry_date IS NOT NULL
    AND pb.expiry_date <= NOW() + ($2 || ' days')::interval
    AND pb.expiry_date > NOW()
ORDER BY pb.expiry_date ASC
`

type GetExpiringBatchesParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Column2 pgtype.Text `db:"column_2" json:"column_2"`
}

type GetExpiringBatchesRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber       string             `db:"batch_number" json:"batch_number"`
	ManufacturingDate pgtype.Date        `db:"manufacturing_date" json:"manufacturing_date"`
	ExpiryDate        pgtype.Date        `db:"expiry_date" json:"expiry_date"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	Notes             pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductName       string             `db:"product_name" json:"product_name"`
}

func (q *Queries) GetExpiringBatches(ctx context.Context, arg GetExpiringBatchesParams) ([]GetExpiringBatchesRow, error) {
	rows, err := q.db.Query(ctx, getExpiringBatches, arg.StoreID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiringBatchesRow
	for rows.Next() {
		var i GetExpiringBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ManufacturingDate,
			&i.ExpiryDate,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProductBatch = `-- name: GetProductBatch :one
SELECT pb.id, pb.product_id, pb.batch_number, pb.manufacturing_date, pb.expiry_date, pb.quantity, pb.notes, pb.created_at, pb.updated_at, p.name as product_name, p.store_id
FROM product_batches pb
JOIN products p ON pb.product_id = p.id
WHERE pb.id = $1 AND p.store_id = $2
LIMIT 1
`

type GetProductBatchParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

type GetProductBatchRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber       string             `db:"batch_number" json:"batch_number"`
	ManufacturingDate pgtype.Date        `db:"manufacturing_date" json:"manufacturing_date"`
	ExpiryDate        pgtype.Date        `db:"expiry_date" json:"expiry_date"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	Notes             pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductName       string             `db:"product_name" json:"product_name"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
}

func (q *Queries) GetProductBatch(ctx context.Context, arg GetProductBatchParams) (GetProductBatchRow, error) {
	row := q.db.QueryRow(ctx, getProductBatch, arg.ID, arg.StoreID)
	var i GetProductBatchRow
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ManufacturingDate,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ProductName,
		&i.StoreID,
	)
	return i, err
}

const listBatchesByStore = `-- name: ListBatchesByStore :many
SELECT pb.id, pb.product_id, pb.batch_number, pb.manufacturing_date, pb.expiry_date, pb.quantity, pb.notes, pb.created_at, pb.updated_at, p.name as product_name
FROM product_batches pb
JOIN products p ON pb.product_id = p.id
WHERE p.store_id = $1
ORDER BY pb.expiry_date ASC NULLS LAST
LIMIT $2 OFFSET $3
`

type ListBatchesByStoreParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListBatchesByStoreRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber       string             `db:"batch_number" json:"batch_number"`
	ManufacturingDate pgtype.Date        `db:"manufacturing_date" json:"manufacturing_date"`
	ExpiryDate        pgtype.Date        `db:"expiry_date" json:"expiry_date"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	Notes             pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductName       string             `db:"product_name" json:"product_name"`
}

func (q *Queries) ListBatchesByStore(ctx context.Context, arg ListBatchesByStoreParams) ([]ListBatchesByStoreRow, error) {
	rows, err := q.db.Query(ctx, listBatchesByStore, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBatchesByStoreRow
	for rows.Next() {
		var i ListBatchesByStoreRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ManufacturingDate,
			&i.ExpiryDate,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductBatches = `-- name: ListProductBatches :many
SELECT pb.id, pb.product_id, pb.batch_number, pb.manufacturing_date, pb.expiry_date, pb.quantity, pb.notes, pb.created_at, pb.updated_at, p.name as product_name
FROM product_batches pb
JOIN products p ON pb.product_id = p.id
WHERE pb.product_id = $1
ORDER BY pb.created_at DESC
`

type ListProductBatchesRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	BatchNumber       string             `db:"batch_number" json:"batch_number"`
	ManufacturingDate pgtype.Date        `db:"manufacturing_date" json:"manufacturing_date"`
	ExpiryDate        pgtype.Date        `db:"expiry_date" json:"expiry_date"`
	Quantity          int32              `db:"quantity" json:"quantity"`
	Notes             pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductName       string             `db:"product_name" json:"product_name"`
}

func (q *Queries) ListProductBatches(ctx context.Context, productID pgtype.UUID) ([]ListProductBatchesRow, error) {
	rows, err := q.db.Query(ctx, listProductBatches, productID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductBatchesRow
	for rows.Next() {
		var i ListProductBatchesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.BatchNumber,
			&i.ManufacturingDate,
			&i.ExpiryDate,
			&i.Quantity,
			&i.Notes,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBatchQuantity = `-- name: UpdateBatchQuantity :one
UPDATE product_batches
SET
    quantity = quantity + $2,
    updated_at = NOW()
WHERE id = $1
    AND quantity + $2 >= 0
RETURNING id, product_id, batch_number, manufacturing_date, expiry_date, quantity, notes, created_at, updated_at
`

type UpdateBatchQuantityParams struct {
	ID       pgtype.UUID `db:"id" json:"id"`
	Quantity int32       `db:"quantity" json:"quantity"`
}

func (q *Queries) UpdateBatchQuantity(ctx context.Context, arg UpdateBatchQuantityParams) (ProductBatch, error) {
	row := q.db.QueryRow(ctx, updateBatchQuantity, arg.ID, arg.Quantity)
	var i ProductBatch
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ManufacturingDate,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductBatch = `-- name: UpdateProductBatch :one
UPDATE product_batches pb
SET
    batch_number = COALESCE($2, batch_number),
    manufacturing_date = COALESCE($3, manufacturing_date),
    expiry_date = COALESCE($4, expiry_date),
    quantity = COALESCE($5, quantity),
    notes = COALESCE($6, notes),
    updated_at = NOW()
FROM products p
WHERE pb.id = $1 AND pb.product_id = p.id AND p.store_id = $7
RETURNING pb.id, pb.product_id, pb.batch_number, pb.manufacturing_date, pb.expiry_date, pb.quantity, pb.notes, pb.created_at, pb.updated_at
`

type UpdateProductBatchParams struct {
	ID                pgtype.UUID `db:"id" json:"id"`
	BatchNumber       string      `db:"batch_number" json:"batch_number"`
	ManufacturingDate pgtype.Date `db:"manufacturing_date" json:"manufacturing_date"`
	ExpiryDate        pgtype.Date `db:"expiry_date" json:"expiry_date"`
	Quantity          int32       `db:"quantity" json:"quantity"`
	Notes             pgtype.Text `db:"notes" json:"notes"`
	StoreID           pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateProductBatch(ctx context.Context, arg UpdateProductBatchParams) (ProductBatch, error) {
	row := q.db.QueryRow(ctx, updateProductBatch,
		arg.ID,
		arg.BatchNumber,
		arg.ManufacturingDate,
		arg.ExpiryDate,
		arg.Quantity,
		arg.Notes,
		arg.StoreID,
	)
	var i ProductBatch
	err := row.Scan(
		&i.ID,
		&i.ProductID,
		&i.BatchNumber,
		&i.ManufacturingDate,
		&i.ExpiryDate,
		&i.Quantity,
		&i.Notes,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
