// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    barcode,
    price,
    cost_price,
    market_price,
    stock_quantity,
    low_stock_threshold,
    expires_at,
    status,
    category_id,
    supplier_id,
    store_id,
    image_url,
    is_tracked
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14
) RETURNING id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at
`

type CreateProductParams struct {
	Name              string             `db:"name" json:"name"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	CostPrice         pgtype.Numeric     `db:"cost_price" json:"cost_price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold pgtype.Int4        `db:"low_stock_threshold" json:"low_stock_threshold"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status            NullProductStatus  `db:"status" json:"status"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
	IsTracked         pgtype.Bool        `db:"is_tracked" json:"is_tracked"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Barcode,
		arg.Price,
		arg.CostPrice,
		arg.MarketPrice,
		arg.StockQuantity,
		arg.LowStockThreshold,
		arg.ExpiresAt,
		arg.Status,
		arg.CategoryID,
		arg.SupplierID,
		arg.StoreID,
		arg.ImageUrl,
		arg.IsTracked,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.Price,
		&i.CostPrice,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.ExpiresAt,
		&i.Status,
		&i.CategoryID,
		&i.SupplierID,
		&i.StoreID,
		&i.ImageUrl,
		&i.IsTracked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
UPDATE products
SET status = 'discontinued'
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const flagExpiringProducts = `-- name: FlagExpiringProducts :exec
UPDATE products
SET status = 'expiring'
WHERE status != 'discontinued'
  AND status != 'expiring'
  AND expires_at IS NOT NULL
  AND expires_at <= NOW() + INTERVAL '7 days'
  AND expires_at > NOW()
`

func (q *Queries) FlagExpiringProducts(ctx context.Context) error {
	_, err := q.db.Exec(ctx, flagExpiringProducts)
	return err
}

const getCategoryStats = `-- name: GetCategoryStats :one
SELECT 
    COUNT(*) as product_count,
    COALESCE(SUM(stock_quantity), 0)::int as total_stock,
    COALESCE(SUM(price * stock_quantity), 0)::numeric as total_value
FROM products
WHERE store_id = $1 AND category_id = $2 AND status != 'discontinued'
`

type GetCategoryStatsParams struct {
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
}

type GetCategoryStatsRow struct {
	ProductCount int64          `db:"product_count" json:"product_count"`
	TotalStock   int32          `db:"total_stock" json:"total_stock"`
	TotalValue   pgtype.Numeric `db:"total_value" json:"total_value"`
}

func (q *Queries) GetCategoryStats(ctx context.Context, arg GetCategoryStatsParams) (GetCategoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getCategoryStats, arg.StoreID, arg.CategoryID)
	var i GetCategoryStatsRow
	err := row.Scan(&i.ProductCount, &i.TotalStock, &i.TotalValue)
	return i, err
}

const getLowStockProducts = `-- name: GetLowStockProducts :many
SELECT id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at FROM products
WHERE store_id = $1
  AND status != 'discontinued'
  AND stock_quantity <= low_stock_threshold
ORDER BY stock_quantity ASC
`

func (q *Queries) GetLowStockProducts(ctx context.Context, storeID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getLowStockProducts, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.CostPrice,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.ExpiresAt,
			&i.Status,
			&i.CategoryID,
			&i.SupplierID,
			&i.StoreID,
			&i.ImageUrl,
			&i.IsTracked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.Price,
		&i.CostPrice,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.ExpiresAt,
		&i.Status,
		&i.CategoryID,
		&i.SupplierID,
		&i.StoreID,
		&i.ImageUrl,
		&i.IsTracked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSupplierStats = `-- name: GetSupplierStats :one
SELECT 
    COUNT(*) as product_count,
    COALESCE(SUM(stock_quantity), 0)::int as total_stock,
    COALESCE(SUM(price * stock_quantity), 0)::numeric as total_value,
    COUNT(*) FILTER (WHERE stock_quantity <= low_stock_threshold) as low_stock_count
FROM products
WHERE store_id = $1 AND supplier_id = $2 AND status != 'discontinued'
`

type GetSupplierStatsParams struct {
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
}

type GetSupplierStatsRow struct {
	ProductCount  int64          `db:"product_count" json:"product_count"`
	TotalStock    int32          `db:"total_stock" json:"total_stock"`
	TotalValue    pgtype.Numeric `db:"total_value" json:"total_value"`
	LowStockCount int64          `db:"low_stock_count" json:"low_stock_count"`
}

func (q *Queries) GetSupplierStats(ctx context.Context, arg GetSupplierStatsParams) (GetSupplierStatsRow, error) {
	row := q.db.QueryRow(ctx, getSupplierStats, arg.StoreID, arg.SupplierID)
	var i GetSupplierStatsRow
	err := row.Scan(
		&i.ProductCount,
		&i.TotalStock,
		&i.TotalValue,
		&i.LowStockCount,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at FROM products
WHERE store_id = $1 AND status != 'discontinued'
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.CostPrice,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.ExpiresAt,
			&i.Status,
			&i.CategoryID,
			&i.SupplierID,
			&i.StoreID,
			&i.ImageUrl,
			&i.IsTracked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at FROM products
WHERE store_id = $1 AND category_id = $2 AND status != 'discontinued'
ORDER BY created_at DESC
`

type ListProductsByCategoryParams struct {
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
	CategoryID pgtype.UUID `db:"category_id" json:"category_id"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, arg.StoreID, arg.CategoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.CostPrice,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.ExpiresAt,
			&i.Status,
			&i.CategoryID,
			&i.SupplierID,
			&i.StoreID,
			&i.ImageUrl,
			&i.IsTracked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsBySupplier = `-- name: ListProductsBySupplier :many
SELECT id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at FROM products
WHERE store_id = $1 AND supplier_id = $2 AND status != 'discontinued'
ORDER BY created_at DESC
`

type ListProductsBySupplierParams struct {
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
}

func (q *Queries) ListProductsBySupplier(ctx context.Context, arg ListProductsBySupplierParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProductsBySupplier, arg.StoreID, arg.SupplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.CostPrice,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.ExpiresAt,
			&i.Status,
			&i.CategoryID,
			&i.SupplierID,
			&i.StoreID,
			&i.ImageUrl,
			&i.IsTracked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTrackedProducts = `-- name: ListTrackedProducts :many
SELECT id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at FROM products
WHERE store_id = $1 AND is_tracked = TRUE AND status != 'discontinued'
ORDER BY updated_at DESC
LIMIT 6
`

func (q *Queries) ListTrackedProducts(ctx context.Context, storeID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, listTrackedProducts, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.CostPrice,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.ExpiresAt,
			&i.Status,
			&i.CategoryID,
			&i.SupplierID,
			&i.StoreID,
			&i.ImageUrl,
			&i.IsTracked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at FROM products
WHERE 
    store_id = $1 AND 
    status != 'discontinued' AND (
    name ILIKE '%' || $2 || '%' OR
    barcode ILIKE '%' || $2 || '%'
    )
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchProductsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Column2 pgtype.Text `db:"column_2" json:"column_2"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.StoreID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.CostPrice,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.ExpiresAt,
			&i.Status,
			&i.CategoryID,
			&i.SupplierID,
			&i.StoreID,
			&i.ImageUrl,
			&i.IsTracked,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    name = COALESCE($2, name),
    barcode = COALESCE($3, barcode),
    price = COALESCE($4, price),
    cost_price = COALESCE($5, cost_price),
    market_price = COALESCE($6, market_price),
    stock_quantity = COALESCE($7, stock_quantity),
    low_stock_threshold = COALESCE($8, low_stock_threshold),
    expires_at = COALESCE($9, expires_at),
    status = COALESCE($10, status),
    category_id = COALESCE($11, category_id),
    supplier_id = COALESCE($12, supplier_id),
    image_url = COALESCE($13, image_url),
    is_tracked = COALESCE($14, is_tracked),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at
`

type UpdateProductParams struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	CostPrice         pgtype.Numeric     `db:"cost_price" json:"cost_price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold pgtype.Int4        `db:"low_stock_threshold" json:"low_stock_threshold"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status            NullProductStatus  `db:"status" json:"status"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
	IsTracked         pgtype.Bool        `db:"is_tracked" json:"is_tracked"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Barcode,
		arg.Price,
		arg.CostPrice,
		arg.MarketPrice,
		arg.StockQuantity,
		arg.LowStockThreshold,
		arg.ExpiresAt,
		arg.Status,
		arg.CategoryID,
		arg.SupplierID,
		arg.ImageUrl,
		arg.IsTracked,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.Price,
		&i.CostPrice,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.ExpiresAt,
		&i.Status,
		&i.CategoryID,
		&i.SupplierID,
		&i.StoreID,
		&i.ImageUrl,
		&i.IsTracked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET 
    stock_quantity = stock_quantity - $2,
    updated_at = NOW()
WHERE id = $1 AND store_id = $3
RETURNING id, name, barcode, price, cost_price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, is_tracked, created_at, updated_at
`

type UpdateProductStockParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	StockQuantity int32       `db:"stock_quantity" json:"stock_quantity"`
	StoreID       pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.StockQuantity, arg.StoreID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.Price,
		&i.CostPrice,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.ExpiresAt,
		&i.Status,
		&i.CategoryID,
		&i.SupplierID,
		&i.StoreID,
		&i.ImageUrl,
		&i.IsTracked,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
