// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: product.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    code,
    slug,
    category_id,
    supplier_id,
    price,
    market_price,
    stock_quantity,
    low_stock_threshold,
    is_perishable,
    unit_of_measure,
    status
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, name, code, category_id, supplier_id, price, market_price, stock_quantity, low_stock_threshold, is_perishable, unit_of_measure, status, is_active, created_at, updated_at, slug, store_id
`

type CreateProductParams struct {
	Name              string         `db:"name" json:"name"`
	Code              string         `db:"code" json:"code"`
	Slug              string         `db:"slug" json:"slug"`
	CategoryID        pgtype.UUID    `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID    `db:"supplier_id" json:"supplier_id"`
	Price             pgtype.Numeric `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric `db:"market_price" json:"market_price"`
	StockQuantity     int32          `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold int32          `db:"low_stock_threshold" json:"low_stock_threshold"`
	IsPerishable      bool           `db:"is_perishable" json:"is_perishable"`
	UnitOfMeasure     string         `db:"unit_of_measure" json:"unit_of_measure"`
	Status            ProductStatus  `db:"status" json:"status"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Code,
		arg.Slug,
		arg.CategoryID,
		arg.SupplierID,
		arg.Price,
		arg.MarketPrice,
		arg.StockQuantity,
		arg.LowStockThreshold,
		arg.IsPerishable,
		arg.UnitOfMeasure,
		arg.Status,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.SupplierID,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.IsPerishable,
		&i.UnitOfMeasure,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :one
UPDATE products
SET is_active = false, updated_at = NOW()
WHERE id = $1
RETURNING id, name, code, category_id, supplier_id, price, market_price, stock_quantity, low_stock_threshold, is_perishable, unit_of_measure, status, is_active, created_at, updated_at, slug, store_id
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, deleteProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.SupplierID,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.IsPerishable,
		&i.UnitOfMeasure,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}

const getProductByCode = `-- name: GetProductByCode :one
SELECT id, name, code, category_id, supplier_id, price, market_price, stock_quantity, low_stock_threshold, is_perishable, unit_of_measure, status, is_active, created_at, updated_at, slug, store_id FROM products WHERE code = $1
`

func (q *Queries) GetProductByCode(ctx context.Context, code string) (Product, error) {
	row := q.db.QueryRow(ctx, getProductByCode, code)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.SupplierID,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.IsPerishable,
		&i.UnitOfMeasure,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}

const getProductById = `-- name: GetProductById :one
SELECT p.id, p.name, p.code, p.category_id, p.supplier_id, p.price, p.market_price, p.stock_quantity, p.low_stock_threshold, p.is_perishable, p.unit_of_measure, p.status, p.is_active, p.created_at, p.updated_at, p.slug, p.store_id, 
       c.name as category_name,
       s.name as supplier_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
LEFT JOIN suppliers s ON p.supplier_id = s.id
WHERE p.id = $1
`

type GetProductByIdRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Code              string             `db:"code" json:"code"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	IsPerishable      bool               `db:"is_perishable" json:"is_perishable"`
	UnitOfMeasure     string             `db:"unit_of_measure" json:"unit_of_measure"`
	Status            ProductStatus      `db:"status" json:"status"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Slug              string             `db:"slug" json:"slug"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	CategoryName      pgtype.Text        `db:"category_name" json:"category_name"`
	SupplierName      pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) GetProductById(ctx context.Context, id pgtype.UUID) (GetProductByIdRow, error) {
	row := q.db.QueryRow(ctx, getProductById, id)
	var i GetProductByIdRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.SupplierID,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.IsPerishable,
		&i.UnitOfMeasure,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
		&i.CategoryName,
		&i.SupplierName,
	)
	return i, err
}

const getProductBySlug = `-- name: GetProductBySlug :one
SELECT p.id, p.name, p.code, p.category_id, p.supplier_id, p.price, p.market_price, p.stock_quantity, p.low_stock_threshold, p.is_perishable, p.unit_of_measure, p.status, p.is_active, p.created_at, p.updated_at, p.slug, p.store_id, 
       c.name as category_name,
       s.name as supplier_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
LEFT JOIN suppliers s ON p.supplier_id = s.id
WHERE p.slug = $1
`

type GetProductBySlugRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Code              string             `db:"code" json:"code"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	IsPerishable      bool               `db:"is_perishable" json:"is_perishable"`
	UnitOfMeasure     string             `db:"unit_of_measure" json:"unit_of_measure"`
	Status            ProductStatus      `db:"status" json:"status"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Slug              string             `db:"slug" json:"slug"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	CategoryName      pgtype.Text        `db:"category_name" json:"category_name"`
	SupplierName      pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) GetProductBySlug(ctx context.Context, slug string) (GetProductBySlugRow, error) {
	row := q.db.QueryRow(ctx, getProductBySlug, slug)
	var i GetProductBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.SupplierID,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.IsPerishable,
		&i.UnitOfMeasure,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
		&i.CategoryName,
		&i.SupplierName,
	)
	return i, err
}

const hardDeleteProduct = `-- name: HardDeleteProduct :exec
DELETE FROM products WHERE id = $1
`

func (q *Queries) HardDeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteProduct, id)
	return err
}

const listLowStockProducts = `-- name: ListLowStockProducts :many
SELECT p.id, p.name, p.code, p.category_id, p.supplier_id, p.price, p.market_price, p.stock_quantity, p.low_stock_threshold, p.is_perishable, p.unit_of_measure, p.status, p.is_active, p.created_at, p.updated_at, p.slug, p.store_id, 
       c.name as category_name,
       s.name as supplier_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
LEFT JOIN suppliers s ON p.supplier_id = s.id
WHERE p.stock_quantity <= p.low_stock_threshold 
  AND p.is_active = true
ORDER BY p.stock_quantity ASC
`

type ListLowStockProductsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Code              string             `db:"code" json:"code"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	IsPerishable      bool               `db:"is_perishable" json:"is_perishable"`
	UnitOfMeasure     string             `db:"unit_of_measure" json:"unit_of_measure"`
	Status            ProductStatus      `db:"status" json:"status"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Slug              string             `db:"slug" json:"slug"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	CategoryName      pgtype.Text        `db:"category_name" json:"category_name"`
	SupplierName      pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) ListLowStockProducts(ctx context.Context) ([]ListLowStockProductsRow, error) {
	rows, err := q.db.Query(ctx, listLowStockProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLowStockProductsRow
	for rows.Next() {
		var i ListLowStockProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CategoryID,
			&i.SupplierID,
			&i.Price,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.IsPerishable,
			&i.UnitOfMeasure,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.StoreID,
			&i.CategoryName,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProducts = `-- name: ListProducts :many
SELECT p.id, p.name, p.code, p.category_id, p.supplier_id, p.price, p.market_price, p.stock_quantity, p.low_stock_threshold, p.is_perishable, p.unit_of_measure, p.status, p.is_active, p.created_at, p.updated_at, p.slug, p.store_id, 
       c.name as category_name,
       s.name as supplier_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
LEFT JOIN suppliers s ON p.supplier_id = s.id
WHERE p.is_active = true
ORDER BY p.created_at DESC
LIMIT $1 OFFSET $2
`

type ListProductsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type ListProductsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Code              string             `db:"code" json:"code"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	IsPerishable      bool               `db:"is_perishable" json:"is_perishable"`
	UnitOfMeasure     string             `db:"unit_of_measure" json:"unit_of_measure"`
	Status            ProductStatus      `db:"status" json:"status"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Slug              string             `db:"slug" json:"slug"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	CategoryName      pgtype.Text        `db:"category_name" json:"category_name"`
	SupplierName      pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]ListProductsRow, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsRow
	for rows.Next() {
		var i ListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CategoryID,
			&i.SupplierID,
			&i.Price,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.IsPerishable,
			&i.UnitOfMeasure,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.StoreID,
			&i.CategoryName,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsByCategory = `-- name: ListProductsByCategory :many
SELECT p.id, p.name, p.code, p.category_id, p.supplier_id, p.price, p.market_price, p.stock_quantity, p.low_stock_threshold, p.is_perishable, p.unit_of_measure, p.status, p.is_active, p.created_at, p.updated_at, p.slug, p.store_id, 
       c.name as category_name,
       s.name as supplier_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
LEFT JOIN suppliers s ON p.supplier_id = s.id
WHERE p.category_id = $1 AND p.is_active = true
ORDER BY p.name
`

type ListProductsByCategoryRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Code              string             `db:"code" json:"code"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	IsPerishable      bool               `db:"is_perishable" json:"is_perishable"`
	UnitOfMeasure     string             `db:"unit_of_measure" json:"unit_of_measure"`
	Status            ProductStatus      `db:"status" json:"status"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Slug              string             `db:"slug" json:"slug"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	CategoryName      pgtype.Text        `db:"category_name" json:"category_name"`
	SupplierName      pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) ListProductsByCategory(ctx context.Context, categoryID pgtype.UUID) ([]ListProductsByCategoryRow, error) {
	rows, err := q.db.Query(ctx, listProductsByCategory, categoryID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProductsByCategoryRow
	for rows.Next() {
		var i ListProductsByCategoryRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CategoryID,
			&i.SupplierID,
			&i.Price,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.IsPerishable,
			&i.UnitOfMeasure,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.StoreID,
			&i.CategoryName,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT p.id, p.name, p.code, p.category_id, p.supplier_id, p.price, p.market_price, p.stock_quantity, p.low_stock_threshold, p.is_perishable, p.unit_of_measure, p.status, p.is_active, p.created_at, p.updated_at, p.slug, p.store_id, 
       c.name as category_name,
       s.name as supplier_name
FROM products p
LEFT JOIN categories c ON p.category_id = c.id
LEFT JOIN suppliers s ON p.supplier_id = s.id
WHERE (LOWER(p.name) LIKE LOWER($1) OR LOWER(p.code) LIKE LOWER($1))
  AND p.is_active = true
ORDER BY p.name
LIMIT $2 OFFSET $3
`

type SearchProductsParams struct {
	Lower  string `db:"lower" json:"lower"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type SearchProductsRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Code              string             `db:"code" json:"code"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold int32              `db:"low_stock_threshold" json:"low_stock_threshold"`
	IsPerishable      bool               `db:"is_perishable" json:"is_perishable"`
	UnitOfMeasure     string             `db:"unit_of_measure" json:"unit_of_measure"`
	Status            ProductStatus      `db:"status" json:"status"`
	IsActive          bool               `db:"is_active" json:"is_active"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	Slug              string             `db:"slug" json:"slug"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	CategoryName      pgtype.Text        `db:"category_name" json:"category_name"`
	SupplierName      pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]SearchProductsRow, error) {
	rows, err := q.db.Query(ctx, searchProducts, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchProductsRow
	for rows.Next() {
		var i SearchProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CategoryID,
			&i.SupplierID,
			&i.Price,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.IsPerishable,
			&i.UnitOfMeasure,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.StoreID,
			&i.CategoryName,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET
    name = COALESCE($1, name),
    code = COALESCE($2, code),
    slug = COALESCE($3, slug),
    category_id = COALESCE($4, category_id),
    supplier_id = COALESCE($5, supplier_id),
    price = COALESCE($6, price),
    market_price = COALESCE($7, market_price),
    stock_quantity = COALESCE($8, stock_quantity),
    low_stock_threshold = COALESCE($9, low_stock_threshold),
    is_perishable = COALESCE($10, is_perishable),
    unit_of_measure = COALESCE($11, unit_of_measure),
    status = COALESCE($12, status),
    is_active = COALESCE($13, is_active),
    updated_at = NOW()
WHERE id = $14
RETURNING id, name, code, category_id, supplier_id, price, market_price, stock_quantity, low_stock_threshold, is_perishable, unit_of_measure, status, is_active, created_at, updated_at, slug, store_id
`

type UpdateProductParams struct {
	Name              pgtype.Text       `db:"name" json:"name"`
	Code              pgtype.Text       `db:"code" json:"code"`
	Slug              pgtype.Text       `db:"slug" json:"slug"`
	CategoryID        pgtype.UUID       `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID       `db:"supplier_id" json:"supplier_id"`
	Price             pgtype.Numeric    `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric    `db:"market_price" json:"market_price"`
	StockQuantity     pgtype.Int4       `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold pgtype.Int4       `db:"low_stock_threshold" json:"low_stock_threshold"`
	IsPerishable      pgtype.Bool       `db:"is_perishable" json:"is_perishable"`
	UnitOfMeasure     pgtype.Text       `db:"unit_of_measure" json:"unit_of_measure"`
	Status            NullProductStatus `db:"status" json:"status"`
	IsActive          pgtype.Bool       `db:"is_active" json:"is_active"`
	ID                pgtype.UUID       `db:"id" json:"id"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.Name,
		arg.Code,
		arg.Slug,
		arg.CategoryID,
		arg.SupplierID,
		arg.Price,
		arg.MarketPrice,
		arg.StockQuantity,
		arg.LowStockThreshold,
		arg.IsPerishable,
		arg.UnitOfMeasure,
		arg.Status,
		arg.IsActive,
		arg.ID,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.SupplierID,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.IsPerishable,
		&i.UnitOfMeasure,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET
    stock_quantity = $2,
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, code, category_id, supplier_id, price, market_price, stock_quantity, low_stock_threshold, is_perishable, unit_of_measure, status, is_active, created_at, updated_at, slug, store_id
`

type UpdateProductStockParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	StockQuantity int32       `db:"stock_quantity" json:"stock_quantity"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.StockQuantity)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Code,
		&i.CategoryID,
		&i.SupplierID,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.IsPerishable,
		&i.UnitOfMeasure,
		&i.Status,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}
