// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: products.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProduct = `-- name: CreateProduct :one
INSERT INTO products (
    name,
    barcode,
    price,
    market_price,
    stock_quantity,
    low_stock_threshold,
    expires_at,
    status,
    category_id,
    supplier_id,
    store_id,
    image_url
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12
) RETURNING id, name, barcode, price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, created_at, updated_at
`

type CreateProductParams struct {
	Name              string             `db:"name" json:"name"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold pgtype.Int4        `db:"low_stock_threshold" json:"low_stock_threshold"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status            NullProductStatus  `db:"status" json:"status"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	StoreID           pgtype.UUID        `db:"store_id" json:"store_id"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
}

func (q *Queries) CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, createProduct,
		arg.Name,
		arg.Barcode,
		arg.Price,
		arg.MarketPrice,
		arg.StockQuantity,
		arg.LowStockThreshold,
		arg.ExpiresAt,
		arg.Status,
		arg.CategoryID,
		arg.SupplierID,
		arg.StoreID,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.ExpiresAt,
		&i.Status,
		&i.CategoryID,
		&i.SupplierID,
		&i.StoreID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteProduct = `-- name: DeleteProduct :exec
DELETE FROM products
WHERE id = $1
`

func (q *Queries) DeleteProduct(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProduct, id)
	return err
}

const getProduct = `-- name: GetProduct :one
SELECT id, name, barcode, price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, created_at, updated_at FROM products
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetProduct(ctx context.Context, id pgtype.UUID) (Product, error) {
	row := q.db.QueryRow(ctx, getProduct, id)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.ExpiresAt,
		&i.Status,
		&i.CategoryID,
		&i.SupplierID,
		&i.StoreID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listProducts = `-- name: ListProducts :many
SELECT id, name, barcode, price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, created_at, updated_at FROM products
WHERE store_id = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListProductsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, listProducts, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.ExpiresAt,
			&i.Status,
			&i.CategoryID,
			&i.SupplierID,
			&i.StoreID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchProducts = `-- name: SearchProducts :many
SELECT id, name, barcode, price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, created_at, updated_at FROM products
WHERE 
    store_id = $1 AND (
    name ILIKE '%' || $2 || '%' OR
    barcode ILIKE '%' || $2 || '%'
    )
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type SearchProductsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Column2 pgtype.Text `db:"column_2" json:"column_2"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

func (q *Queries) SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error) {
	rows, err := q.db.Query(ctx, searchProducts,
		arg.StoreID,
		arg.Column2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Barcode,
			&i.Price,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.ExpiresAt,
			&i.Status,
			&i.CategoryID,
			&i.SupplierID,
			&i.StoreID,
			&i.ImageUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProduct = `-- name: UpdateProduct :one
UPDATE products
SET 
    name = COALESCE($2, name),
    barcode = COALESCE($3, barcode),
    price = COALESCE($4, price),
    market_price = COALESCE($5, market_price),
    stock_quantity = COALESCE($6, stock_quantity),
    low_stock_threshold = COALESCE($7, low_stock_threshold),
    expires_at = COALESCE($8, expires_at),
    status = COALESCE($9, status),
    category_id = COALESCE($10, category_id),
    supplier_id = COALESCE($11, supplier_id),
    image_url = COALESCE($12, image_url),
    updated_at = NOW()
WHERE id = $1
RETURNING id, name, barcode, price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, created_at, updated_at
`

type UpdateProductParams struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	Name              string             `db:"name" json:"name"`
	Barcode           pgtype.Text        `db:"barcode" json:"barcode"`
	Price             pgtype.Numeric     `db:"price" json:"price"`
	MarketPrice       pgtype.Numeric     `db:"market_price" json:"market_price"`
	StockQuantity     int32              `db:"stock_quantity" json:"stock_quantity"`
	LowStockThreshold pgtype.Int4        `db:"low_stock_threshold" json:"low_stock_threshold"`
	ExpiresAt         pgtype.Timestamptz `db:"expires_at" json:"expires_at"`
	Status            NullProductStatus  `db:"status" json:"status"`
	CategoryID        pgtype.UUID        `db:"category_id" json:"category_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	ImageUrl          pgtype.Text        `db:"image_url" json:"image_url"`
}

func (q *Queries) UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProduct,
		arg.ID,
		arg.Name,
		arg.Barcode,
		arg.Price,
		arg.MarketPrice,
		arg.StockQuantity,
		arg.LowStockThreshold,
		arg.ExpiresAt,
		arg.Status,
		arg.CategoryID,
		arg.SupplierID,
		arg.ImageUrl,
	)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.ExpiresAt,
		&i.Status,
		&i.CategoryID,
		&i.SupplierID,
		&i.StoreID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateProductStock = `-- name: UpdateProductStock :one
UPDATE products
SET 
    stock_quantity = stock_quantity - $2,
    updated_at = NOW()
WHERE id = $1 AND store_id = $3
RETURNING id, name, barcode, price, market_price, stock_quantity, low_stock_threshold, expires_at, status, category_id, supplier_id, store_id, image_url, created_at, updated_at
`

type UpdateProductStockParams struct {
	ID            pgtype.UUID `db:"id" json:"id"`
	StockQuantity int32       `db:"stock_quantity" json:"stock_quantity"`
	StoreID       pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error) {
	row := q.db.QueryRow(ctx, updateProductStock, arg.ID, arg.StockQuantity, arg.StoreID)
	var i Product
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Barcode,
		&i.Price,
		&i.MarketPrice,
		&i.StockQuantity,
		&i.LowStockThreshold,
		&i.ExpiresAt,
		&i.Status,
		&i.CategoryID,
		&i.SupplierID,
		&i.StoreID,
		&i.ImageUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
