// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: purchase_orders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createPurchaseOrder = `-- name: CreatePurchaseOrder :one
INSERT INTO purchase_orders (store_id, order_date, expected_delivery_date, status, notes, total_cost)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, store_id, order_date, expected_delivery_date, status, notes, total_cost, created_at, updated_at
`

type CreatePurchaseOrderParams struct {
	StoreID              pgtype.UUID        `db:"store_id" json:"store_id"`
	OrderDate            pgtype.Timestamptz `db:"order_date" json:"order_date"`
	ExpectedDeliveryDate pgtype.Timestamptz `db:"expected_delivery_date" json:"expected_delivery_date"`
	Status               string             `db:"status" json:"status"`
	Notes                pgtype.Text        `db:"notes" json:"notes"`
	TotalCost            pgtype.Numeric     `db:"total_cost" json:"total_cost"`
}

func (q *Queries) CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrder,
		arg.StoreID,
		arg.OrderDate,
		arg.ExpectedDeliveryDate,
		arg.Status,
		arg.Notes,
		arg.TotalCost,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.Status,
		&i.Notes,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const createPurchaseOrderItem = `-- name: CreatePurchaseOrderItem :one
INSERT INTO purchase_order_items (purchase_order_id, supplier_id, product_id, product_name, ordered_quantity, unit_cost)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, purchase_order_id, supplier_id, product_id, product_name, ordered_quantity, received_quantity, damaged_quantity, unit_cost, created_at, updated_at
`

type CreatePurchaseOrderItemParams struct {
	PurchaseOrderID pgtype.UUID    `db:"purchase_order_id" json:"purchase_order_id"`
	SupplierID      pgtype.UUID    `db:"supplier_id" json:"supplier_id"`
	ProductID       pgtype.UUID    `db:"product_id" json:"product_id"`
	ProductName     string         `db:"product_name" json:"product_name"`
	OrderedQuantity int32          `db:"ordered_quantity" json:"ordered_quantity"`
	UnitCost        pgtype.Numeric `db:"unit_cost" json:"unit_cost"`
}

func (q *Queries) CreatePurchaseOrderItem(ctx context.Context, arg CreatePurchaseOrderItemParams) (PurchaseOrderItem, error) {
	row := q.db.QueryRow(ctx, createPurchaseOrderItem,
		arg.PurchaseOrderID,
		arg.SupplierID,
		arg.ProductID,
		arg.ProductName,
		arg.OrderedQuantity,
		arg.UnitCost,
	)
	var i PurchaseOrderItem
	err := row.Scan(
		&i.ID,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.ProductID,
		&i.ProductName,
		&i.OrderedQuantity,
		&i.ReceivedQuantity,
		&i.DamagedQuantity,
		&i.UnitCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deletePOItemsByOrder = `-- name: DeletePOItemsByOrder :exec
DELETE FROM purchase_order_items
WHERE purchase_order_id = $1
`

func (q *Queries) DeletePOItemsByOrder(ctx context.Context, purchaseOrderID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deletePOItemsByOrder, purchaseOrderID)
	return err
}

const deletePurchaseOrder = `-- name: DeletePurchaseOrder :exec
DELETE FROM purchase_orders
WHERE id = $1 AND store_id = $2 AND status = 'draft'
`

type DeletePurchaseOrderParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeletePurchaseOrder(ctx context.Context, arg DeletePurchaseOrderParams) error {
	_, err := q.db.Exec(ctx, deletePurchaseOrder, arg.ID, arg.StoreID)
	return err
}

const getPOItem = `-- name: GetPOItem :one
SELECT poi.id, poi.purchase_order_id, poi.supplier_id, poi.product_id, poi.product_name, poi.ordered_quantity, poi.received_quantity, poi.damaged_quantity, poi.unit_cost, poi.created_at, poi.updated_at, s.name as supplier_name
FROM purchase_order_items poi
JOIN suppliers s ON poi.supplier_id = s.id
WHERE poi.id = $1
`

type GetPOItemRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PurchaseOrderID  pgtype.UUID        `db:"purchase_order_id" json:"purchase_order_id"`
	SupplierID       pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	ProductID        pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName      string             `db:"product_name" json:"product_name"`
	OrderedQuantity  int32              `db:"ordered_quantity" json:"ordered_quantity"`
	ReceivedQuantity int32              `db:"received_quantity" json:"received_quantity"`
	DamagedQuantity  int32              `db:"damaged_quantity" json:"damaged_quantity"`
	UnitCost         pgtype.Numeric     `db:"unit_cost" json:"unit_cost"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SupplierName     pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) GetPOItem(ctx context.Context, id pgtype.UUID) (GetPOItemRow, error) {
	row := q.db.QueryRow(ctx, getPOItem, id)
	var i GetPOItemRow
	err := row.Scan(
		&i.ID,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.ProductID,
		&i.ProductName,
		&i.OrderedQuantity,
		&i.ReceivedQuantity,
		&i.DamagedQuantity,
		&i.UnitCost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupplierName,
	)
	return i, err
}

const getPOItemsBySupplier = `-- name: GetPOItemsBySupplier :many
SELECT poi.id, poi.purchase_order_id, poi.supplier_id, poi.product_id, poi.product_name, poi.ordered_quantity, poi.received_quantity, poi.damaged_quantity, poi.unit_cost, poi.created_at, poi.updated_at, s.name as supplier_name
FROM purchase_order_items poi
JOIN suppliers s ON poi.supplier_id = s.id
WHERE poi.purchase_order_id = $1
ORDER BY poi.supplier_id, poi.created_at
`

type GetPOItemsBySupplierRow struct {
	ID               pgtype.UUID        `db:"id" json:"id"`
	PurchaseOrderID  pgtype.UUID        `db:"purchase_order_id" json:"purchase_order_id"`
	SupplierID       pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	ProductID        pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName      string             `db:"product_name" json:"product_name"`
	OrderedQuantity  int32              `db:"ordered_quantity" json:"ordered_quantity"`
	ReceivedQuantity int32              `db:"received_quantity" json:"received_quantity"`
	DamagedQuantity  int32              `db:"damaged_quantity" json:"damaged_quantity"`
	UnitCost         pgtype.Numeric     `db:"unit_cost" json:"unit_cost"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SupplierName     pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) GetPOItemsBySupplier(ctx context.Context, purchaseOrderID pgtype.UUID) ([]GetPOItemsBySupplierRow, error) {
	rows, err := q.db.Query(ctx, getPOItemsBySupplier, purchaseOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPOItemsBySupplierRow
	for rows.Next() {
		var i GetPOItemsBySupplierRow
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseOrderID,
			&i.SupplierID,
			&i.ProductID,
			&i.ProductName,
			&i.OrderedQuantity,
			&i.ReceivedQuantity,
			&i.DamagedQuantity,
			&i.UnitCost,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPOItemsForReceive = `-- name: GetPOItemsForReceive :many
SELECT poi.id, poi.purchase_order_id, poi.supplier_id, poi.product_id, poi.product_name, poi.ordered_quantity, poi.received_quantity, poi.damaged_quantity, poi.unit_cost, poi.created_at, poi.updated_at, s.name as supplier_name, p.name as product_name_lookup
FROM purchase_order_items poi
JOIN suppliers s ON poi.supplier_id = s.id
LEFT JOIN products p ON poi.product_id = p.id
WHERE poi.purchase_order_id = $1
ORDER BY poi.supplier_id, poi.created_at
`

type GetPOItemsForReceiveRow struct {
	ID                pgtype.UUID        `db:"id" json:"id"`
	PurchaseOrderID   pgtype.UUID        `db:"purchase_order_id" json:"purchase_order_id"`
	SupplierID        pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	ProductID         pgtype.UUID        `db:"product_id" json:"product_id"`
	ProductName       string             `db:"product_name" json:"product_name"`
	OrderedQuantity   int32              `db:"ordered_quantity" json:"ordered_quantity"`
	ReceivedQuantity  int32              `db:"received_quantity" json:"received_quantity"`
	DamagedQuantity   int32              `db:"damaged_quantity" json:"damaged_quantity"`
	UnitCost          pgtype.Numeric     `db:"unit_cost" json:"unit_cost"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SupplierName      pgtype.Text        `db:"supplier_name" json:"supplier_name"`
	ProductNameLookup pgtype.Text        `db:"product_name_lookup" json:"product_name_lookup"`
}

func (q *Queries) GetPOItemsForReceive(ctx context.Context, purchaseOrderID pgtype.UUID) ([]GetPOItemsForReceiveRow, error) {
	rows, err := q.db.Query(ctx, getPOItemsForReceive, purchaseOrderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPOItemsForReceiveRow
	for rows.Next() {
		var i GetPOItemsForReceiveRow
		if err := rows.Scan(
			&i.ID,
			&i.PurchaseOrderID,
			&i.SupplierID,
			&i.ProductID,
			&i.ProductName,
			&i.OrderedQuantity,
			&i.ReceivedQuantity,
			&i.DamagedQuantity,
			&i.UnitCost,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupplierName,
			&i.ProductNameLookup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPurchaseOrder = `-- name: GetPurchaseOrder :one
SELECT po.id, po.store_id, po.order_date, po.expected_delivery_date, po.status, po.notes, po.total_cost, po.created_at, po.updated_at,
    COALESCE(
        (SELECT jsonb_agg(jsonb_build_object(
            'id', poi.id,
            'supplier_id', poi.supplier_id,
            'supplier_name', s.name,
            'product_id', poi.product_id,
            'product_name', poi.product_name,
            'ordered_quantity', poi.ordered_quantity,
            'received_quantity', poi.received_quantity,
            'damaged_quantity', poi.damaged_quantity,
            'unit_cost', poi.unit_cost
        ) ORDER BY poi.created_at)
        FROM purchase_order_items poi
        JOIN suppliers s ON poi.supplier_id = s.id
        WHERE poi.purchase_order_id = po.id),
        '[]'::jsonb
    )::TEXT as items_json
FROM purchase_orders po
WHERE po.id = $1 AND po.store_id = $2
`

type GetPurchaseOrderParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

type GetPurchaseOrderRow struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	StoreID              pgtype.UUID        `db:"store_id" json:"store_id"`
	OrderDate            pgtype.Timestamptz `db:"order_date" json:"order_date"`
	ExpectedDeliveryDate pgtype.Timestamptz `db:"expected_delivery_date" json:"expected_delivery_date"`
	Status               string             `db:"status" json:"status"`
	Notes                pgtype.Text        `db:"notes" json:"notes"`
	TotalCost            pgtype.Numeric     `db:"total_cost" json:"total_cost"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ItemsJson            string             `db:"items_json" json:"items_json"`
}

func (q *Queries) GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (GetPurchaseOrderRow, error) {
	row := q.db.QueryRow(ctx, getPurchaseOrder, arg.ID, arg.StoreID)
	var i GetPurchaseOrderRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.Status,
		&i.Notes,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.ItemsJson,
	)
	return i, err
}

const getPurchaseOrdersBySupplier = `-- name: GetPurchaseOrdersBySupplier :many
SELECT po.id, po.store_id, po.order_date, po.expected_delivery_date, po.status, po.notes, po.total_cost, po.created_at, po.updated_at
FROM purchase_orders po
WHERE po.store_id = $1
  AND EXISTS (
    SELECT 1 FROM purchase_order_items poi
    WHERE poi.purchase_order_id = po.id AND poi.supplier_id = $2
  )
ORDER BY po.created_at DESC
`

type GetPurchaseOrdersBySupplierParams struct {
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
}

func (q *Queries) GetPurchaseOrdersBySupplier(ctx context.Context, arg GetPurchaseOrdersBySupplierParams) ([]PurchaseOrder, error) {
	rows, err := q.db.Query(ctx, getPurchaseOrdersBySupplier, arg.StoreID, arg.SupplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PurchaseOrder
	for rows.Next() {
		var i PurchaseOrder
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.OrderDate,
			&i.ExpectedDeliveryDate,
			&i.Status,
			&i.Notes,
			&i.TotalCost,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPurchaseOrders = `-- name: ListPurchaseOrders :many
SELECT po.id, po.order_date, po.status, po.total_cost, po.created_at,
    COALESCE(
        (SELECT jsonb_agg(DISTINCT jsonb_build_object('id', s.id, 'name', s.name))
        FROM purchase_order_items poi
        JOIN suppliers s ON poi.supplier_id = s.id
        WHERE poi.purchase_order_id = po.id),
        '[]'::jsonb
    )::TEXT as suppliers_json
FROM purchase_orders po
WHERE po.store_id = $1
ORDER BY po.created_at DESC
`

type ListPurchaseOrdersRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	OrderDate     pgtype.Timestamptz `db:"order_date" json:"order_date"`
	Status        string             `db:"status" json:"status"`
	TotalCost     pgtype.Numeric     `db:"total_cost" json:"total_cost"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SuppliersJson string             `db:"suppliers_json" json:"suppliers_json"`
}

func (q *Queries) ListPurchaseOrders(ctx context.Context, storeID pgtype.UUID) ([]ListPurchaseOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPurchaseOrders, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPurchaseOrdersRow
	for rows.Next() {
		var i ListPurchaseOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderDate,
			&i.Status,
			&i.TotalCost,
			&i.CreatedAt,
			&i.SuppliersJson,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePOItemReceive = `-- name: UpdatePOItemReceive :one
UPDATE purchase_order_items
SET received_quantity = received_quantity + $2,
    damaged_quantity = damaged_quantity + $3,
    updated_at = NOW()
WHERE id = $1
RETURNING id, purchase_order_id, supplier_id, product_id, product_name, ordered_quantity, received_quantity, damaged_quantity, unit_cost, created_at, updated_at
`

type UpdatePOItemReceiveParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	ReceivedQuantity int32       `db:"received_quantity" json:"received_quantity"`
	DamagedQuantity  int32       `db:"damaged_quantity" json:"damaged_quantity"`
}

func (q *Queries) UpdatePOItemReceive(ctx context.Context, arg UpdatePOItemReceiveParams) (PurchaseOrderItem, error) {
	row := q.db.QueryRow(ctx, updatePOItemReceive, arg.ID, arg.ReceivedQuantity, arg.DamagedQuantity)
	var i PurchaseOrderItem
	err := row.Scan(
		&i.ID,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.ProductID,
		&i.ProductName,
		&i.OrderedQuantity,
		&i.ReceivedQuantity,
		&i.DamagedQuantity,
		&i.UnitCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePurchaseOrder = `-- name: UpdatePurchaseOrder :one
UPDATE purchase_orders
SET status = $2, notes = COALESCE($3, notes), expected_delivery_date = COALESCE($4, expected_delivery_date), total_cost = $5, updated_at = NOW()
WHERE id = $1 AND store_id = $6
RETURNING id, store_id, order_date, expected_delivery_date, status, notes, total_cost, created_at, updated_at
`

type UpdatePurchaseOrderParams struct {
	ID                   pgtype.UUID        `db:"id" json:"id"`
	Status               string             `db:"status" json:"status"`
	Notes                pgtype.Text        `db:"notes" json:"notes"`
	ExpectedDeliveryDate pgtype.Timestamptz `db:"expected_delivery_date" json:"expected_delivery_date"`
	TotalCost            pgtype.Numeric     `db:"total_cost" json:"total_cost"`
	StoreID              pgtype.UUID        `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdatePurchaseOrder(ctx context.Context, arg UpdatePurchaseOrderParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrder,
		arg.ID,
		arg.Status,
		arg.Notes,
		arg.ExpectedDeliveryDate,
		arg.TotalCost,
		arg.StoreID,
	)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.Status,
		&i.Notes,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePurchaseOrderItem = `-- name: UpdatePurchaseOrderItem :one
UPDATE purchase_order_items
SET received_quantity = $2, damaged_quantity = $3, updated_at = NOW()
WHERE id = $1
RETURNING id, purchase_order_id, supplier_id, product_id, product_name, ordered_quantity, received_quantity, damaged_quantity, unit_cost, created_at, updated_at
`

type UpdatePurchaseOrderItemParams struct {
	ID               pgtype.UUID `db:"id" json:"id"`
	ReceivedQuantity int32       `db:"received_quantity" json:"received_quantity"`
	DamagedQuantity  int32       `db:"damaged_quantity" json:"damaged_quantity"`
}

func (q *Queries) UpdatePurchaseOrderItem(ctx context.Context, arg UpdatePurchaseOrderItemParams) (PurchaseOrderItem, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrderItem, arg.ID, arg.ReceivedQuantity, arg.DamagedQuantity)
	var i PurchaseOrderItem
	err := row.Scan(
		&i.ID,
		&i.PurchaseOrderID,
		&i.SupplierID,
		&i.ProductID,
		&i.ProductName,
		&i.OrderedQuantity,
		&i.ReceivedQuantity,
		&i.DamagedQuantity,
		&i.UnitCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updatePurchaseOrderStatus = `-- name: UpdatePurchaseOrderStatus :one
UPDATE purchase_orders
SET status = $2, updated_at = NOW()
WHERE id = $1 AND store_id = $3
RETURNING id, store_id, order_date, expected_delivery_date, status, notes, total_cost, created_at, updated_at
`

type UpdatePurchaseOrderStatusParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	Status  string      `db:"status" json:"status"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) (PurchaseOrder, error) {
	row := q.db.QueryRow(ctx, updatePurchaseOrderStatus, arg.ID, arg.Status, arg.StoreID)
	var i PurchaseOrder
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.OrderDate,
		&i.ExpectedDeliveryDate,
		&i.Status,
		&i.Notes,
		&i.TotalCost,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
