// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CheckNotificationExists(ctx context.Context, arg CheckNotificationExistsParams) (bool, error)
	CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOTPToken(ctx context.Context, arg CreateOTPTokenParams) (OtpToken, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error)
	CreateStoreInfo(ctx context.Context, arg CreateStoreInfoParams) (StoreInfo, error)
	CreateStoreOwner(ctx context.Context, arg CreateStoreOwnerParams) (StoreOwner, error)
	CreateSuppliers(ctx context.Context, arg CreateSuppliersParams) (Supplier, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteDebt(ctx context.Context, arg DeleteDebtParams) error
	DeleteExpiredOTPs(ctx context.Context) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteOTPToken(ctx context.Context, id pgtype.UUID) error
	DeleteOldNotifications(ctx context.Context, storeID pgtype.UUID) error
	DeleteProduct(ctx context.Context, id pgtype.UUID) error
	DeleteStoreInfo(ctx context.Context, id pgtype.UUID) error
	DeleteStoreOwner(ctx context.Context, id pgtype.UUID) error
	DeleteSupplier(ctx context.Context, arg DeleteSupplierParams) error
	DismissNotification(ctx context.Context, arg DismissNotificationParams) (Notification, error)
	FlagExpiringProducts(ctx context.Context) error
	GetAllStores(ctx context.Context) ([]StoreInfo, error)
	GetAllSuppliers(ctx context.Context, storeID pgtype.UUID) ([]Supplier, error)
	GetCategories(ctx context.Context, storeID pgtype.UUID) ([]Category, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetCategoryByStore(ctx context.Context, arg GetCategoryByStoreParams) (Category, error)
	GetCategoryStats(ctx context.Context, arg GetCategoryStatsParams) (GetCategoryStatsRow, error)
	GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error)
	GetDailySales(ctx context.Context, arg GetDailySalesParams) ([]GetDailySalesRow, error)
	GetDebt(ctx context.Context, arg GetDebtParams) (GetDebtRow, error)
	GetDebts(ctx context.Context, storeID pgtype.UUID) ([]GetDebtsRow, error)
	GetDebtsStats(ctx context.Context, storeID pgtype.UUID) (GetDebtsStatsRow, error)
	GetDueDebts(ctx context.Context, storeID pgtype.UUID) ([]GetDueDebtsRow, error)
	GetInactiveProducts(ctx context.Context, arg GetInactiveProductsParams) ([]GetInactiveProductsRow, error)
	GetInventoryStats(ctx context.Context, storeID pgtype.UUID) (GetInventoryStatsRow, error)
	GetLowStockProducts(ctx context.Context, storeID pgtype.UUID) ([]Product, error)
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]Notification, error)
	GetProduct(ctx context.Context, id pgtype.UUID) (Product, error)
	GetProfitStats(ctx context.Context, arg GetProfitStatsParams) (GetProfitStatsRow, error)
	GetRecentSales(ctx context.Context, arg GetRecentSalesParams) ([]GetRecentSalesRow, error)
	GetRevenueByCategory(ctx context.Context, arg GetRevenueByCategoryParams) ([]GetRevenueByCategoryRow, error)
	GetSale(ctx context.Context, arg GetSaleParams) (GetSaleRow, error)
	GetSaleItems(ctx context.Context, saleID pgtype.UUID) ([]GetSaleItemsRow, error)
	GetSalesByType(ctx context.Context, arg GetSalesByTypeParams) ([]GetSalesByTypeRow, error)
	GetSalesForPeriod(ctx context.Context, arg GetSalesForPeriodParams) (pgtype.Numeric, error)
	GetSalesInRange(ctx context.Context, arg GetSalesInRangeParams) ([]GetSalesInRangeRow, error)
	GetStockByCategory(ctx context.Context, storeID pgtype.UUID) ([]GetStockByCategoryRow, error)
	GetStoreInfo(ctx context.Context, id pgtype.UUID) (StoreInfo, error)
	GetStoreInfoByOwner(ctx context.Context, ownerID pgtype.UUID) (StoreInfo, error)
	GetStoreOwner(ctx context.Context, id pgtype.UUID) (StoreOwner, error)
	GetStoreOwnerByEmail(ctx context.Context, email string) (StoreOwner, error)
	GetStoreOwnerById(ctx context.Context, id pgtype.UUID) (StoreOwner, error)
	GetStoreWithOwner(ctx context.Context, id pgtype.UUID) (GetStoreWithOwnerRow, error)
	GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error)
	GetTopDebtors(ctx context.Context, arg GetTopDebtorsParams) ([]GetTopDebtorsRow, error)
	GetTopSellingProducts(ctx context.Context, arg GetTopSellingProductsParams) ([]GetTopSellingProductsRow, error)
	GetTotalSales(ctx context.Context, arg GetTotalSalesParams) (GetTotalSalesRow, error)
	GetUnreadCount(ctx context.Context, storeID pgtype.UUID) (int64, error)
	GetUnreadNotifications(ctx context.Context, storeID pgtype.UUID) ([]Notification, error)
	ListCustomers(ctx context.Context, storeID pgtype.UUID) ([]Customer, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListSales(ctx context.Context, storeID pgtype.UUID) ([]ListSalesRow, error)
	ListStoreInfo(ctx context.Context, arg ListStoreInfoParams) ([]StoreInfo, error)
	ListStoreOwners(ctx context.Context, arg ListStoreOwnersParams) ([]StoreOwner, error)
	ListTrackedProducts(ctx context.Context, storeID pgtype.UUID) ([]Product, error)
	MarkAllNotificationsAsRead(ctx context.Context, storeID pgtype.UUID) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error)
	RecordDebtPayment(ctx context.Context, arg RecordDebtPaymentParams) (Debt, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error)
	UpdateEmailVerification(ctx context.Context, email string) error
	UpdatePasswordByEmail(ctx context.Context, arg UpdatePasswordByEmailParams) error
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateStoreInfo(ctx context.Context, arg UpdateStoreInfoParams) (StoreInfo, error)
	UpdateStoreOwner(ctx context.Context, arg UpdateStoreOwnerParams) (StoreOwner, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	VerifyOTP(ctx context.Context, arg VerifyOTPParams) (OtpToken, error)
}

var _ Querier = (*Queries)(nil)
