// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddDamagedProductStock(ctx context.Context, arg AddDamagedProductStockParams) (Product, error)
	AddDamagedVariantStock(ctx context.Context, arg AddDamagedVariantStockParams) (ProductVariant, error)
	ArchiveProductVariant(ctx context.Context, id pgtype.UUID) error
	CheckNotificationExists(ctx context.Context, arg CheckNotificationExistsParams) (bool, error)
	CreateCategories(ctx context.Context, arg CreateCategoriesParams) (Category, error)
	CreateCustomer(ctx context.Context, arg CreateCustomerParams) (Customer, error)
	CreateDebt(ctx context.Context, arg CreateDebtParams) (Debt, error)
	CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error)
	CreateNotification(ctx context.Context, arg CreateNotificationParams) (Notification, error)
	CreateOTPToken(ctx context.Context, arg CreateOTPTokenParams) (OtpToken, error)
	CreatePaymentRecord(ctx context.Context, arg CreatePaymentRecordParams) (PaymentRecord, error)
	CreateProduct(ctx context.Context, arg CreateProductParams) (Product, error)
	CreateProductVariant(ctx context.Context, arg CreateProductVariantParams) (ProductVariant, error)
	CreatePurchaseOrder(ctx context.Context, arg CreatePurchaseOrderParams) (PurchaseOrder, error)
	CreatePurchaseOrderItem(ctx context.Context, arg CreatePurchaseOrderItemParams) (PurchaseOrderItem, error)
	CreateReturn(ctx context.Context, arg CreateReturnParams) (Return, error)
	CreateReturnItem(ctx context.Context, arg CreateReturnItemParams) (ReturnItem, error)
	CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error)
	CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error)
	CreateStoreInfo(ctx context.Context, arg CreateStoreInfoParams) (StoreInfo, error)
	CreateStoreOwner(ctx context.Context, arg CreateStoreOwnerParams) (StoreOwner, error)
	CreateSupplierPayable(ctx context.Context, arg CreateSupplierPayableParams) (SupplierPayable, error)
	CreateSuppliers(ctx context.Context, arg CreateSuppliersParams) (Supplier, error)
	DeleteCategory(ctx context.Context, arg DeleteCategoryParams) error
	DeleteDebt(ctx context.Context, arg DeleteDebtParams) error
	DeleteExpense(ctx context.Context, arg DeleteExpenseParams) error
	DeleteExpiredOTPs(ctx context.Context) error
	DeleteNotification(ctx context.Context, arg DeleteNotificationParams) error
	DeleteOTPToken(ctx context.Context, id pgtype.UUID) error
	DeleteOldNotifications(ctx context.Context, storeID pgtype.UUID) error
	DeletePOItemsByOrder(ctx context.Context, purchaseOrderID pgtype.UUID) error
	DeleteProduct(ctx context.Context, arg DeleteProductParams) error
	DeleteProductVariant(ctx context.Context, id pgtype.UUID) error
	DeletePurchaseOrder(ctx context.Context, arg DeletePurchaseOrderParams) error
	DeleteStoreInfo(ctx context.Context, arg DeleteStoreInfoParams) error
	DeleteStoreOwner(ctx context.Context, id pgtype.UUID) error
	DeleteSupplier(ctx context.Context, arg DeleteSupplierParams) error
	DeleteSupplierPayable(ctx context.Context, arg DeleteSupplierPayableParams) error
	DeleteVariantsByProduct(ctx context.Context, arg DeleteVariantsByProductParams) error
	DismissNotification(ctx context.Context, arg DismissNotificationParams) (Notification, error)
	FlagExpiringProducts(ctx context.Context) error
	GetAllStores(ctx context.Context) ([]StoreInfo, error)
	GetAllSuppliers(ctx context.Context, storeID pgtype.UUID) ([]GetAllSuppliersRow, error)
	GetBalanceSheetAssets(ctx context.Context, storeID pgtype.UUID) (GetBalanceSheetAssetsRow, error)
	GetBalanceSheetLiabilities(ctx context.Context, storeID pgtype.UUID) (pgtype.Numeric, error)
	GetCashFlowDaily(ctx context.Context, arg GetCashFlowDailyParams) ([]GetCashFlowDailyRow, error)
	GetCategories(ctx context.Context, storeID pgtype.UUID) ([]Category, error)
	GetCategory(ctx context.Context, arg GetCategoryParams) (Category, error)
	GetCategoryByStore(ctx context.Context, arg GetCategoryByStoreParams) (Category, error)
	GetCategoryStats(ctx context.Context, arg GetCategoryStatsParams) (GetCategoryStatsRow, error)
	GetCustomerByPhone(ctx context.Context, arg GetCustomerByPhoneParams) (Customer, error)
	GetCustomerLoyaltyStatus(ctx context.Context, arg GetCustomerLoyaltyStatusParams) (GetCustomerLoyaltyStatusRow, error)
	GetDailyExpenses(ctx context.Context, arg GetDailyExpensesParams) ([]GetDailyExpensesRow, error)
	GetDailySales(ctx context.Context, arg GetDailySalesParams) ([]GetDailySalesRow, error)
	GetDailySupplierPayments(ctx context.Context, arg GetDailySupplierPaymentsParams) ([]GetDailySupplierPaymentsRow, error)
	GetDeadStock(ctx context.Context, arg GetDeadStockParams) ([]GetDeadStockRow, error)
	GetDebt(ctx context.Context, arg GetDebtParams) (GetDebtRow, error)
	GetDebts(ctx context.Context, storeID pgtype.UUID) ([]GetDebtsRow, error)
	GetDebtsStats(ctx context.Context, storeID pgtype.UUID) (GetDebtsStatsRow, error)
	GetDueDebts(ctx context.Context, storeID pgtype.UUID) ([]GetDueDebtsRow, error)
	GetExpense(ctx context.Context, arg GetExpenseParams) (Expense, error)
	GetExpenseSummary(ctx context.Context, arg GetExpenseSummaryParams) (GetExpenseSummaryRow, error)
	GetExpenseTotalsByCategory(ctx context.Context, arg GetExpenseTotalsByCategoryParams) ([]GetExpenseTotalsByCategoryRow, error)
	GetHourlyTransactionHeatmap(ctx context.Context, storeID pgtype.UUID) ([]GetHourlyTransactionHeatmapRow, error)
	GetInactiveProducts(ctx context.Context, arg GetInactiveProductsParams) ([]GetInactiveProductsRow, error)
	GetInventoryStats(ctx context.Context, storeID pgtype.UUID) (GetInventoryStatsRow, error)
	GetLowStockProducts(ctx context.Context, storeID pgtype.UUID) ([]Product, error)
	GetNetProfit(ctx context.Context, arg GetNetProfitParams) (GetNetProfitRow, error)
	GetNotifications(ctx context.Context, arg GetNotificationsParams) ([]Notification, error)
	GetOverduePayables(ctx context.Context, storeID pgtype.UUID) ([]GetOverduePayablesRow, error)
	GetPOItem(ctx context.Context, id pgtype.UUID) (GetPOItemRow, error)
	GetPOItemsBySupplier(ctx context.Context, purchaseOrderID pgtype.UUID) ([]GetPOItemsBySupplierRow, error)
	GetPOItemsForReceive(ctx context.Context, purchaseOrderID pgtype.UUID) ([]GetPOItemsForReceiveRow, error)
	GetPOSCatalog(ctx context.Context, storeID pgtype.UUID) ([]GetPOSCatalogRow, error)
	GetPaymentTotalsByStore(ctx context.Context, storeID pgtype.UUID) ([]GetPaymentTotalsByStoreRow, error)
	GetProduct(ctx context.Context, arg GetProductParams) (Product, error)
	GetProductPairFrequency(ctx context.Context, storeID pgtype.UUID) ([]GetProductPairFrequencyRow, error)
	GetProductVariant(ctx context.Context, arg GetProductVariantParams) (ProductVariant, error)
	GetProductVelocity(ctx context.Context, storeID pgtype.UUID) ([]GetProductVelocityRow, error)
	GetProfitStats(ctx context.Context, arg GetProfitStatsParams) (GetProfitStatsRow, error)
	GetPurchaseOrder(ctx context.Context, arg GetPurchaseOrderParams) (GetPurchaseOrderRow, error)
	GetPurchaseOrdersBySupplier(ctx context.Context, arg GetPurchaseOrdersBySupplierParams) ([]PurchaseOrder, error)
	GetRecentSales(ctx context.Context, arg GetRecentSalesParams) ([]GetRecentSalesRow, error)
	GetReturnItems(ctx context.Context, returnID pgtype.UUID) ([]GetReturnItemsRow, error)
	GetRevenueByCategory(ctx context.Context, arg GetRevenueByCategoryParams) ([]GetRevenueByCategoryRow, error)
	GetSale(ctx context.Context, arg GetSaleParams) (GetSaleRow, error)
	GetSaleItem(ctx context.Context, arg GetSaleItemParams) (SaleItem, error)
	GetSaleItems(ctx context.Context, saleID pgtype.UUID) ([]GetSaleItemsRow, error)
	GetSalesByType(ctx context.Context, arg GetSalesByTypeParams) ([]GetSalesByTypeRow, error)
	GetSalesForPeriod(ctx context.Context, arg GetSalesForPeriodParams) (pgtype.Numeric, error)
	GetSalesInRange(ctx context.Context, arg GetSalesInRangeParams) ([]GetSalesInRangeRow, error)
	GetStockByCategory(ctx context.Context, storeID pgtype.UUID) ([]GetStockByCategoryRow, error)
	GetStoreInfo(ctx context.Context, id pgtype.UUID) (StoreInfo, error)
	GetStoreInfoByOwner(ctx context.Context, ownerID pgtype.UUID) (StoreInfo, error)
	GetStoreOwner(ctx context.Context, id pgtype.UUID) (StoreOwner, error)
	GetStoreOwnerByEmail(ctx context.Context, email string) (StoreOwner, error)
	GetStoreOwnerById(ctx context.Context, id pgtype.UUID) (StoreOwner, error)
	GetStoreWithOwner(ctx context.Context, id pgtype.UUID) (GetStoreWithOwnerRow, error)
	GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error)
	GetSupplierPayable(ctx context.Context, arg GetSupplierPayableParams) (GetSupplierPayableRow, error)
	GetSupplierPayableSummary(ctx context.Context, storeID pgtype.UUID) (GetSupplierPayableSummaryRow, error)
	GetSupplierStats(ctx context.Context, arg GetSupplierStatsParams) (GetSupplierStatsRow, error)
	GetSupplierTotalPayable(ctx context.Context, arg GetSupplierTotalPayableParams) (pgtype.Numeric, error)
	GetTopDebtors(ctx context.Context, arg GetTopDebtorsParams) ([]GetTopDebtorsRow, error)
	GetTopSellingProducts(ctx context.Context, arg GetTopSellingProductsParams) ([]GetTopSellingProductsRow, error)
	GetTotalExpensesForPeriod(ctx context.Context, arg GetTotalExpensesForPeriodParams) (pgtype.Numeric, error)
	GetTotalSales(ctx context.Context, arg GetTotalSalesParams) (GetTotalSalesRow, error)
	GetTotalSupplierPaymentsForPeriod(ctx context.Context, arg GetTotalSupplierPaymentsForPeriodParams) (pgtype.Numeric, error)
	GetUnreadCount(ctx context.Context, storeID pgtype.UUID) (int64, error)
	GetUnreadNotifications(ctx context.Context, storeID pgtype.UUID) ([]Notification, error)
	GetVariantByBarcodeOrSKU(ctx context.Context, barcode pgtype.Text) (ProductVariant, error)
	GetVariantBySKU(ctx context.Context, sku string) (ProductVariant, error)
	IncrementCustomerPurchaseCount(ctx context.Context, arg IncrementCustomerPurchaseCountParams) error
	ListCustomers(ctx context.Context, storeID pgtype.UUID) ([]Customer, error)
	ListExpenses(ctx context.Context, arg ListExpensesParams) ([]Expense, error)
	ListPaymentsByPayable(ctx context.Context, arg ListPaymentsByPayableParams) ([]SupplierPayment, error)
	ListPaymentsBySale(ctx context.Context, saleID pgtype.UUID) ([]PaymentRecord, error)
	ListProducts(ctx context.Context, arg ListProductsParams) ([]Product, error)
	ListProductsByCategory(ctx context.Context, arg ListProductsByCategoryParams) ([]Product, error)
	ListProductsBySupplier(ctx context.Context, arg ListProductsBySupplierParams) ([]Product, error)
	ListPurchaseOrders(ctx context.Context, storeID pgtype.UUID) ([]ListPurchaseOrdersRow, error)
	ListReturns(ctx context.Context, arg ListReturnsParams) ([]ListReturnsRow, error)
	ListSales(ctx context.Context, storeID pgtype.UUID) ([]ListSalesRow, error)
	ListStoreInfo(ctx context.Context, arg ListStoreInfoParams) ([]StoreInfo, error)
	ListStoreOwners(ctx context.Context, arg ListStoreOwnersParams) ([]StoreOwner, error)
	ListSupplierPayables(ctx context.Context, arg ListSupplierPayablesParams) ([]ListSupplierPayablesRow, error)
	ListTrackedProducts(ctx context.Context, storeID pgtype.UUID) ([]Product, error)
	ListVariantsByProduct(ctx context.Context, productID pgtype.UUID) ([]ProductVariant, error)
	ListVariantsByProducts(ctx context.Context, dollar_1 []pgtype.UUID) ([]ProductVariant, error)
	MarkAllNotificationsAsRead(ctx context.Context, storeID pgtype.UUID) error
	MarkNotificationAsRead(ctx context.Context, arg MarkNotificationAsReadParams) (Notification, error)
	RecordDebtPayment(ctx context.Context, arg RecordDebtPaymentParams) (Debt, error)
	RecordSupplierPayment(ctx context.Context, arg RecordSupplierPaymentParams) (SupplierPayment, error)
	ReturnProductStock(ctx context.Context, arg ReturnProductStockParams) (Product, error)
	ReturnVariantStock(ctx context.Context, arg ReturnVariantStockParams) (ProductVariant, error)
	SearchCustomers(ctx context.Context, arg SearchCustomersParams) ([]Customer, error)
	SearchProducts(ctx context.Context, arg SearchProductsParams) ([]Product, error)
	UpdateCategory(ctx context.Context, arg UpdateCategoryParams) (Category, error)
	UpdateCustomer(ctx context.Context, arg UpdateCustomerParams) (Customer, error)
	UpdateCustomerLoyalty(ctx context.Context, arg UpdateCustomerLoyaltyParams) error
	UpdateDebt(ctx context.Context, arg UpdateDebtParams) (Debt, error)
	UpdateEmailVerification(ctx context.Context, email string) error
	UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error)
	UpdatePOItemReceive(ctx context.Context, arg UpdatePOItemReceiveParams) (PurchaseOrderItem, error)
	UpdatePasswordByEmail(ctx context.Context, arg UpdatePasswordByEmailParams) error
	UpdatePayableAfterPayment(ctx context.Context, arg UpdatePayableAfterPaymentParams) (SupplierPayable, error)
	UpdateProduct(ctx context.Context, arg UpdateProductParams) (Product, error)
	UpdateProductStock(ctx context.Context, arg UpdateProductStockParams) (Product, error)
	UpdateProductVariant(ctx context.Context, arg UpdateProductVariantParams) (ProductVariant, error)
	UpdatePurchaseOrder(ctx context.Context, arg UpdatePurchaseOrderParams) (PurchaseOrder, error)
	UpdatePurchaseOrderItem(ctx context.Context, arg UpdatePurchaseOrderItemParams) (PurchaseOrderItem, error)
	UpdatePurchaseOrderStatus(ctx context.Context, arg UpdatePurchaseOrderStatusParams) (PurchaseOrder, error)
	UpdateSaleAmount(ctx context.Context, arg UpdateSaleAmountParams) error
	UpdateStoreInfo(ctx context.Context, arg UpdateStoreInfoParams) (StoreInfo, error)
	UpdateStoreOwner(ctx context.Context, arg UpdateStoreOwnerParams) (StoreOwner, error)
	UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error)
	UpdateSupplierPayable(ctx context.Context, arg UpdateSupplierPayableParams) (SupplierPayable, error)
	UpdateVariantStock(ctx context.Context, arg UpdateVariantStockParams) (ProductVariant, error)
	VerifyOTP(ctx context.Context, arg VerifyOTPParams) (OtpToken, error)
}

var _ Querier = (*Queries)(nil)
