// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	CreateStoreInfo(ctx context.Context, arg CreateStoreInfoParams) (StoreInfo, error)
	CreateStoreOwner(ctx context.Context, arg CreateStoreOwnerParams) (StoreOwner, error)
	DeleteStoreInfo(ctx context.Context, id pgtype.UUID) error
	DeleteStoreOwner(ctx context.Context, id pgtype.UUID) error
	GetStoreInfo(ctx context.Context, id pgtype.UUID) (StoreInfo, error)
	GetStoreInfoByOwner(ctx context.Context, ownerID pgtype.UUID) (StoreInfo, error)
	GetStoreOwner(ctx context.Context, id pgtype.UUID) (StoreOwner, error)
	GetStoreOwnerByEmail(ctx context.Context, email string) (StoreOwner, error)
	GetStoreWithOwner(ctx context.Context, id pgtype.UUID) (GetStoreWithOwnerRow, error)
	ListStoreInfo(ctx context.Context, arg ListStoreInfoParams) ([]StoreInfo, error)
	ListStoreOwners(ctx context.Context, arg ListStoreOwnersParams) ([]StoreOwner, error)
	UpdateStoreInfo(ctx context.Context, arg UpdateStoreInfoParams) (StoreInfo, error)
	UpdateStoreOwner(ctx context.Context, arg UpdateStoreOwnerParams) (StoreOwner, error)
}

var _ Querier = (*Queries)(nil)
