// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getDailySales = `-- name: GetDailySales :many
SELECT 
    DATE(sale_date)::VARCHAR as sale_date,
    COALESCE(SUM(total_amount), 0.0)::DECIMAL(12,2) as daily_total
FROM sales
WHERE store_id = $1 AND sale_date BETWEEN $2 AND $3
GROUP BY DATE(sale_date)
ORDER BY DATE(sale_date)
`

type GetDailySalesParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	SaleDate   pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	SaleDate_2 pgtype.Timestamptz `db:"sale_date_2" json:"sale_date_2"`
}

type GetDailySalesRow struct {
	SaleDate   string         `db:"sale_date" json:"sale_date"`
	DailyTotal pgtype.Numeric `db:"daily_total" json:"daily_total"`
}

func (q *Queries) GetDailySales(ctx context.Context, arg GetDailySalesParams) ([]GetDailySalesRow, error) {
	rows, err := q.db.Query(ctx, getDailySales, arg.StoreID, arg.SaleDate, arg.SaleDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySalesRow
	for rows.Next() {
		var i GetDailySalesRow
		if err := rows.Scan(&i.SaleDate, &i.DailyTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getDebtsStats = `-- name: GetDebtsStats :one
SELECT 
    COALESCE(SUM(amount_owed - amount_paid), 0.0)::DECIMAL(12,2) as total_outstanding,
    COUNT(DISTINCT customer_id) as total_debtors
FROM debts
WHERE store_id = $1 AND amount_owed > amount_paid
`

type GetDebtsStatsRow struct {
	TotalOutstanding pgtype.Numeric `db:"total_outstanding" json:"total_outstanding"`
	TotalDebtors     int64          `db:"total_debtors" json:"total_debtors"`
}

func (q *Queries) GetDebtsStats(ctx context.Context, storeID pgtype.UUID) (GetDebtsStatsRow, error) {
	row := q.db.QueryRow(ctx, getDebtsStats, storeID)
	var i GetDebtsStatsRow
	err := row.Scan(&i.TotalOutstanding, &i.TotalDebtors)
	return i, err
}

const getInactiveProducts = `-- name: GetInactiveProducts :many
SELECT 
    p.name as product_name,
    p.stock_quantity,
    p.price,
    (p.stock_quantity * p.price)::DECIMAL(12,2) as potential_revenue,
    MAX(s.sale_date) as last_sold_at
FROM products p
LEFT JOIN sale_items si ON p.id = si.product_id
LEFT JOIN sales s ON si.sale_id = s.id
WHERE 
    p.store_id = $1 
    AND p.stock_quantity > 0 
    AND p.status = 'active'
GROUP BY p.id, p.name, p.stock_quantity, p.price
HAVING 
    MAX(s.sale_date) < NOW() - INTERVAL '30 days' 
    OR MAX(s.sale_date) IS NULL
ORDER BY potential_revenue DESC
LIMIT $2
`

type GetInactiveProductsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
}

type GetInactiveProductsRow struct {
	ProductName      string         `db:"product_name" json:"product_name"`
	StockQuantity    int32          `db:"stock_quantity" json:"stock_quantity"`
	Price            pgtype.Numeric `db:"price" json:"price"`
	PotentialRevenue pgtype.Numeric `db:"potential_revenue" json:"potential_revenue"`
	LastSoldAt       interface{}    `db:"last_sold_at" json:"last_sold_at"`
}

func (q *Queries) GetInactiveProducts(ctx context.Context, arg GetInactiveProductsParams) ([]GetInactiveProductsRow, error) {
	rows, err := q.db.Query(ctx, getInactiveProducts, arg.StoreID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInactiveProductsRow
	for rows.Next() {
		var i GetInactiveProductsRow
		if err := rows.Scan(
			&i.ProductName,
			&i.StockQuantity,
			&i.Price,
			&i.PotentialRevenue,
			&i.LastSoldAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getInventoryStats = `-- name: GetInventoryStats :one
SELECT 
    COUNT(*) as total_products,
    COALESCE(SUM(stock_quantity * COALESCE(market_price, price)), 0.0)::DECIMAL(12,2) as total_value,
    COUNT(*) FILTER (WHERE stock_quantity < low_stock_threshold) as low_stock_count
FROM products
WHERE store_id = $1 AND status = 'active'
`

type GetInventoryStatsRow struct {
	TotalProducts int64          `db:"total_products" json:"total_products"`
	TotalValue    pgtype.Numeric `db:"total_value" json:"total_value"`
	LowStockCount int64          `db:"low_stock_count" json:"low_stock_count"`
}

func (q *Queries) GetInventoryStats(ctx context.Context, storeID pgtype.UUID) (GetInventoryStatsRow, error) {
	row := q.db.QueryRow(ctx, getInventoryStats, storeID)
	var i GetInventoryStatsRow
	err := row.Scan(&i.TotalProducts, &i.TotalValue, &i.LowStockCount)
	return i, err
}

const getRecentSales = `-- name: GetRecentSales :many
SELECT 
    s.id,
    s.total_amount,
    s.sales_type,
    s.sale_date,
    c.name as customer_name
FROM sales s
LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.store_id = $1
ORDER BY s.sale_date DESC
LIMIT $2
`

type GetRecentSalesParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
}

type GetRecentSalesRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	TotalAmount  pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	SalesType    SalesTypes         `db:"sales_type" json:"sales_type"`
	SaleDate     pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	CustomerName pgtype.Text        `db:"customer_name" json:"customer_name"`
}

func (q *Queries) GetRecentSales(ctx context.Context, arg GetRecentSalesParams) ([]GetRecentSalesRow, error) {
	rows, err := q.db.Query(ctx, getRecentSales, arg.StoreID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentSalesRow
	for rows.Next() {
		var i GetRecentSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.TotalAmount,
			&i.SalesType,
			&i.SaleDate,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRevenueByCategory = `-- name: GetRevenueByCategory :many
SELECT 
    c.name as category_name,
    COALESCE(SUM(si.total_price), 0.0)::DECIMAL(12,2) as total_revenue
FROM sale_items si
JOIN products p ON si.product_id = p.id
JOIN categories c ON p.category_id = c.id
JOIN sales s ON si.sale_id = s.id
WHERE s.store_id = $1 AND s.sale_date BETWEEN $2 AND $3
GROUP BY c.id, c.name
ORDER BY total_revenue DESC
`

type GetRevenueByCategoryParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	SaleDate   pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	SaleDate_2 pgtype.Timestamptz `db:"sale_date_2" json:"sale_date_2"`
}

type GetRevenueByCategoryRow struct {
	CategoryName string         `db:"category_name" json:"category_name"`
	TotalRevenue pgtype.Numeric `db:"total_revenue" json:"total_revenue"`
}

func (q *Queries) GetRevenueByCategory(ctx context.Context, arg GetRevenueByCategoryParams) ([]GetRevenueByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getRevenueByCategory, arg.StoreID, arg.SaleDate, arg.SaleDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRevenueByCategoryRow
	for rows.Next() {
		var i GetRevenueByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.TotalRevenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesByType = `-- name: GetSalesByType :many
SELECT 
    sales_type,
    COALESCE(SUM(total_amount), 0.0)::DECIMAL(12,2) as total_amount,
    COUNT(*) as count
FROM sales
WHERE store_id = $1 AND sale_date BETWEEN $2 AND $3
GROUP BY sales_type
`

type GetSalesByTypeParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	SaleDate   pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	SaleDate_2 pgtype.Timestamptz `db:"sale_date_2" json:"sale_date_2"`
}

type GetSalesByTypeRow struct {
	SalesType   SalesTypes     `db:"sales_type" json:"sales_type"`
	TotalAmount pgtype.Numeric `db:"total_amount" json:"total_amount"`
	Count       int64          `db:"count" json:"count"`
}

func (q *Queries) GetSalesByType(ctx context.Context, arg GetSalesByTypeParams) ([]GetSalesByTypeRow, error) {
	rows, err := q.db.Query(ctx, getSalesByType, arg.StoreID, arg.SaleDate, arg.SaleDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSalesByTypeRow
	for rows.Next() {
		var i GetSalesByTypeRow
		if err := rows.Scan(&i.SalesType, &i.TotalAmount, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesForPeriod = `-- name: GetSalesForPeriod :one
SELECT 
    COALESCE(SUM(total_amount), 0.0)::DECIMAL(12,2) as total_sales
FROM sales
WHERE store_id = $1 AND sale_date BETWEEN $2 AND $3
`

type GetSalesForPeriodParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	SaleDate   pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	SaleDate_2 pgtype.Timestamptz `db:"sale_date_2" json:"sale_date_2"`
}

func (q *Queries) GetSalesForPeriod(ctx context.Context, arg GetSalesForPeriodParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getSalesForPeriod, arg.StoreID, arg.SaleDate, arg.SaleDate_2)
	var total_sales pgtype.Numeric
	err := row.Scan(&total_sales)
	return total_sales, err
}

const getStockByCategory = `-- name: GetStockByCategory :many
SELECT 
    c.name as category_name,
    COUNT(p.id) as product_count
FROM products p
JOIN categories c ON p.category_id = c.id
WHERE p.store_id = $1 AND p.status = 'active'
GROUP BY c.id, c.name
`

type GetStockByCategoryRow struct {
	CategoryName string `db:"category_name" json:"category_name"`
	ProductCount int64  `db:"product_count" json:"product_count"`
}

func (q *Queries) GetStockByCategory(ctx context.Context, storeID pgtype.UUID) ([]GetStockByCategoryRow, error) {
	rows, err := q.db.Query(ctx, getStockByCategory, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStockByCategoryRow
	for rows.Next() {
		var i GetStockByCategoryRow
		if err := rows.Scan(&i.CategoryName, &i.ProductCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopDebtors = `-- name: GetTopDebtors :many
SELECT 
    c.name as customer_name,
    c.phone as customer_phone,
    SUM(d.amount_owed - d.amount_paid)::DECIMAL(12,2) as total_debt,
    MAX(d.updated_at) as last_transaction
FROM debts d
JOIN customers c ON d.customer_id = c.id
WHERE d.store_id = $1 AND d.amount_owed > d.amount_paid
GROUP BY c.id, c.name, c.phone
ORDER BY total_debt DESC
LIMIT $2
`

type GetTopDebtorsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
}

type GetTopDebtorsRow struct {
	CustomerName    string         `db:"customer_name" json:"customer_name"`
	CustomerPhone   string         `db:"customer_phone" json:"customer_phone"`
	TotalDebt       pgtype.Numeric `db:"total_debt" json:"total_debt"`
	LastTransaction interface{}    `db:"last_transaction" json:"last_transaction"`
}

func (q *Queries) GetTopDebtors(ctx context.Context, arg GetTopDebtorsParams) ([]GetTopDebtorsRow, error) {
	rows, err := q.db.Query(ctx, getTopDebtors, arg.StoreID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopDebtorsRow
	for rows.Next() {
		var i GetTopDebtorsRow
		if err := rows.Scan(
			&i.CustomerName,
			&i.CustomerPhone,
			&i.TotalDebt,
			&i.LastTransaction,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopSellingProducts = `-- name: GetTopSellingProducts :many
SELECT 
    p.name as product_name,
    SUM(si.quantity)::BIGINT as total_quantity
FROM sale_items si
JOIN products p ON si.product_id = p.id
JOIN sales s ON si.sale_id = s.id
WHERE s.store_id = $1 AND s.sale_date BETWEEN $2 AND $3
GROUP BY p.id, p.name
ORDER BY total_quantity DESC
LIMIT $4
`

type GetTopSellingProductsParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	SaleDate   pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	SaleDate_2 pgtype.Timestamptz `db:"sale_date_2" json:"sale_date_2"`
	Limit      int32              `db:"limit" json:"limit"`
}

type GetTopSellingProductsRow struct {
	ProductName   string `db:"product_name" json:"product_name"`
	TotalQuantity int64  `db:"total_quantity" json:"total_quantity"`
}

func (q *Queries) GetTopSellingProducts(ctx context.Context, arg GetTopSellingProductsParams) ([]GetTopSellingProductsRow, error) {
	rows, err := q.db.Query(ctx, getTopSellingProducts,
		arg.StoreID,
		arg.SaleDate,
		arg.SaleDate_2,
		arg.Limit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopSellingProductsRow
	for rows.Next() {
		var i GetTopSellingProductsRow
		if err := rows.Scan(&i.ProductName, &i.TotalQuantity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTotalSales = `-- name: GetTotalSales :one
SELECT 
    COALESCE(SUM(total_amount), 0.0)::DECIMAL(12,2) as total_sales,
    COUNT(*) as sales_count
FROM sales
WHERE store_id = $1 AND sale_date BETWEEN $2 AND $3
`

type GetTotalSalesParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	SaleDate   pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	SaleDate_2 pgtype.Timestamptz `db:"sale_date_2" json:"sale_date_2"`
}

type GetTotalSalesRow struct {
	TotalSales pgtype.Numeric `db:"total_sales" json:"total_sales"`
	SalesCount int64          `db:"sales_count" json:"sales_count"`
}

func (q *Queries) GetTotalSales(ctx context.Context, arg GetTotalSalesParams) (GetTotalSalesRow, error) {
	row := q.db.QueryRow(ctx, getTotalSales, arg.StoreID, arg.SaleDate, arg.SaleDate_2)
	var i GetTotalSalesRow
	err := row.Scan(&i.TotalSales, &i.SalesCount)
	return i, err
}
