// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: returns.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createReturn = `-- name: CreateReturn :one
INSERT INTO returns (
    sale_id,
    store_id,
    refund_amount,
    refund_method
) VALUES (
    $1, $2, $3, $4
) RETURNING id, sale_id, store_id, refund_amount, refund_method, created_at
`

type CreateReturnParams struct {
	SaleID       pgtype.UUID    `db:"sale_id" json:"sale_id"`
	StoreID      pgtype.UUID    `db:"store_id" json:"store_id"`
	RefundAmount pgtype.Numeric `db:"refund_amount" json:"refund_amount"`
	RefundMethod string         `db:"refund_method" json:"refund_method"`
}

func (q *Queries) CreateReturn(ctx context.Context, arg CreateReturnParams) (Return, error) {
	row := q.db.QueryRow(ctx, createReturn,
		arg.SaleID,
		arg.StoreID,
		arg.RefundAmount,
		arg.RefundMethod,
	)
	var i Return
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.StoreID,
		&i.RefundAmount,
		&i.RefundMethod,
		&i.CreatedAt,
	)
	return i, err
}

const createReturnItem = `-- name: CreateReturnItem :one
INSERT INTO return_items (
    return_id,
    sale_item_id,
    quantity,
    reason,
    condition
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, return_id, sale_item_id, quantity, reason, condition
`

type CreateReturnItemParams struct {
	ReturnID   pgtype.UUID `db:"return_id" json:"return_id"`
	SaleItemID pgtype.UUID `db:"sale_item_id" json:"sale_item_id"`
	Quantity   int32       `db:"quantity" json:"quantity"`
	Reason     string      `db:"reason" json:"reason"`
	Condition  string      `db:"condition" json:"condition"`
}

func (q *Queries) CreateReturnItem(ctx context.Context, arg CreateReturnItemParams) (ReturnItem, error) {
	row := q.db.QueryRow(ctx, createReturnItem,
		arg.ReturnID,
		arg.SaleItemID,
		arg.Quantity,
		arg.Reason,
		arg.Condition,
	)
	var i ReturnItem
	err := row.Scan(
		&i.ID,
		&i.ReturnID,
		&i.SaleItemID,
		&i.Quantity,
		&i.Reason,
		&i.Condition,
	)
	return i, err
}

const getReturnItems = `-- name: GetReturnItems :many
SELECT ri.id, ri.return_id, ri.sale_item_id, ri.quantity, ri.reason, ri.condition,
       p.name AS product_name, pv.sku AS variant_sku
FROM return_items ri
JOIN sale_items si ON ri.sale_item_id = si.id
JOIN products p ON si.product_id = p.id
LEFT JOIN product_variants pv ON si.variant_id = pv.id
WHERE ri.return_id = $1
`

type GetReturnItemsRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	ReturnID    pgtype.UUID `db:"return_id" json:"return_id"`
	SaleItemID  pgtype.UUID `db:"sale_item_id" json:"sale_item_id"`
	Quantity    int32       `db:"quantity" json:"quantity"`
	Reason      string      `db:"reason" json:"reason"`
	Condition   string      `db:"condition" json:"condition"`
	ProductName string      `db:"product_name" json:"product_name"`
	VariantSku  pgtype.Text `db:"variant_sku" json:"variant_sku"`
}

func (q *Queries) GetReturnItems(ctx context.Context, returnID pgtype.UUID) ([]GetReturnItemsRow, error) {
	rows, err := q.db.Query(ctx, getReturnItems, returnID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReturnItemsRow
	for rows.Next() {
		var i GetReturnItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.ReturnID,
			&i.SaleItemID,
			&i.Quantity,
			&i.Reason,
			&i.Condition,
			&i.ProductName,
			&i.VariantSku,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listReturns = `-- name: ListReturns :many
SELECT r.id, r.sale_id, r.store_id, r.refund_amount, r.refund_method, r.created_at, 
       s.total_amount AS sale_total, c.name AS customer_name
FROM returns r
JOIN sales s ON r.sale_id = s.id
LEFT JOIN customers c ON s.customer_id = c.id
WHERE r.store_id = $1
ORDER BY r.created_at DESC
LIMIT $2 OFFSET $3
`

type ListReturnsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListReturnsRow struct {
	ID           pgtype.UUID        `db:"id" json:"id"`
	SaleID       pgtype.UUID        `db:"sale_id" json:"sale_id"`
	StoreID      pgtype.UUID        `db:"store_id" json:"store_id"`
	RefundAmount pgtype.Numeric     `db:"refund_amount" json:"refund_amount"`
	RefundMethod string             `db:"refund_method" json:"refund_method"`
	CreatedAt    pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SaleTotal    pgtype.Numeric     `db:"sale_total" json:"sale_total"`
	CustomerName pgtype.Text        `db:"customer_name" json:"customer_name"`
}

func (q *Queries) ListReturns(ctx context.Context, arg ListReturnsParams) ([]ListReturnsRow, error) {
	rows, err := q.db.Query(ctx, listReturns, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListReturnsRow
	for rows.Next() {
		var i ListReturnsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.StoreID,
			&i.RefundAmount,
			&i.RefundMethod,
			&i.CreatedAt,
			&i.SaleTotal,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
