// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sale.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (
    store_id,
    user_id,
    customer_id,
    sale_type,
    total_amount,
    discount_applied,
    tax_amount,
    final_amount,
    receipt_number,
    notes
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, store_id, user_id, customer_id, sale_type, total_amount, discount_applied, tax_amount, final_amount, sale_date, receipt_number, receipt_url, notes, created_at
`

type CreateSaleParams struct {
	StoreID         pgtype.UUID    `db:"store_id" json:"store_id"`
	UserID          pgtype.UUID    `db:"user_id" json:"user_id"`
	CustomerID      pgtype.UUID    `db:"customer_id" json:"customer_id"`
	SaleType        string         `db:"sale_type" json:"sale_type"`
	TotalAmount     pgtype.Numeric `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric `db:"discount_applied" json:"discount_applied"`
	TaxAmount       pgtype.Numeric `db:"tax_amount" json:"tax_amount"`
	FinalAmount     pgtype.Numeric `db:"final_amount" json:"final_amount"`
	ReceiptNumber   pgtype.Text    `db:"receipt_number" json:"receipt_number"`
	Notes           pgtype.Text    `db:"notes" json:"notes"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.StoreID,
		arg.UserID,
		arg.CustomerID,
		arg.SaleType,
		arg.TotalAmount,
		arg.DiscountApplied,
		arg.TaxAmount,
		arg.FinalAmount,
		arg.ReceiptNumber,
		arg.Notes,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.UserID,
		&i.CustomerID,
		&i.SaleType,
		&i.TotalAmount,
		&i.DiscountApplied,
		&i.TaxAmount,
		&i.FinalAmount,
		&i.SaleDate,
		&i.ReceiptNumber,
		&i.ReceiptUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one

INSERT INTO sale_items (
    sale_id,
    product_id,
    product_name,
    quantity,
    unit_price,
    subtotal,
    discount
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
) RETURNING id, sale_id, product_id, product_name, quantity, unit_price, subtotal, discount
`

type CreateSaleItemParams struct {
	SaleID      pgtype.UUID    `db:"sale_id" json:"sale_id"`
	ProductID   pgtype.UUID    `db:"product_id" json:"product_id"`
	ProductName string         `db:"product_name" json:"product_name"`
	Quantity    int32          `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric `db:"unit_price" json:"unit_price"`
	Subtotal    pgtype.Numeric `db:"subtotal" json:"subtotal"`
	Discount    pgtype.Numeric `db:"discount" json:"discount"`
}

// Sale Items queries
func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.ProductName,
		arg.Quantity,
		arg.UnitPrice,
		arg.Subtotal,
		arg.Discount,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.ProductName,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.Discount,
	)
	return i, err
}

const deleteSale = `-- name: DeleteSale :exec
DELETE FROM sales WHERE id = $1 AND store_id = $2
`

type DeleteSaleParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeleteSale(ctx context.Context, arg DeleteSaleParams) error {
	_, err := q.db.Exec(ctx, deleteSale, arg.ID, arg.StoreID)
	return err
}

const deleteSaleItem = `-- name: DeleteSaleItem :exec
DELETE FROM sale_items WHERE id = $1
`

func (q *Queries) DeleteSaleItem(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteSaleItem, id)
	return err
}

const getSaleById = `-- name: GetSaleById :one
SELECT s.id, s.store_id, s.user_id, s.customer_id, s.sale_type, s.total_amount, s.discount_applied, s.tax_amount, s.final_amount, s.sale_date, s.receipt_number, s.receipt_url, s.notes, s.created_at, 
       u.name as user_name,
       c.name as customer_name
FROM sales s
LEFT JOIN users u ON s.user_id = u.id
LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.id = $1 AND s.store_id = $2
`

type GetSaleByIdParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

type GetSaleByIdRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleType        string             `db:"sale_type" json:"sale_type"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric     `db:"discount_applied" json:"discount_applied"`
	TaxAmount       pgtype.Numeric     `db:"tax_amount" json:"tax_amount"`
	FinalAmount     pgtype.Numeric     `db:"final_amount" json:"final_amount"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	ReceiptNumber   pgtype.Text        `db:"receipt_number" json:"receipt_number"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UserName        pgtype.Text        `db:"user_name" json:"user_name"`
	CustomerName    pgtype.Text        `db:"customer_name" json:"customer_name"`
}

func (q *Queries) GetSaleById(ctx context.Context, arg GetSaleByIdParams) (GetSaleByIdRow, error) {
	row := q.db.QueryRow(ctx, getSaleById, arg.ID, arg.StoreID)
	var i GetSaleByIdRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.UserID,
		&i.CustomerID,
		&i.SaleType,
		&i.TotalAmount,
		&i.DiscountApplied,
		&i.TaxAmount,
		&i.FinalAmount,
		&i.SaleDate,
		&i.ReceiptNumber,
		&i.ReceiptUrl,
		&i.Notes,
		&i.CreatedAt,
		&i.UserName,
		&i.CustomerName,
	)
	return i, err
}

const getSaleItemById = `-- name: GetSaleItemById :one
SELECT id, sale_id, product_id, product_name, quantity, unit_price, subtotal, discount FROM sale_items WHERE id = $1
`

func (q *Queries) GetSaleItemById(ctx context.Context, id pgtype.UUID) (SaleItem, error) {
	row := q.db.QueryRow(ctx, getSaleItemById, id)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.ProductName,
		&i.Quantity,
		&i.UnitPrice,
		&i.Subtotal,
		&i.Discount,
	)
	return i, err
}

const getSaleItems = `-- name: GetSaleItems :many
SELECT si.id, si.sale_id, si.product_id, si.product_name, si.quantity, si.unit_price, si.subtotal, si.discount,
       p.code as product_code
FROM sale_items si
LEFT JOIN products p ON si.product_id = p.id
WHERE si.sale_id = $1
`

type GetSaleItemsRow struct {
	ID          pgtype.UUID    `db:"id" json:"id"`
	SaleID      pgtype.UUID    `db:"sale_id" json:"sale_id"`
	ProductID   pgtype.UUID    `db:"product_id" json:"product_id"`
	ProductName string         `db:"product_name" json:"product_name"`
	Quantity    int32          `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric `db:"unit_price" json:"unit_price"`
	Subtotal    pgtype.Numeric `db:"subtotal" json:"subtotal"`
	Discount    pgtype.Numeric `db:"discount" json:"discount"`
	ProductCode pgtype.Text    `db:"product_code" json:"product_code"`
}

func (q *Queries) GetSaleItems(ctx context.Context, saleID pgtype.UUID) ([]GetSaleItemsRow, error) {
	rows, err := q.db.Query(ctx, getSaleItems, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSaleItemsRow
	for rows.Next() {
		var i GetSaleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPrice,
			&i.Subtotal,
			&i.Discount,
			&i.ProductCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSalesTotalByDateRange = `-- name: GetSalesTotalByDateRange :one
SELECT 
    COUNT(*) as total_sales,
    COALESCE(SUM(final_amount), 0) as total_revenue
FROM sales
WHERE store_id = $1 
  AND sale_date >= $2 
  AND sale_date <= $3
`

type GetSalesTotalByDateRangeParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	SaleDate   pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	SaleDate_2 pgtype.Timestamptz `db:"sale_date_2" json:"sale_date_2"`
}

type GetSalesTotalByDateRangeRow struct {
	TotalSales   int64       `db:"total_sales" json:"total_sales"`
	TotalRevenue interface{} `db:"total_revenue" json:"total_revenue"`
}

func (q *Queries) GetSalesTotalByDateRange(ctx context.Context, arg GetSalesTotalByDateRangeParams) (GetSalesTotalByDateRangeRow, error) {
	row := q.db.QueryRow(ctx, getSalesTotalByDateRange, arg.StoreID, arg.SaleDate, arg.SaleDate_2)
	var i GetSalesTotalByDateRangeRow
	err := row.Scan(&i.TotalSales, &i.TotalRevenue)
	return i, err
}

const listSales = `-- name: ListSales :many
SELECT s.id, s.store_id, s.user_id, s.customer_id, s.sale_type, s.total_amount, s.discount_applied, s.tax_amount, s.final_amount, s.sale_date, s.receipt_number, s.receipt_url, s.notes, s.created_at,
       u.name as user_name,
       c.name as customer_name
FROM sales s
LEFT JOIN users u ON s.user_id = u.id
LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.store_id = $1
ORDER BY s.sale_date DESC
LIMIT $2 OFFSET $3
`

type ListSalesParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListSalesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleType        string             `db:"sale_type" json:"sale_type"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric     `db:"discount_applied" json:"discount_applied"`
	TaxAmount       pgtype.Numeric     `db:"tax_amount" json:"tax_amount"`
	FinalAmount     pgtype.Numeric     `db:"final_amount" json:"final_amount"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	ReceiptNumber   pgtype.Text        `db:"receipt_number" json:"receipt_number"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UserName        pgtype.Text        `db:"user_name" json:"user_name"`
	CustomerName    pgtype.Text        `db:"customer_name" json:"customer_name"`
}

func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesRow
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.UserID,
			&i.CustomerID,
			&i.SaleType,
			&i.TotalAmount,
			&i.DiscountApplied,
			&i.TaxAmount,
			&i.FinalAmount,
			&i.SaleDate,
			&i.ReceiptNumber,
			&i.ReceiptUrl,
			&i.Notes,
			&i.CreatedAt,
			&i.UserName,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesByCustomer = `-- name: ListSalesByCustomer :many
SELECT s.id, s.store_id, s.user_id, s.customer_id, s.sale_type, s.total_amount, s.discount_applied, s.tax_amount, s.final_amount, s.sale_date, s.receipt_number, s.receipt_url, s.notes, s.created_at,
       u.name as user_name
FROM sales s
LEFT JOIN users u ON s.user_id = u.id
WHERE s.customer_id = $1 AND s.store_id = $2
ORDER BY s.sale_date DESC
`

type ListSalesByCustomerParams struct {
	CustomerID pgtype.UUID `db:"customer_id" json:"customer_id"`
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
}

type ListSalesByCustomerRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleType        string             `db:"sale_type" json:"sale_type"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric     `db:"discount_applied" json:"discount_applied"`
	TaxAmount       pgtype.Numeric     `db:"tax_amount" json:"tax_amount"`
	FinalAmount     pgtype.Numeric     `db:"final_amount" json:"final_amount"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	ReceiptNumber   pgtype.Text        `db:"receipt_number" json:"receipt_number"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UserName        pgtype.Text        `db:"user_name" json:"user_name"`
}

func (q *Queries) ListSalesByCustomer(ctx context.Context, arg ListSalesByCustomerParams) ([]ListSalesByCustomerRow, error) {
	rows, err := q.db.Query(ctx, listSalesByCustomer, arg.CustomerID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesByCustomerRow
	for rows.Next() {
		var i ListSalesByCustomerRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.UserID,
			&i.CustomerID,
			&i.SaleType,
			&i.TotalAmount,
			&i.DiscountApplied,
			&i.TaxAmount,
			&i.FinalAmount,
			&i.SaleDate,
			&i.ReceiptNumber,
			&i.ReceiptUrl,
			&i.Notes,
			&i.CreatedAt,
			&i.UserName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSalesByDateRange = `-- name: ListSalesByDateRange :many
SELECT s.id, s.store_id, s.user_id, s.customer_id, s.sale_type, s.total_amount, s.discount_applied, s.tax_amount, s.final_amount, s.sale_date, s.receipt_number, s.receipt_url, s.notes, s.created_at,
       u.name as user_name,
       c.name as customer_name
FROM sales s
LEFT JOIN users u ON s.user_id = u.id
LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.store_id = $1 
  AND s.sale_date >= $2 
  AND s.sale_date <= $3
ORDER BY s.sale_date DESC
`

type ListSalesByDateRangeParams struct {
	StoreID    pgtype.UUID        `db:"store_id" json:"store_id"`
	SaleDate   pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	SaleDate_2 pgtype.Timestamptz `db:"sale_date_2" json:"sale_date_2"`
}

type ListSalesByDateRangeRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	UserID          pgtype.UUID        `db:"user_id" json:"user_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleType        string             `db:"sale_type" json:"sale_type"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric     `db:"discount_applied" json:"discount_applied"`
	TaxAmount       pgtype.Numeric     `db:"tax_amount" json:"tax_amount"`
	FinalAmount     pgtype.Numeric     `db:"final_amount" json:"final_amount"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	ReceiptNumber   pgtype.Text        `db:"receipt_number" json:"receipt_number"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	Notes           pgtype.Text        `db:"notes" json:"notes"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UserName        pgtype.Text        `db:"user_name" json:"user_name"`
	CustomerName    pgtype.Text        `db:"customer_name" json:"customer_name"`
}

func (q *Queries) ListSalesByDateRange(ctx context.Context, arg ListSalesByDateRangeParams) ([]ListSalesByDateRangeRow, error) {
	rows, err := q.db.Query(ctx, listSalesByDateRange, arg.StoreID, arg.SaleDate, arg.SaleDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesByDateRangeRow
	for rows.Next() {
		var i ListSalesByDateRangeRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.UserID,
			&i.CustomerID,
			&i.SaleType,
			&i.TotalAmount,
			&i.DiscountApplied,
			&i.TaxAmount,
			&i.FinalAmount,
			&i.SaleDate,
			&i.ReceiptNumber,
			&i.ReceiptUrl,
			&i.Notes,
			&i.CreatedAt,
			&i.UserName,
			&i.CustomerName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSale = `-- name: UpdateSale :one
UPDATE sales SET
    receipt_url = COALESCE($1, receipt_url),
    notes = COALESCE($2, notes)
WHERE id = $3 AND store_id = $4
RETURNING id, store_id, user_id, customer_id, sale_type, total_amount, discount_applied, tax_amount, final_amount, sale_date, receipt_number, receipt_url, notes, created_at
`

type UpdateSaleParams struct {
	ReceiptUrl pgtype.Text `db:"receipt_url" json:"receipt_url"`
	Notes      pgtype.Text `db:"notes" json:"notes"`
	ID         pgtype.UUID `db:"id" json:"id"`
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateSale(ctx context.Context, arg UpdateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, updateSale,
		arg.ReceiptUrl,
		arg.Notes,
		arg.ID,
		arg.StoreID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.UserID,
		&i.CustomerID,
		&i.SaleType,
		&i.TotalAmount,
		&i.DiscountApplied,
		&i.TaxAmount,
		&i.FinalAmount,
		&i.SaleDate,
		&i.ReceiptNumber,
		&i.ReceiptUrl,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}
