// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (
    sales_type,
    total_amount,
    discount_applied,
    receipt_url,
    store_id,
    customer_id,
    sale_date
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, sales_type, total_amount, discount_applied, receipt_url, sale_date, store_id, customer_id
`

type CreateSaleParams struct {
	SalesType       SalesTypes         `db:"sales_type" json:"sales_type"`
	TotalAmount     pgtype.Numeric     `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric     `db:"discount_applied" json:"discount_applied"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.SalesType,
		arg.TotalAmount,
		arg.DiscountApplied,
		arg.ReceiptUrl,
		arg.StoreID,
		arg.CustomerID,
		arg.SaleDate,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.SalesType,
		&i.TotalAmount,
		&i.DiscountApplied,
		&i.ReceiptUrl,
		&i.SaleDate,
		&i.StoreID,
		&i.CustomerID,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (
    sale_id,
    product_id,
    quantity,
    unit_price,
    total_price
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, sale_id, product_id, quantity, unit_price, total_price
`

type CreateSaleItemParams struct {
	SaleID     pgtype.UUID    `db:"sale_id" json:"sale_id"`
	ProductID  pgtype.UUID    `db:"product_id" json:"product_id"`
	Quantity   int32          `db:"quantity" json:"quantity"`
	UnitPrice  pgtype.Numeric `db:"unit_price" json:"unit_price"`
	TotalPrice pgtype.Numeric `db:"total_price" json:"total_price"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
	)
	return i, err
}

const getSale = `-- name: GetSale :one
SELECT 
    s.id, s.sales_type, s.total_amount::float as total_amount, s.discount_applied::float as discount_applied, s.receipt_url, s.sale_date, s.store_id, s.customer_id,
    c.name as customer_name,
    c.phone as customer_phone
FROM sales s
LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.id = $1 AND s.store_id = $2
`

type GetSaleParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

type GetSaleRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SalesType       SalesTypes         `db:"sales_type" json:"sales_type"`
	TotalAmount     float64            `db:"total_amount" json:"total_amount"`
	DiscountApplied float64            `db:"discount_applied" json:"discount_applied"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	CustomerName    pgtype.Text        `db:"customer_name" json:"customer_name"`
	CustomerPhone   pgtype.Text        `db:"customer_phone" json:"customer_phone"`
}

func (q *Queries) GetSale(ctx context.Context, arg GetSaleParams) (GetSaleRow, error) {
	row := q.db.QueryRow(ctx, getSale, arg.ID, arg.StoreID)
	var i GetSaleRow
	err := row.Scan(
		&i.ID,
		&i.SalesType,
		&i.TotalAmount,
		&i.DiscountApplied,
		&i.ReceiptUrl,
		&i.SaleDate,
		&i.StoreID,
		&i.CustomerID,
		&i.CustomerName,
		&i.CustomerPhone,
	)
	return i, err
}

const getSaleItems = `-- name: GetSaleItems :many
SELECT si.id, si.sale_id, si.product_id, si.quantity, si.unit_price::float as unit_price, si.total_price::float as total_price, p.name as product_name
FROM sale_items si
JOIN products p ON si.product_id = p.id
WHERE si.sale_id = $1
`

type GetSaleItemsRow struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	SaleID      pgtype.UUID `db:"sale_id" json:"sale_id"`
	ProductID   pgtype.UUID `db:"product_id" json:"product_id"`
	Quantity    int32       `db:"quantity" json:"quantity"`
	UnitPrice   float64     `db:"unit_price" json:"unit_price"`
	TotalPrice  float64     `db:"total_price" json:"total_price"`
	ProductName string      `db:"product_name" json:"product_name"`
}

func (q *Queries) GetSaleItems(ctx context.Context, saleID pgtype.UUID) ([]GetSaleItemsRow, error) {
	rows, err := q.db.Query(ctx, getSaleItems, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSaleItemsRow
	for rows.Next() {
		var i GetSaleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT 
    s.id, s.sales_type, s.total_amount::float as total_amount, s.discount_applied::float as discount_applied, s.receipt_url, s.sale_date, s.store_id, s.customer_id,
    c.name as customer_name,
    c.phone as customer_phone
FROM sales s
LEFT JOIN customers c ON s.customer_id = c.id
WHERE s.store_id = $1
ORDER BY s.sale_date DESC
`

type ListSalesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	SalesType       SalesTypes         `db:"sales_type" json:"sales_type"`
	TotalAmount     float64            `db:"total_amount" json:"total_amount"`
	DiscountApplied float64            `db:"discount_applied" json:"discount_applied"`
	ReceiptUrl      pgtype.Text        `db:"receipt_url" json:"receipt_url"`
	SaleDate        pgtype.Timestamptz `db:"sale_date" json:"sale_date"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID        `db:"customer_id" json:"customer_id"`
	CustomerName    pgtype.Text        `db:"customer_name" json:"customer_name"`
	CustomerPhone   pgtype.Text        `db:"customer_phone" json:"customer_phone"`
}

func (q *Queries) ListSales(ctx context.Context, storeID pgtype.UUID) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSalesRow
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.SalesType,
			&i.TotalAmount,
			&i.DiscountApplied,
			&i.ReceiptUrl,
			&i.SaleDate,
			&i.StoreID,
			&i.CustomerID,
			&i.CustomerName,
			&i.CustomerPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSaleAmount = `-- name: UpdateSaleAmount :exec
UPDATE sales
SET total_amount = $1
WHERE id = $2
`

type UpdateSaleAmountParams struct {
	TotalAmount pgtype.Numeric `db:"total_amount" json:"total_amount"`
	ID          pgtype.UUID    `db:"id" json:"id"`
}

func (q *Queries) UpdateSaleAmount(ctx context.Context, arg UpdateSaleAmountParams) error {
	_, err := q.db.Exec(ctx, updateSaleAmount, arg.TotalAmount, arg.ID)
	return err
}
