// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sales.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSale = `-- name: CreateSale :one
INSERT INTO sales (
    sales_type,
    total_amount,
    discount_applied,
    receipt_url,
    store_id,
    customer_id
) VALUES (
    $1, $2, $3, $4, $5, $6
)
RETURNING id, sales_type, total_amount, discount_applied, receipt_url, sale_date, store_id, customer_id
`

type CreateSaleParams struct {
	SalesType       SalesTypes     `db:"sales_type" json:"sales_type"`
	TotalAmount     pgtype.Numeric `db:"total_amount" json:"total_amount"`
	DiscountApplied pgtype.Numeric `db:"discount_applied" json:"discount_applied"`
	ReceiptUrl      pgtype.Text    `db:"receipt_url" json:"receipt_url"`
	StoreID         pgtype.UUID    `db:"store_id" json:"store_id"`
	CustomerID      pgtype.UUID    `db:"customer_id" json:"customer_id"`
}

func (q *Queries) CreateSale(ctx context.Context, arg CreateSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, createSale,
		arg.SalesType,
		arg.TotalAmount,
		arg.DiscountApplied,
		arg.ReceiptUrl,
		arg.StoreID,
		arg.CustomerID,
	)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.SalesType,
		&i.TotalAmount,
		&i.DiscountApplied,
		&i.ReceiptUrl,
		&i.SaleDate,
		&i.StoreID,
		&i.CustomerID,
	)
	return i, err
}

const createSaleItem = `-- name: CreateSaleItem :one
INSERT INTO sale_items (
    sale_id,
    product_id,
    quantity,
    unit_price,
    total_price
) VALUES (
    $1, $2, $3, $4, $5
)
RETURNING id, sale_id, product_id, quantity, unit_price, total_price
`

type CreateSaleItemParams struct {
	SaleID     pgtype.UUID    `db:"sale_id" json:"sale_id"`
	ProductID  pgtype.UUID    `db:"product_id" json:"product_id"`
	Quantity   int32          `db:"quantity" json:"quantity"`
	UnitPrice  pgtype.Numeric `db:"unit_price" json:"unit_price"`
	TotalPrice pgtype.Numeric `db:"total_price" json:"total_price"`
}

func (q *Queries) CreateSaleItem(ctx context.Context, arg CreateSaleItemParams) (SaleItem, error) {
	row := q.db.QueryRow(ctx, createSaleItem,
		arg.SaleID,
		arg.ProductID,
		arg.Quantity,
		arg.UnitPrice,
		arg.TotalPrice,
	)
	var i SaleItem
	err := row.Scan(
		&i.ID,
		&i.SaleID,
		&i.ProductID,
		&i.Quantity,
		&i.UnitPrice,
		&i.TotalPrice,
	)
	return i, err
}

const getSale = `-- name: GetSale :one
SELECT id, sales_type, total_amount, discount_applied, receipt_url, sale_date, store_id, customer_id FROM sales
WHERE id = $1 AND store_id = $2
`

type GetSaleParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) GetSale(ctx context.Context, arg GetSaleParams) (Sale, error) {
	row := q.db.QueryRow(ctx, getSale, arg.ID, arg.StoreID)
	var i Sale
	err := row.Scan(
		&i.ID,
		&i.SalesType,
		&i.TotalAmount,
		&i.DiscountApplied,
		&i.ReceiptUrl,
		&i.SaleDate,
		&i.StoreID,
		&i.CustomerID,
	)
	return i, err
}

const getSaleItems = `-- name: GetSaleItems :many
SELECT si.id, si.sale_id, si.product_id, si.quantity, si.unit_price, si.total_price, p.name as product_name
FROM sale_items si
JOIN products p ON si.product_id = p.id
WHERE si.sale_id = $1
`

type GetSaleItemsRow struct {
	ID          pgtype.UUID    `db:"id" json:"id"`
	SaleID      pgtype.UUID    `db:"sale_id" json:"sale_id"`
	ProductID   pgtype.UUID    `db:"product_id" json:"product_id"`
	Quantity    int32          `db:"quantity" json:"quantity"`
	UnitPrice   pgtype.Numeric `db:"unit_price" json:"unit_price"`
	TotalPrice  pgtype.Numeric `db:"total_price" json:"total_price"`
	ProductName string         `db:"product_name" json:"product_name"`
}

func (q *Queries) GetSaleItems(ctx context.Context, saleID pgtype.UUID) ([]GetSaleItemsRow, error) {
	rows, err := q.db.Query(ctx, getSaleItems, saleID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSaleItemsRow
	for rows.Next() {
		var i GetSaleItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.SaleID,
			&i.ProductID,
			&i.Quantity,
			&i.UnitPrice,
			&i.TotalPrice,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSales = `-- name: ListSales :many
SELECT id, sales_type, total_amount, discount_applied, receipt_url, sale_date, store_id, customer_id FROM sales
WHERE store_id = $1
ORDER BY sale_date DESC
`

func (q *Queries) ListSales(ctx context.Context, storeID pgtype.UUID) ([]Sale, error) {
	rows, err := q.db.Query(ctx, listSales, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Sale
	for rows.Next() {
		var i Sale
		if err := rows.Scan(
			&i.ID,
			&i.SalesType,
			&i.TotalAmount,
			&i.DiscountApplied,
			&i.ReceiptUrl,
			&i.SaleDate,
			&i.StoreID,
			&i.CustomerID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
