// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock_adjustments.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStockAdjustment = `-- name: CreateStockAdjustment :one
INSERT INTO stock_adjustments (
    store_id, product_id, variant_id, adjustment_quantity,
    previous_quantity, new_quantity, reason, notes, adjusted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, store_id, product_id, variant_id, adjustment_quantity, previous_quantity, new_quantity, reason, notes, adjusted_by, created_at
`

type CreateStockAdjustmentParams struct {
	StoreID            pgtype.UUID           `db:"store_id" json:"store_id"`
	ProductID          pgtype.UUID           `db:"product_id" json:"product_id"`
	VariantID          pgtype.UUID           `db:"variant_id" json:"variant_id"`
	AdjustmentQuantity int32                 `db:"adjustment_quantity" json:"adjustment_quantity"`
	PreviousQuantity   int32                 `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity        int32                 `db:"new_quantity" json:"new_quantity"`
	Reason             StockAdjustmentReason `db:"reason" json:"reason"`
	Notes              pgtype.Text           `db:"notes" json:"notes"`
	AdjustedBy         pgtype.UUID           `db:"adjusted_by" json:"adjusted_by"`
}

func (q *Queries) CreateStockAdjustment(ctx context.Context, arg CreateStockAdjustmentParams) (StockAdjustment, error) {
	row := q.db.QueryRow(ctx, createStockAdjustment,
		arg.StoreID,
		arg.ProductID,
		arg.VariantID,
		arg.AdjustmentQuantity,
		arg.PreviousQuantity,
		arg.NewQuantity,
		arg.Reason,
		arg.Notes,
		arg.AdjustedBy,
	)
	var i StockAdjustment
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ProductID,
		&i.VariantID,
		&i.AdjustmentQuantity,
		&i.PreviousQuantity,
		&i.NewQuantity,
		&i.Reason,
		&i.Notes,
		&i.AdjustedBy,
		&i.CreatedAt,
	)
	return i, err
}

const createStockMovement = `-- name: CreateStockMovement :one
INSERT INTO stock_movements (
    store_id, product_id, variant_id, movement_type,
    quantity_change, reference_id, reference_type, notes
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, store_id, product_id, variant_id, movement_type, quantity_change, reference_id, reference_type, notes, created_at
`

type CreateStockMovementParams struct {
	StoreID        pgtype.UUID            `db:"store_id" json:"store_id"`
	ProductID      pgtype.UUID            `db:"product_id" json:"product_id"`
	VariantID      pgtype.UUID            `db:"variant_id" json:"variant_id"`
	MovementType   StockMovementType      `db:"movement_type" json:"movement_type"`
	QuantityChange int32                  `db:"quantity_change" json:"quantity_change"`
	ReferenceID    pgtype.UUID            `db:"reference_id" json:"reference_id"`
	ReferenceType  NullStockReferenceType `db:"reference_type" json:"reference_type"`
	Notes          pgtype.Text            `db:"notes" json:"notes"`
}

func (q *Queries) CreateStockMovement(ctx context.Context, arg CreateStockMovementParams) (StockMovement, error) {
	row := q.db.QueryRow(ctx, createStockMovement,
		arg.StoreID,
		arg.ProductID,
		arg.VariantID,
		arg.MovementType,
		arg.QuantityChange,
		arg.ReferenceID,
		arg.ReferenceType,
		arg.Notes,
	)
	var i StockMovement
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.ProductID,
		&i.VariantID,
		&i.MovementType,
		&i.QuantityChange,
		&i.ReferenceID,
		&i.ReferenceType,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const getStockAdjustmentsByProduct = `-- name: GetStockAdjustmentsByProduct :many
SELECT sa.id, sa.store_id, sa.product_id, sa.variant_id, sa.adjustment_quantity, sa.previous_quantity, sa.new_quantity, sa.reason, sa.notes, sa.adjusted_by, sa.created_at, p.name as product_name
FROM stock_adjustments sa
JOIN products p ON sa.product_id = p.id
WHERE sa.store_id = $1 AND sa.product_id = $2
ORDER BY sa.created_at DESC
`

type GetStockAdjustmentsByProductParams struct {
	StoreID   pgtype.UUID `db:"store_id" json:"store_id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
}

type GetStockAdjustmentsByProductRow struct {
	ID                 pgtype.UUID           `db:"id" json:"id"`
	StoreID            pgtype.UUID           `db:"store_id" json:"store_id"`
	ProductID          pgtype.UUID           `db:"product_id" json:"product_id"`
	VariantID          pgtype.UUID           `db:"variant_id" json:"variant_id"`
	AdjustmentQuantity int32                 `db:"adjustment_quantity" json:"adjustment_quantity"`
	PreviousQuantity   int32                 `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity        int32                 `db:"new_quantity" json:"new_quantity"`
	Reason             StockAdjustmentReason `db:"reason" json:"reason"`
	Notes              pgtype.Text           `db:"notes" json:"notes"`
	AdjustedBy         pgtype.UUID           `db:"adjusted_by" json:"adjusted_by"`
	CreatedAt          pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	ProductName        string                `db:"product_name" json:"product_name"`
}

func (q *Queries) GetStockAdjustmentsByProduct(ctx context.Context, arg GetStockAdjustmentsByProductParams) ([]GetStockAdjustmentsByProductRow, error) {
	rows, err := q.db.Query(ctx, getStockAdjustmentsByProduct, arg.StoreID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStockAdjustmentsByProductRow
	for rows.Next() {
		var i GetStockAdjustmentsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ProductID,
			&i.VariantID,
			&i.AdjustmentQuantity,
			&i.PreviousQuantity,
			&i.NewQuantity,
			&i.Reason,
			&i.Notes,
			&i.AdjustedBy,
			&i.CreatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStockMovementSummary = `-- name: GetStockMovementSummary :one
SELECT
    product_id,
    p.name as product_name,
    SUM(CASE WHEN quantity_change > 0 THEN quantity_change ELSE 0 END)::INT as total_inbound,
    SUM(CASE WHEN quantity_change < 0 THEN ABS(quantity_change) ELSE 0 END)::INT as total_outbound,
    COUNT(*) as movement_count
FROM stock_movements sm
JOIN products p ON sm.product_id = p.id
WHERE sm.store_id = $1 AND sm.product_id = $2
GROUP BY product_id, p.name
`

type GetStockMovementSummaryParams struct {
	StoreID   pgtype.UUID `db:"store_id" json:"store_id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
}

type GetStockMovementSummaryRow struct {
	ProductID     pgtype.UUID `db:"product_id" json:"product_id"`
	ProductName   string      `db:"product_name" json:"product_name"`
	TotalInbound  int32       `db:"total_inbound" json:"total_inbound"`
	TotalOutbound int32       `db:"total_outbound" json:"total_outbound"`
	MovementCount int64       `db:"movement_count" json:"movement_count"`
}

func (q *Queries) GetStockMovementSummary(ctx context.Context, arg GetStockMovementSummaryParams) (GetStockMovementSummaryRow, error) {
	row := q.db.QueryRow(ctx, getStockMovementSummary, arg.StoreID, arg.ProductID)
	var i GetStockMovementSummaryRow
	err := row.Scan(
		&i.ProductID,
		&i.ProductName,
		&i.TotalInbound,
		&i.TotalOutbound,
		&i.MovementCount,
	)
	return i, err
}

const getStockMovementsByProduct = `-- name: GetStockMovementsByProduct :many
SELECT sm.id, sm.store_id, sm.product_id, sm.variant_id, sm.movement_type, sm.quantity_change, sm.reference_id, sm.reference_type, sm.notes, sm.created_at, p.name as product_name
FROM stock_movements sm
JOIN products p ON sm.product_id = p.id
WHERE sm.store_id = $1 AND sm.product_id = $2
ORDER BY sm.created_at DESC
`

type GetStockMovementsByProductParams struct {
	StoreID   pgtype.UUID `db:"store_id" json:"store_id"`
	ProductID pgtype.UUID `db:"product_id" json:"product_id"`
}

type GetStockMovementsByProductRow struct {
	ID             pgtype.UUID            `db:"id" json:"id"`
	StoreID        pgtype.UUID            `db:"store_id" json:"store_id"`
	ProductID      pgtype.UUID            `db:"product_id" json:"product_id"`
	VariantID      pgtype.UUID            `db:"variant_id" json:"variant_id"`
	MovementType   StockMovementType      `db:"movement_type" json:"movement_type"`
	QuantityChange int32                  `db:"quantity_change" json:"quantity_change"`
	ReferenceID    pgtype.UUID            `db:"reference_id" json:"reference_id"`
	ReferenceType  NullStockReferenceType `db:"reference_type" json:"reference_type"`
	Notes          pgtype.Text            `db:"notes" json:"notes"`
	CreatedAt      pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	ProductName    string                 `db:"product_name" json:"product_name"`
}

func (q *Queries) GetStockMovementsByProduct(ctx context.Context, arg GetStockMovementsByProductParams) ([]GetStockMovementsByProductRow, error) {
	rows, err := q.db.Query(ctx, getStockMovementsByProduct, arg.StoreID, arg.ProductID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStockMovementsByProductRow
	for rows.Next() {
		var i GetStockMovementsByProductRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ProductID,
			&i.VariantID,
			&i.MovementType,
			&i.QuantityChange,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Notes,
			&i.CreatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockAdjustments = `-- name: ListStockAdjustments :many
SELECT sa.id, sa.store_id, sa.product_id, sa.variant_id, sa.adjustment_quantity, sa.previous_quantity, sa.new_quantity, sa.reason, sa.notes, sa.adjusted_by, sa.created_at, p.name as product_name
FROM stock_adjustments sa
JOIN products p ON sa.product_id = p.id
WHERE sa.store_id = $1
ORDER BY sa.created_at DESC
LIMIT $2 OFFSET $3
`

type ListStockAdjustmentsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListStockAdjustmentsRow struct {
	ID                 pgtype.UUID           `db:"id" json:"id"`
	StoreID            pgtype.UUID           `db:"store_id" json:"store_id"`
	ProductID          pgtype.UUID           `db:"product_id" json:"product_id"`
	VariantID          pgtype.UUID           `db:"variant_id" json:"variant_id"`
	AdjustmentQuantity int32                 `db:"adjustment_quantity" json:"adjustment_quantity"`
	PreviousQuantity   int32                 `db:"previous_quantity" json:"previous_quantity"`
	NewQuantity        int32                 `db:"new_quantity" json:"new_quantity"`
	Reason             StockAdjustmentReason `db:"reason" json:"reason"`
	Notes              pgtype.Text           `db:"notes" json:"notes"`
	AdjustedBy         pgtype.UUID           `db:"adjusted_by" json:"adjusted_by"`
	CreatedAt          pgtype.Timestamptz    `db:"created_at" json:"created_at"`
	ProductName        string                `db:"product_name" json:"product_name"`
}

func (q *Queries) ListStockAdjustments(ctx context.Context, arg ListStockAdjustmentsParams) ([]ListStockAdjustmentsRow, error) {
	rows, err := q.db.Query(ctx, listStockAdjustments, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockAdjustmentsRow
	for rows.Next() {
		var i ListStockAdjustmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ProductID,
			&i.VariantID,
			&i.AdjustmentQuantity,
			&i.PreviousQuantity,
			&i.NewQuantity,
			&i.Reason,
			&i.Notes,
			&i.AdjustedBy,
			&i.CreatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovements = `-- name: ListStockMovements :many
SELECT sm.id, sm.store_id, sm.product_id, sm.variant_id, sm.movement_type, sm.quantity_change, sm.reference_id, sm.reference_type, sm.notes, sm.created_at, p.name as product_name
FROM stock_movements sm
JOIN products p ON sm.product_id = p.id
WHERE sm.store_id = $1
ORDER BY sm.created_at DESC
LIMIT $2 OFFSET $3
`

type ListStockMovementsParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Limit   int32       `db:"limit" json:"limit"`
	Offset  int32       `db:"offset" json:"offset"`
}

type ListStockMovementsRow struct {
	ID             pgtype.UUID            `db:"id" json:"id"`
	StoreID        pgtype.UUID            `db:"store_id" json:"store_id"`
	ProductID      pgtype.UUID            `db:"product_id" json:"product_id"`
	VariantID      pgtype.UUID            `db:"variant_id" json:"variant_id"`
	MovementType   StockMovementType      `db:"movement_type" json:"movement_type"`
	QuantityChange int32                  `db:"quantity_change" json:"quantity_change"`
	ReferenceID    pgtype.UUID            `db:"reference_id" json:"reference_id"`
	ReferenceType  NullStockReferenceType `db:"reference_type" json:"reference_type"`
	Notes          pgtype.Text            `db:"notes" json:"notes"`
	CreatedAt      pgtype.Timestamptz     `db:"created_at" json:"created_at"`
	ProductName    string                 `db:"product_name" json:"product_name"`
}

func (q *Queries) ListStockMovements(ctx context.Context, arg ListStockMovementsParams) ([]ListStockMovementsRow, error) {
	rows, err := q.db.Query(ctx, listStockMovements, arg.StoreID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStockMovementsRow
	for rows.Next() {
		var i ListStockMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.ProductID,
			&i.VariantID,
			&i.MovementType,
			&i.QuantityChange,
			&i.ReferenceID,
			&i.ReferenceType,
			&i.Notes,
			&i.CreatedAt,
			&i.ProductName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
