// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: store.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStore = `-- name: CreateStore :one
INSERT INTO stores (
    owner_id,
    name,
    slug,
    business_type,
    description,
    address,
    phone,
    email,
    currency,
    timezone
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8, $9, $10
) RETURNING id, owner_id, name, slug, business_type, description, address, phone, email, tax_id, logo_url, currency, timezone, is_active, subscription_plan, subscription_expires_at, created_at, updated_at
`

type CreateStoreParams struct {
	OwnerID      pgtype.UUID `db:"owner_id" json:"owner_id"`
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	BusinessType pgtype.Text `db:"business_type" json:"business_type"`
	Description  pgtype.Text `db:"description" json:"description"`
	Address      pgtype.Text `db:"address" json:"address"`
	Phone        pgtype.Text `db:"phone" json:"phone"`
	Email        pgtype.Text `db:"email" json:"email"`
	Currency     pgtype.Text `db:"currency" json:"currency"`
	Timezone     pgtype.Text `db:"timezone" json:"timezone"`
}

func (q *Queries) CreateStore(ctx context.Context, arg CreateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, createStore,
		arg.OwnerID,
		arg.Name,
		arg.Slug,
		arg.BusinessType,
		arg.Description,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.Currency,
		arg.Timezone,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.Description,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.LogoUrl,
		&i.Currency,
		&i.Timezone,
		&i.IsActive,
		&i.SubscriptionPlan,
		&i.SubscriptionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStore = `-- name: DeleteStore :one
UPDATE stores SET is_active = false, updated_at = NOW()
WHERE id = $1
RETURNING id, owner_id, name, slug, business_type, description, address, phone, email, tax_id, logo_url, currency, timezone, is_active, subscription_plan, subscription_expires_at, created_at, updated_at
`

func (q *Queries) DeleteStore(ctx context.Context, id pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, deleteStore, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.Description,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.LogoUrl,
		&i.Currency,
		&i.Timezone,
		&i.IsActive,
		&i.SubscriptionPlan,
		&i.SubscriptionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreById = `-- name: GetStoreById :one
SELECT id, owner_id, name, slug, business_type, description, address, phone, email, tax_id, logo_url, currency, timezone, is_active, subscription_plan, subscription_expires_at, created_at, updated_at FROM stores WHERE id = $1
`

func (q *Queries) GetStoreById(ctx context.Context, id pgtype.UUID) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreById, id)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.Description,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.LogoUrl,
		&i.Currency,
		&i.Timezone,
		&i.IsActive,
		&i.SubscriptionPlan,
		&i.SubscriptionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreBySlug = `-- name: GetStoreBySlug :one
SELECT id, owner_id, name, slug, business_type, description, address, phone, email, tax_id, logo_url, currency, timezone, is_active, subscription_plan, subscription_expires_at, created_at, updated_at FROM stores WHERE slug = $1
`

func (q *Queries) GetStoreBySlug(ctx context.Context, slug string) (Store, error) {
	row := q.db.QueryRow(ctx, getStoreBySlug, slug)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.Description,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.LogoUrl,
		&i.Currency,
		&i.Timezone,
		&i.IsActive,
		&i.SubscriptionPlan,
		&i.SubscriptionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoresByOwner = `-- name: GetStoresByOwner :many
SELECT id, owner_id, name, slug, business_type, description, address, phone, email, tax_id, logo_url, currency, timezone, is_active, subscription_plan, subscription_expires_at, created_at, updated_at FROM stores 
WHERE owner_id = $1 AND is_active = true
ORDER BY created_at DESC
`

func (q *Queries) GetStoresByOwner(ctx context.Context, ownerID pgtype.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, getStoresByOwner, ownerID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.BusinessType,
			&i.Description,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.TaxID,
			&i.LogoUrl,
			&i.Currency,
			&i.Timezone,
			&i.IsActive,
			&i.SubscriptionPlan,
			&i.SubscriptionExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserStores = `-- name: GetUserStores :many
SELECT s.id, s.owner_id, s.name, s.slug, s.business_type, s.description, s.address, s.phone, s.email, s.tax_id, s.logo_url, s.currency, s.timezone, s.is_active, s.subscription_plan, s.subscription_expires_at, s.created_at, s.updated_at FROM stores s
JOIN store_users su ON s.id = su.store_id
WHERE su.user_id = $1 AND su.is_active = true AND s.is_active = true
ORDER BY s.created_at DESC
`

func (q *Queries) GetUserStores(ctx context.Context, userID pgtype.UUID) ([]Store, error) {
	rows, err := q.db.Query(ctx, getUserStores, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Store
	for rows.Next() {
		var i Store
		if err := rows.Scan(
			&i.ID,
			&i.OwnerID,
			&i.Name,
			&i.Slug,
			&i.BusinessType,
			&i.Description,
			&i.Address,
			&i.Phone,
			&i.Email,
			&i.TaxID,
			&i.LogoUrl,
			&i.Currency,
			&i.Timezone,
			&i.IsActive,
			&i.SubscriptionPlan,
			&i.SubscriptionExpiresAt,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteStore = `-- name: HardDeleteStore :exec
DELETE FROM stores WHERE id = $1
`

func (q *Queries) HardDeleteStore(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteStore, id)
	return err
}

const updateStore = `-- name: UpdateStore :one
UPDATE stores SET
    name = COALESCE($1, name),
    business_type = COALESCE($2, business_type),
    description = COALESCE($3, description),
    address = COALESCE($4, address),
    phone = COALESCE($5, phone),
    email = COALESCE($6, email),
    logo_url = COALESCE($7, logo_url),
    currency = COALESCE($8, currency),
    timezone = COALESCE($9, timezone),
    is_active = COALESCE($10, is_active),
    subscription_plan = COALESCE($11, subscription_plan),
    subscription_expires_at = COALESCE($12, subscription_expires_at),
    updated_at = NOW()
WHERE id = $13
RETURNING id, owner_id, name, slug, business_type, description, address, phone, email, tax_id, logo_url, currency, timezone, is_active, subscription_plan, subscription_expires_at, created_at, updated_at
`

type UpdateStoreParams struct {
	Name                  pgtype.Text        `db:"name" json:"name"`
	BusinessType          pgtype.Text        `db:"business_type" json:"business_type"`
	Description           pgtype.Text        `db:"description" json:"description"`
	Address               pgtype.Text        `db:"address" json:"address"`
	Phone                 pgtype.Text        `db:"phone" json:"phone"`
	Email                 pgtype.Text        `db:"email" json:"email"`
	LogoUrl               pgtype.Text        `db:"logo_url" json:"logo_url"`
	Currency              pgtype.Text        `db:"currency" json:"currency"`
	Timezone              pgtype.Text        `db:"timezone" json:"timezone"`
	IsActive              pgtype.Bool        `db:"is_active" json:"is_active"`
	SubscriptionPlan      pgtype.Text        `db:"subscription_plan" json:"subscription_plan"`
	SubscriptionExpiresAt pgtype.Timestamptz `db:"subscription_expires_at" json:"subscription_expires_at"`
	ID                    pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdateStore(ctx context.Context, arg UpdateStoreParams) (Store, error) {
	row := q.db.QueryRow(ctx, updateStore,
		arg.Name,
		arg.BusinessType,
		arg.Description,
		arg.Address,
		arg.Phone,
		arg.Email,
		arg.LogoUrl,
		arg.Currency,
		arg.Timezone,
		arg.IsActive,
		arg.SubscriptionPlan,
		arg.SubscriptionExpiresAt,
		arg.ID,
	)
	var i Store
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Slug,
		&i.BusinessType,
		&i.Description,
		&i.Address,
		&i.Phone,
		&i.Email,
		&i.TaxID,
		&i.LogoUrl,
		&i.Currency,
		&i.Timezone,
		&i.IsActive,
		&i.SubscriptionPlan,
		&i.SubscriptionExpiresAt,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
