// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_info.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreInfo = `-- name: CreateStoreInfo :one
INSERT INTO store_info (
  name,
  address,
  currency_code,
  owner_id
) VALUES (
  $1, $2, $3, $4
) RETURNING id, name, address, currency_code, owner_id, created_at, updated_at
`

type CreateStoreInfoParams struct {
	Name         string      `db:"name" json:"name"`
	Address      string      `db:"address" json:"address"`
	CurrencyCode string      `db:"currency_code" json:"currency_code"`
	OwnerID      pgtype.UUID `db:"owner_id" json:"owner_id"`
}

func (q *Queries) CreateStoreInfo(ctx context.Context, arg CreateStoreInfoParams) (StoreInfo, error) {
	row := q.db.QueryRow(ctx, createStoreInfo,
		arg.Name,
		arg.Address,
		arg.CurrencyCode,
		arg.OwnerID,
	)
	var i StoreInfo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CurrencyCode,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStoreInfo = `-- name: DeleteStoreInfo :exec
DELETE FROM store_info
WHERE id = $1
`

func (q *Queries) DeleteStoreInfo(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStoreInfo, id)
	return err
}

const getAllStores = `-- name: GetAllStores :many
SELECT id, name, address, currency_code, owner_id, created_at, updated_at FROM store_info
`

func (q *Queries) GetAllStores(ctx context.Context) ([]StoreInfo, error) {
	rows, err := q.db.Query(ctx, getAllStores)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreInfo
	for rows.Next() {
		var i StoreInfo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CurrencyCode,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStoreInfo = `-- name: GetStoreInfo :one
SELECT id, name, address, currency_code, owner_id, created_at, updated_at FROM store_info
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStoreInfo(ctx context.Context, id pgtype.UUID) (StoreInfo, error) {
	row := q.db.QueryRow(ctx, getStoreInfo, id)
	var i StoreInfo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CurrencyCode,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreInfoByOwner = `-- name: GetStoreInfoByOwner :one
SELECT id, name, address, currency_code, owner_id, created_at, updated_at FROM store_info
WHERE owner_id = $1 LIMIT 1
`

func (q *Queries) GetStoreInfoByOwner(ctx context.Context, ownerID pgtype.UUID) (StoreInfo, error) {
	row := q.db.QueryRow(ctx, getStoreInfoByOwner, ownerID)
	var i StoreInfo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CurrencyCode,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreWithOwner = `-- name: GetStoreWithOwner :one
SELECT 
  store_info.id, store_info.name, store_info.address, store_info.currency_code, store_info.owner_id, store_info.created_at, store_info.updated_at,
  store_owner.id, store_owner.name, store_owner.email, store_owner.password, store_owner.emailverified, store_owner.phone, store_owner.role, store_owner.profile_picture, store_owner.created_at, store_owner.updated_at
FROM store_info
INNER JOIN store_owner ON store_info.owner_id = store_owner.id
WHERE store_info.id = $1
`

type GetStoreWithOwnerRow struct {
	StoreInfo  StoreInfo  `db:"store_info" json:"store_info"`
	StoreOwner StoreOwner `db:"store_owner" json:"store_owner"`
}

func (q *Queries) GetStoreWithOwner(ctx context.Context, id pgtype.UUID) (GetStoreWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, getStoreWithOwner, id)
	var i GetStoreWithOwnerRow
	err := row.Scan(
		&i.StoreInfo.ID,
		&i.StoreInfo.Name,
		&i.StoreInfo.Address,
		&i.StoreInfo.CurrencyCode,
		&i.StoreInfo.OwnerID,
		&i.StoreInfo.CreatedAt,
		&i.StoreInfo.UpdatedAt,
		&i.StoreOwner.ID,
		&i.StoreOwner.Name,
		&i.StoreOwner.Email,
		&i.StoreOwner.Password,
		&i.StoreOwner.Emailverified,
		&i.StoreOwner.Phone,
		&i.StoreOwner.Role,
		&i.StoreOwner.ProfilePicture,
		&i.StoreOwner.CreatedAt,
		&i.StoreOwner.UpdatedAt,
	)
	return i, err
}

const listStoreInfo = `-- name: ListStoreInfo :many
SELECT id, name, address, currency_code, owner_id, created_at, updated_at FROM store_info
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListStoreInfoParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListStoreInfo(ctx context.Context, arg ListStoreInfoParams) ([]StoreInfo, error) {
	rows, err := q.db.Query(ctx, listStoreInfo, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreInfo
	for rows.Next() {
		var i StoreInfo
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.CurrencyCode,
			&i.OwnerID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateStoreInfo = `-- name: UpdateStoreInfo :one
UPDATE store_info
SET
  name = COALESCE($1, name),
  address = COALESCE($2, address),
  currency_code = COALESCE($3, currency_code),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $4
RETURNING id, name, address, currency_code, owner_id, created_at, updated_at
`

type UpdateStoreInfoParams struct {
	Name         pgtype.Text `db:"name" json:"name"`
	Address      pgtype.Text `db:"address" json:"address"`
	CurrencyCode pgtype.Text `db:"currency_code" json:"currency_code"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateStoreInfo(ctx context.Context, arg UpdateStoreInfoParams) (StoreInfo, error) {
	row := q.db.QueryRow(ctx, updateStoreInfo,
		arg.Name,
		arg.Address,
		arg.CurrencyCode,
		arg.ID,
	)
	var i StoreInfo
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.CurrencyCode,
		&i.OwnerID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
