// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: store_owner.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createStoreOwner = `-- name: CreateStoreOwner :one
INSERT INTO store_owner (
  name,
  email,
  password,
  phone,
  role,
  profile_picture
) VALUES (
  $1, $2, $3, $4, $5, $6
) RETURNING id, name, email, password, emailverified, phone, role, profile_picture, created_at, updated_at
`

type CreateStoreOwnerParams struct {
	Name           string `db:"name" json:"name"`
	Email          string `db:"email" json:"email"`
	Password       string `db:"password" json:"password"`
	Phone          string `db:"phone" json:"phone"`
	Role           string `db:"role" json:"role"`
	ProfilePicture string `db:"profile_picture" json:"profile_picture"`
}

func (q *Queries) CreateStoreOwner(ctx context.Context, arg CreateStoreOwnerParams) (StoreOwner, error) {
	row := q.db.QueryRow(ctx, createStoreOwner,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Role,
		arg.ProfilePicture,
	)
	var i StoreOwner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Emailverified,
		&i.Phone,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteStoreOwner = `-- name: DeleteStoreOwner :exec
DELETE FROM store_owner
WHERE id = $1
`

func (q *Queries) DeleteStoreOwner(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStoreOwner, id)
	return err
}

const getStoreOwner = `-- name: GetStoreOwner :one
SELECT id, name, email, password, emailverified, phone, role, profile_picture, created_at, updated_at FROM store_owner
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStoreOwner(ctx context.Context, id pgtype.UUID) (StoreOwner, error) {
	row := q.db.QueryRow(ctx, getStoreOwner, id)
	var i StoreOwner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Emailverified,
		&i.Phone,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreOwnerByEmail = `-- name: GetStoreOwnerByEmail :one
SELECT id, name, email, password, emailverified, phone, role, profile_picture, created_at, updated_at FROM store_owner
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetStoreOwnerByEmail(ctx context.Context, email string) (StoreOwner, error) {
	row := q.db.QueryRow(ctx, getStoreOwnerByEmail, email)
	var i StoreOwner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Emailverified,
		&i.Phone,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getStoreOwnerById = `-- name: GetStoreOwnerById :one
SELECT id, name, email, password, emailverified, phone, role, profile_picture, created_at, updated_at FROM store_owner
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetStoreOwnerById(ctx context.Context, id pgtype.UUID) (StoreOwner, error) {
	row := q.db.QueryRow(ctx, getStoreOwnerById, id)
	var i StoreOwner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Emailverified,
		&i.Phone,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listStoreOwners = `-- name: ListStoreOwners :many
SELECT id, name, email, password, emailverified, phone, role, profile_picture, created_at, updated_at FROM store_owner
ORDER BY created_at DESC
LIMIT $1
OFFSET $2
`

type ListStoreOwnersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListStoreOwners(ctx context.Context, arg ListStoreOwnersParams) ([]StoreOwner, error) {
	rows, err := q.db.Query(ctx, listStoreOwners, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StoreOwner
	for rows.Next() {
		var i StoreOwner
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Emailverified,
			&i.Phone,
			&i.Role,
			&i.ProfilePicture,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateEmailVerification = `-- name: UpdateEmailVerification :exec
UPDATE store_owner
SET
  emailVerified = true
WHERE email = $1
`

func (q *Queries) UpdateEmailVerification(ctx context.Context, email string) error {
	_, err := q.db.Exec(ctx, updateEmailVerification, email)
	return err
}

const updatePasswordByEmail = `-- name: UpdatePasswordByEmail :exec
UPDATE store_owner
SET
  password = $2,
  updated_at = CURRENT_TIMESTAMP
WHERE email = $1
`

type UpdatePasswordByEmailParams struct {
	Email    string `db:"email" json:"email"`
	Password string `db:"password" json:"password"`
}

func (q *Queries) UpdatePasswordByEmail(ctx context.Context, arg UpdatePasswordByEmailParams) error {
	_, err := q.db.Exec(ctx, updatePasswordByEmail, arg.Email, arg.Password)
	return err
}

const updateStoreOwner = `-- name: UpdateStoreOwner :one
UPDATE store_owner
SET
  name = COALESCE($1, name),
  email = COALESCE($2, email),
  password = COALESCE($3, password),
  phone = COALESCE($4, phone),
  role = COALESCE($5, role),
  profile_picture = COALESCE($6, profile_picture),
  updated_at = CURRENT_TIMESTAMP
WHERE id = $7
RETURNING id, name, email, password, emailverified, phone, role, profile_picture, created_at, updated_at
`

type UpdateStoreOwnerParams struct {
	Name           pgtype.Text `db:"name" json:"name"`
	Email          pgtype.Text `db:"email" json:"email"`
	Password       pgtype.Text `db:"password" json:"password"`
	Phone          pgtype.Text `db:"phone" json:"phone"`
	Role           pgtype.Text `db:"role" json:"role"`
	ProfilePicture pgtype.Text `db:"profile_picture" json:"profile_picture"`
	ID             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateStoreOwner(ctx context.Context, arg UpdateStoreOwnerParams) (StoreOwner, error) {
	row := q.db.QueryRow(ctx, updateStoreOwner,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Role,
		arg.ProfilePicture,
		arg.ID,
	)
	var i StoreOwner
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Emailverified,
		&i.Phone,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
