// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: supplier_payables.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSupplierPayable = `-- name: CreateSupplierPayable :one
INSERT INTO supplier_payables (store_id, supplier_id, description, amount_owed, amount_paid, due_date, status)
VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, store_id, supplier_id, description, amount_owed, amount_paid, due_date, status, purchase_order_id, created_at, updated_at
`

type CreateSupplierPayableParams struct {
	StoreID     pgtype.UUID        `db:"store_id" json:"store_id"`
	SupplierID  pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Description pgtype.Text        `db:"description" json:"description"`
	AmountOwed  pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid  pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	Status      string             `db:"status" json:"status"`
}

func (q *Queries) CreateSupplierPayable(ctx context.Context, arg CreateSupplierPayableParams) (SupplierPayable, error) {
	row := q.db.QueryRow(ctx, createSupplierPayable,
		arg.StoreID,
		arg.SupplierID,
		arg.Description,
		arg.AmountOwed,
		arg.AmountPaid,
		arg.DueDate,
		arg.Status,
	)
	var i SupplierPayable
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SupplierID,
		&i.Description,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.DueDate,
		&i.Status,
		&i.PurchaseOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSupplierPayable = `-- name: DeleteSupplierPayable :exec
DELETE FROM supplier_payables
WHERE id = $1 AND store_id = $2
`

type DeleteSupplierPayableParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeleteSupplierPayable(ctx context.Context, arg DeleteSupplierPayableParams) error {
	_, err := q.db.Exec(ctx, deleteSupplierPayable, arg.ID, arg.StoreID)
	return err
}

const getDailySupplierPayments = `-- name: GetDailySupplierPayments :many
SELECT 
    DATE(payment_date)::VARCHAR as payment_date,
    COALESCE(SUM(amount), 0)::DECIMAL(12,2) as daily_total
FROM supplier_payments
WHERE store_id = $1 AND payment_date BETWEEN $2 AND $3
GROUP BY DATE(payment_date)
ORDER BY DATE(payment_date)
`

type GetDailySupplierPaymentsParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	PaymentDate   pgtype.Timestamptz `db:"payment_date" json:"payment_date"`
	PaymentDate_2 pgtype.Timestamptz `db:"payment_date_2" json:"payment_date_2"`
}

type GetDailySupplierPaymentsRow struct {
	PaymentDate string         `db:"payment_date" json:"payment_date"`
	DailyTotal  pgtype.Numeric `db:"daily_total" json:"daily_total"`
}

func (q *Queries) GetDailySupplierPayments(ctx context.Context, arg GetDailySupplierPaymentsParams) ([]GetDailySupplierPaymentsRow, error) {
	rows, err := q.db.Query(ctx, getDailySupplierPayments, arg.StoreID, arg.PaymentDate, arg.PaymentDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetDailySupplierPaymentsRow
	for rows.Next() {
		var i GetDailySupplierPaymentsRow
		if err := rows.Scan(&i.PaymentDate, &i.DailyTotal); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOverduePayables = `-- name: GetOverduePayables :many
SELECT 
    sp.id, sp.store_id, sp.supplier_id, sp.description, sp.amount_owed, sp.amount_paid, sp.due_date, sp.status, sp.purchase_order_id, sp.created_at, sp.updated_at,
    s.name as supplier_name
FROM supplier_payables sp
JOIN suppliers s ON sp.supplier_id = s.id
WHERE sp.store_id = $1 
  AND sp.status != 'paid'
  AND sp.due_date < NOW()
ORDER BY sp.due_date ASC
`

type GetOverduePayablesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	SupplierID      pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Description     pgtype.Text        `db:"description" json:"description"`
	AmountOwed      pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid      pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	DueDate         pgtype.Timestamptz `db:"due_date" json:"due_date"`
	Status          string             `db:"status" json:"status"`
	PurchaseOrderID pgtype.UUID        `db:"purchase_order_id" json:"purchase_order_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SupplierName    pgtype.Text        `db:"supplier_name" json:"supplier_name"`
}

func (q *Queries) GetOverduePayables(ctx context.Context, storeID pgtype.UUID) ([]GetOverduePayablesRow, error) {
	rows, err := q.db.Query(ctx, getOverduePayables, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetOverduePayablesRow
	for rows.Next() {
		var i GetOverduePayablesRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.SupplierID,
			&i.Description,
			&i.AmountOwed,
			&i.AmountPaid,
			&i.DueDate,
			&i.Status,
			&i.PurchaseOrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplierPayable = `-- name: GetSupplierPayable :one
SELECT 
    sp.id, sp.store_id, sp.supplier_id, sp.description, sp.amount_owed, sp.amount_paid, sp.due_date, sp.status, sp.purchase_order_id, sp.created_at, sp.updated_at,
    s.name as supplier_name,
    s.phone_number as supplier_phone
FROM supplier_payables sp
JOIN suppliers s ON sp.supplier_id = s.id
WHERE sp.id = $1 AND sp.store_id = $2
`

type GetSupplierPayableParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

type GetSupplierPayableRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	SupplierID      pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Description     pgtype.Text        `db:"description" json:"description"`
	AmountOwed      pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid      pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	DueDate         pgtype.Timestamptz `db:"due_date" json:"due_date"`
	Status          string             `db:"status" json:"status"`
	PurchaseOrderID pgtype.UUID        `db:"purchase_order_id" json:"purchase_order_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SupplierName    pgtype.Text        `db:"supplier_name" json:"supplier_name"`
	SupplierPhone   pgtype.Text        `db:"supplier_phone" json:"supplier_phone"`
}

func (q *Queries) GetSupplierPayable(ctx context.Context, arg GetSupplierPayableParams) (GetSupplierPayableRow, error) {
	row := q.db.QueryRow(ctx, getSupplierPayable, arg.ID, arg.StoreID)
	var i GetSupplierPayableRow
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SupplierID,
		&i.Description,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.DueDate,
		&i.Status,
		&i.PurchaseOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.SupplierName,
		&i.SupplierPhone,
	)
	return i, err
}

const getSupplierPayableSummary = `-- name: GetSupplierPayableSummary :one
SELECT 
    COUNT(*) as total_count,
    COALESCE(SUM(amount_owed - amount_paid), 0)::DECIMAL(12,2) as total_outstanding,
    COALESCE(SUM(CASE WHEN status = 'overdue' THEN (amount_owed - amount_paid) ELSE 0 END), 0)::DECIMAL(12,2) as total_overdue,
    COALESCE(SUM(CASE WHEN due_date BETWEEN NOW() AND NOW() + INTERVAL '7 days' AND status != 'paid' THEN (amount_owed - amount_paid) ELSE 0 END), 0)::DECIMAL(12,2) as due_this_week
FROM supplier_payables
WHERE store_id = $1 AND status != 'paid'
`

type GetSupplierPayableSummaryRow struct {
	TotalCount       int64          `db:"total_count" json:"total_count"`
	TotalOutstanding pgtype.Numeric `db:"total_outstanding" json:"total_outstanding"`
	TotalOverdue     pgtype.Numeric `db:"total_overdue" json:"total_overdue"`
	DueThisWeek      pgtype.Numeric `db:"due_this_week" json:"due_this_week"`
}

func (q *Queries) GetSupplierPayableSummary(ctx context.Context, storeID pgtype.UUID) (GetSupplierPayableSummaryRow, error) {
	row := q.db.QueryRow(ctx, getSupplierPayableSummary, storeID)
	var i GetSupplierPayableSummaryRow
	err := row.Scan(
		&i.TotalCount,
		&i.TotalOutstanding,
		&i.TotalOverdue,
		&i.DueThisWeek,
	)
	return i, err
}

const getSupplierTotalPayable = `-- name: GetSupplierTotalPayable :one
SELECT 
    COALESCE(SUM(amount_owed - amount_paid), 0)::DECIMAL(12,2) as total_outstanding
FROM supplier_payables
WHERE supplier_id = $1 AND store_id = $2 AND status != 'paid'
`

type GetSupplierTotalPayableParams struct {
	SupplierID pgtype.UUID `db:"supplier_id" json:"supplier_id"`
	StoreID    pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) GetSupplierTotalPayable(ctx context.Context, arg GetSupplierTotalPayableParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getSupplierTotalPayable, arg.SupplierID, arg.StoreID)
	var total_outstanding pgtype.Numeric
	err := row.Scan(&total_outstanding)
	return total_outstanding, err
}

const getTotalSupplierPaymentsForPeriod = `-- name: GetTotalSupplierPaymentsForPeriod :one
SELECT 
    COALESCE(SUM(amount), 0)::DECIMAL(12,2) as total_payments
FROM supplier_payments
WHERE store_id = $1 AND payment_date BETWEEN $2 AND $3
`

type GetTotalSupplierPaymentsForPeriodParams struct {
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	PaymentDate   pgtype.Timestamptz `db:"payment_date" json:"payment_date"`
	PaymentDate_2 pgtype.Timestamptz `db:"payment_date_2" json:"payment_date_2"`
}

func (q *Queries) GetTotalSupplierPaymentsForPeriod(ctx context.Context, arg GetTotalSupplierPaymentsForPeriodParams) (pgtype.Numeric, error) {
	row := q.db.QueryRow(ctx, getTotalSupplierPaymentsForPeriod, arg.StoreID, arg.PaymentDate, arg.PaymentDate_2)
	var total_payments pgtype.Numeric
	err := row.Scan(&total_payments)
	return total_payments, err
}

const listPaymentsByPayable = `-- name: ListPaymentsByPayable :many
SELECT id, store_id, payable_id, amount, payment_method, payment_date, notes, created_at FROM supplier_payments
WHERE payable_id = $1 AND store_id = $2
ORDER BY payment_date DESC
`

type ListPaymentsByPayableParams struct {
	PayableID pgtype.UUID `db:"payable_id" json:"payable_id"`
	StoreID   pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) ListPaymentsByPayable(ctx context.Context, arg ListPaymentsByPayableParams) ([]SupplierPayment, error) {
	rows, err := q.db.Query(ctx, listPaymentsByPayable, arg.PayableID, arg.StoreID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SupplierPayment
	for rows.Next() {
		var i SupplierPayment
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.PayableID,
			&i.Amount,
			&i.PaymentMethod,
			&i.PaymentDate,
			&i.Notes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSupplierPayables = `-- name: ListSupplierPayables :many
SELECT 
    sp.id, sp.store_id, sp.supplier_id, sp.description, sp.amount_owed, sp.amount_paid, sp.due_date, sp.status, sp.purchase_order_id, sp.created_at, sp.updated_at,
    s.name as supplier_name,
    s.phone_number as supplier_phone
FROM supplier_payables sp
JOIN suppliers s ON sp.supplier_id = s.id
WHERE sp.store_id = $1
  AND ($2::TEXT = '' OR sp.status = $2)
ORDER BY 
    CASE sp.status 
        WHEN 'overdue' THEN 1 
        WHEN 'pending' THEN 2 
        WHEN 'partial' THEN 3 
        ELSE 4 
    END,
    sp.due_date ASC
`

type ListSupplierPayablesParams struct {
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
	Column2 string      `db:"column_2" json:"column_2"`
}

type ListSupplierPayablesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	StoreID         pgtype.UUID        `db:"store_id" json:"store_id"`
	SupplierID      pgtype.UUID        `db:"supplier_id" json:"supplier_id"`
	Description     pgtype.Text        `db:"description" json:"description"`
	AmountOwed      pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	AmountPaid      pgtype.Numeric     `db:"amount_paid" json:"amount_paid"`
	DueDate         pgtype.Timestamptz `db:"due_date" json:"due_date"`
	Status          string             `db:"status" json:"status"`
	PurchaseOrderID pgtype.UUID        `db:"purchase_order_id" json:"purchase_order_id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	SupplierName    pgtype.Text        `db:"supplier_name" json:"supplier_name"`
	SupplierPhone   pgtype.Text        `db:"supplier_phone" json:"supplier_phone"`
}

func (q *Queries) ListSupplierPayables(ctx context.Context, arg ListSupplierPayablesParams) ([]ListSupplierPayablesRow, error) {
	rows, err := q.db.Query(ctx, listSupplierPayables, arg.StoreID, arg.Column2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSupplierPayablesRow
	for rows.Next() {
		var i ListSupplierPayablesRow
		if err := rows.Scan(
			&i.ID,
			&i.StoreID,
			&i.SupplierID,
			&i.Description,
			&i.AmountOwed,
			&i.AmountPaid,
			&i.DueDate,
			&i.Status,
			&i.PurchaseOrderID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.SupplierName,
			&i.SupplierPhone,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const recordSupplierPayment = `-- name: RecordSupplierPayment :one
INSERT INTO supplier_payments (store_id, payable_id, amount, payment_method, notes)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, store_id, payable_id, amount, payment_method, payment_date, notes, created_at
`

type RecordSupplierPaymentParams struct {
	StoreID       pgtype.UUID    `db:"store_id" json:"store_id"`
	PayableID     pgtype.UUID    `db:"payable_id" json:"payable_id"`
	Amount        pgtype.Numeric `db:"amount" json:"amount"`
	PaymentMethod pgtype.Text    `db:"payment_method" json:"payment_method"`
	Notes         pgtype.Text    `db:"notes" json:"notes"`
}

func (q *Queries) RecordSupplierPayment(ctx context.Context, arg RecordSupplierPaymentParams) (SupplierPayment, error) {
	row := q.db.QueryRow(ctx, recordSupplierPayment,
		arg.StoreID,
		arg.PayableID,
		arg.Amount,
		arg.PaymentMethod,
		arg.Notes,
	)
	var i SupplierPayment
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.PayableID,
		&i.Amount,
		&i.PaymentMethod,
		&i.PaymentDate,
		&i.Notes,
		&i.CreatedAt,
	)
	return i, err
}

const updatePayableAfterPayment = `-- name: UpdatePayableAfterPayment :one
UPDATE supplier_payables
SET amount_paid = $2, status = $3, updated_at = NOW()
WHERE id = $1 AND store_id = $4
RETURNING id, store_id, supplier_id, description, amount_owed, amount_paid, due_date, status, purchase_order_id, created_at, updated_at
`

type UpdatePayableAfterPaymentParams struct {
	ID         pgtype.UUID    `db:"id" json:"id"`
	AmountPaid pgtype.Numeric `db:"amount_paid" json:"amount_paid"`
	Status     string         `db:"status" json:"status"`
	StoreID    pgtype.UUID    `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdatePayableAfterPayment(ctx context.Context, arg UpdatePayableAfterPaymentParams) (SupplierPayable, error) {
	row := q.db.QueryRow(ctx, updatePayableAfterPayment,
		arg.ID,
		arg.AmountPaid,
		arg.Status,
		arg.StoreID,
	)
	var i SupplierPayable
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SupplierID,
		&i.Description,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.DueDate,
		&i.Status,
		&i.PurchaseOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSupplierPayable = `-- name: UpdateSupplierPayable :one
UPDATE supplier_payables
SET description = $2, amount_owed = $3, due_date = $4, status = $5, updated_at = NOW()
WHERE id = $1 AND store_id = $6
RETURNING id, store_id, supplier_id, description, amount_owed, amount_paid, due_date, status, purchase_order_id, created_at, updated_at
`

type UpdateSupplierPayableParams struct {
	ID          pgtype.UUID        `db:"id" json:"id"`
	Description pgtype.Text        `db:"description" json:"description"`
	AmountOwed  pgtype.Numeric     `db:"amount_owed" json:"amount_owed"`
	DueDate     pgtype.Timestamptz `db:"due_date" json:"due_date"`
	Status      string             `db:"status" json:"status"`
	StoreID     pgtype.UUID        `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateSupplierPayable(ctx context.Context, arg UpdateSupplierPayableParams) (SupplierPayable, error) {
	row := q.db.QueryRow(ctx, updateSupplierPayable,
		arg.ID,
		arg.Description,
		arg.AmountOwed,
		arg.DueDate,
		arg.Status,
		arg.StoreID,
	)
	var i SupplierPayable
	err := row.Scan(
		&i.ID,
		&i.StoreID,
		&i.SupplierID,
		&i.Description,
		&i.AmountOwed,
		&i.AmountPaid,
		&i.DueDate,
		&i.Status,
		&i.PurchaseOrderID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
