// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: supplier.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSupplier = `-- name: CreateSupplier :one
INSERT INTO suppliers (
    name,
    slug,
    contact_phone,
    contact_email,
    address
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, name, contact_phone, contact_email, address, is_active, created_at, updated_at, slug, store_id
`

type CreateSupplierParams struct {
	Name         string      `db:"name" json:"name"`
	Slug         string      `db:"slug" json:"slug"`
	ContactPhone pgtype.Text `db:"contact_phone" json:"contact_phone"`
	ContactEmail pgtype.Text `db:"contact_email" json:"contact_email"`
	Address      pgtype.Text `db:"address" json:"address"`
}

func (q *Queries) CreateSupplier(ctx context.Context, arg CreateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSupplier,
		arg.Name,
		arg.Slug,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.Address,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :one
UPDATE suppliers
SET is_active = false, updated_at = NOW()
WHERE id = $1
RETURNING id, name, contact_phone, contact_email, address, is_active, created_at, updated_at, slug, store_id
`

func (q *Queries) DeleteSupplier(ctx context.Context, id pgtype.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, deleteSupplier, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}

const getSupplierById = `-- name: GetSupplierById :one
SELECT id, name, contact_phone, contact_email, address, is_active, created_at, updated_at, slug, store_id FROM suppliers WHERE id = $1
`

func (q *Queries) GetSupplierById(ctx context.Context, id pgtype.UUID) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierById, id)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}

const getSupplierBySlug = `-- name: GetSupplierBySlug :one
SELECT id, name, contact_phone, contact_email, address, is_active, created_at, updated_at, slug, store_id FROM suppliers WHERE slug = $1
`

func (q *Queries) GetSupplierBySlug(ctx context.Context, slug string) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplierBySlug, slug)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}

const getSupplierProducts = `-- name: GetSupplierProducts :many
SELECT p.id, p.name, p.code, p.category_id, p.supplier_id, p.price, p.market_price, p.stock_quantity, p.low_stock_threshold, p.is_perishable, p.unit_of_measure, p.status, p.is_active, p.created_at, p.updated_at, p.slug, p.store_id FROM products p
WHERE p.supplier_id = $1 AND p.is_active = true
ORDER BY p.name
`

func (q *Queries) GetSupplierProducts(ctx context.Context, supplierID pgtype.UUID) ([]Product, error) {
	rows, err := q.db.Query(ctx, getSupplierProducts, supplierID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Product
	for rows.Next() {
		var i Product
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Code,
			&i.CategoryID,
			&i.SupplierID,
			&i.Price,
			&i.MarketPrice,
			&i.StockQuantity,
			&i.LowStockThreshold,
			&i.IsPerishable,
			&i.UnitOfMeasure,
			&i.Status,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const hardDeleteSupplier = `-- name: HardDeleteSupplier :exec
DELETE FROM suppliers WHERE id = $1
`

func (q *Queries) HardDeleteSupplier(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, hardDeleteSupplier, id)
	return err
}

const listSuppliers = `-- name: ListSuppliers :many
SELECT id, name, contact_phone, contact_email, address, is_active, created_at, updated_at, slug, store_id FROM suppliers 
WHERE is_active = true
ORDER BY name
LIMIT $1 OFFSET $2
`

type ListSuppliersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListSuppliers(ctx context.Context, arg ListSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, listSuppliers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSuppliers = `-- name: SearchSuppliers :many
SELECT id, name, contact_phone, contact_email, address, is_active, created_at, updated_at, slug, store_id FROM suppliers
WHERE LOWER(name) LIKE LOWER($1) AND is_active = true
ORDER BY name
LIMIT $2 OFFSET $3
`

type SearchSuppliersParams struct {
	Lower  string `db:"lower" json:"lower"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

func (q *Queries) SearchSuppliers(ctx context.Context, arg SearchSuppliersParams) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, searchSuppliers, arg.Lower, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ContactPhone,
			&i.ContactEmail,
			&i.Address,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Slug,
			&i.StoreID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET
    name = COALESCE($1, name),
    slug = COALESCE($2, slug),
    contact_phone = COALESCE($3, contact_phone),
    contact_email = COALESCE($4, contact_email),
    address = COALESCE($5, address),
    is_active = COALESCE($6, is_active),
    updated_at = NOW()
WHERE id = $7
RETURNING id, name, contact_phone, contact_email, address, is_active, created_at, updated_at, slug, store_id
`

type UpdateSupplierParams struct {
	Name         pgtype.Text `db:"name" json:"name"`
	Slug         pgtype.Text `db:"slug" json:"slug"`
	ContactPhone pgtype.Text `db:"contact_phone" json:"contact_phone"`
	ContactEmail pgtype.Text `db:"contact_email" json:"contact_email"`
	Address      pgtype.Text `db:"address" json:"address"`
	IsActive     pgtype.Bool `db:"is_active" json:"is_active"`
	ID           pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.Name,
		arg.Slug,
		arg.ContactPhone,
		arg.ContactEmail,
		arg.Address,
		arg.IsActive,
		arg.ID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.ContactPhone,
		&i.ContactEmail,
		&i.Address,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Slug,
		&i.StoreID,
	)
	return i, err
}
