// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSuppliers = `-- name: CreateSuppliers :one
INSERT INTO suppliers (
  name,
  address,
  phone_number,
  email,
  store_id
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, address, phone_number, email, store_id, created_at, updated_at
`

type CreateSuppliersParams struct {
	Name        pgtype.Text `db:"name" json:"name"`
	Address     pgtype.Text `db:"address" json:"address"`
	PhoneNumber pgtype.Text `db:"phone_number" json:"phone_number"`
	Email       pgtype.Text `db:"email" json:"email"`
	StoreID     pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) CreateSuppliers(ctx context.Context, arg CreateSuppliersParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSuppliers,
		arg.Name,
		arg.Address,
		arg.PhoneNumber,
		arg.Email,
		arg.StoreID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PhoneNumber,
		&i.Email,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getAllSuppliers = `-- name: GetAllSuppliers :many
SELECT id, name, address, phone_number, email, store_id, created_at, updated_at FROM suppliers WHERE store_id = $1
`

func (q *Queries) GetAllSuppliers(ctx context.Context, storeID pgtype.UUID) ([]Supplier, error) {
	rows, err := q.db.Query(ctx, getAllSuppliers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Supplier
	for rows.Next() {
		var i Supplier
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.PhoneNumber,
			&i.Email,
			&i.StoreID,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
