// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: suppliers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSuppliers = `-- name: CreateSuppliers :one
INSERT INTO suppliers (
  name,
  address,
  phone_number,
  email,
  store_id
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, address, phone_number, email, store_id, created_at, updated_at
`

type CreateSuppliersParams struct {
	Name        pgtype.Text `db:"name" json:"name"`
	Address     pgtype.Text `db:"address" json:"address"`
	PhoneNumber pgtype.Text `db:"phone_number" json:"phone_number"`
	Email       pgtype.Text `db:"email" json:"email"`
	StoreID     pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) CreateSuppliers(ctx context.Context, arg CreateSuppliersParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, createSuppliers,
		arg.Name,
		arg.Address,
		arg.PhoneNumber,
		arg.Email,
		arg.StoreID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PhoneNumber,
		&i.Email,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteSupplier = `-- name: DeleteSupplier :exec
DELETE FROM suppliers WHERE id = $1 AND store_id = $2
`

type DeleteSupplierParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) DeleteSupplier(ctx context.Context, arg DeleteSupplierParams) error {
	_, err := q.db.Exec(ctx, deleteSupplier, arg.ID, arg.StoreID)
	return err
}

const getAllSuppliers = `-- name: GetAllSuppliers :many
SELECT 
    s.id, s.name, s.address, s.phone_number, s.email, s.store_id, s.created_at, s.updated_at,
    COUNT(p.id) as product_count,
    COUNT(p.id) FILTER (WHERE p.stock_quantity <= p.low_stock_threshold) as low_stock_count
FROM suppliers s
LEFT JOIN products p ON s.id = p.supplier_id AND p.status != 'discontinued'
WHERE s.store_id = $1
GROUP BY s.id
ORDER BY s.created_at DESC
`

type GetAllSuppliersRow struct {
	ID            pgtype.UUID        `db:"id" json:"id"`
	Name          pgtype.Text        `db:"name" json:"name"`
	Address       pgtype.Text        `db:"address" json:"address"`
	PhoneNumber   pgtype.Text        `db:"phone_number" json:"phone_number"`
	Email         pgtype.Text        `db:"email" json:"email"`
	StoreID       pgtype.UUID        `db:"store_id" json:"store_id"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	ProductCount  int64              `db:"product_count" json:"product_count"`
	LowStockCount int64              `db:"low_stock_count" json:"low_stock_count"`
}

func (q *Queries) GetAllSuppliers(ctx context.Context, storeID pgtype.UUID) ([]GetAllSuppliersRow, error) {
	rows, err := q.db.Query(ctx, getAllSuppliers, storeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllSuppliersRow
	for rows.Next() {
		var i GetAllSuppliersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Address,
			&i.PhoneNumber,
			&i.Email,
			&i.StoreID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.ProductCount,
			&i.LowStockCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSupplier = `-- name: GetSupplier :one
SELECT id, name, address, phone_number, email, store_id, created_at, updated_at FROM suppliers WHERE id = $1 AND store_id = $2
`

type GetSupplierParams struct {
	ID      pgtype.UUID `db:"id" json:"id"`
	StoreID pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) GetSupplier(ctx context.Context, arg GetSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, getSupplier, arg.ID, arg.StoreID)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PhoneNumber,
		&i.Email,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const updateSupplier = `-- name: UpdateSupplier :one
UPDATE suppliers
SET 
  name = COALESCE($2, name),
  address = COALESCE($3, address),
  phone_number = COALESCE($4, phone_number),
  email = COALESCE($5, email)
WHERE id = $1 AND store_id = $6
RETURNING id, name, address, phone_number, email, store_id, created_at, updated_at
`

type UpdateSupplierParams struct {
	ID          pgtype.UUID `db:"id" json:"id"`
	Name        pgtype.Text `db:"name" json:"name"`
	Address     pgtype.Text `db:"address" json:"address"`
	PhoneNumber pgtype.Text `db:"phone_number" json:"phone_number"`
	Email       pgtype.Text `db:"email" json:"email"`
	StoreID     pgtype.UUID `db:"store_id" json:"store_id"`
}

func (q *Queries) UpdateSupplier(ctx context.Context, arg UpdateSupplierParams) (Supplier, error) {
	row := q.db.QueryRow(ctx, updateSupplier,
		arg.ID,
		arg.Name,
		arg.Address,
		arg.PhoneNumber,
		arg.Email,
		arg.StoreID,
	)
	var i Supplier
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Address,
		&i.PhoneNumber,
		&i.Email,
		&i.StoreID,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
