// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: user.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
  name,
  email,
  password,
  store_name,
  phone
) VALUES (
  $1, $2, $3, $4, $5
) RETURNING id, name, email, password, phone, status, email_verified, last_login, failed_login_attempts, locked_until, created_at, updated_at, store_name, confirmed_email
`

type CreateUserParams struct {
	Name      string      `db:"name" json:"name"`
	Email     string      `db:"email" json:"email"`
	Password  string      `db:"password" json:"password"`
	StoreName pgtype.Text `db:"store_name" json:"store_name"`
	Phone     pgtype.Text `db:"phone" json:"phone"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.StoreName,
		arg.Phone,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Status,
		&i.EmailVerified,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreName,
		&i.ConfirmedEmail,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, name, email, password, phone, status, email_verified, last_login, failed_login_attempts, locked_until, created_at, updated_at, store_name, confirmed_email FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Status,
		&i.EmailVerified,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreName,
		&i.ConfirmedEmail,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, name, email, password, phone, status, email_verified, last_login, failed_login_attempts, locked_until, created_at, updated_at, store_name, confirmed_email FROM users
WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Status,
		&i.EmailVerified,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreName,
		&i.ConfirmedEmail,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, name, email, password, phone, status, email_verified, last_login, failed_login_attempts, locked_until, created_at, updated_at, store_name, confirmed_email FROM users
ORDER BY created_at
LIMIT $1
OFFSET $2
`

type ListUsersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []User
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Email,
			&i.Password,
			&i.Phone,
			&i.Status,
			&i.EmailVerified,
			&i.LastLogin,
			&i.FailedLoginAttempts,
			&i.LockedUntil,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.StoreName,
			&i.ConfirmedEmail,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLoginAttempts = `-- name: UpdateLoginAttempts :one
UPDATE users
SET
  failed_login_attempts = $1,
  locked_until = $2,
  last_login = $3,
  updated_at = now()
WHERE id = $4
RETURNING id, name, email, password, phone, status, email_verified, last_login, failed_login_attempts, locked_until, created_at, updated_at, store_name, confirmed_email
`

type UpdateLoginAttemptsParams struct {
	FailedLoginAttempts int32              `db:"failed_login_attempts" json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	LastLogin           pgtype.Timestamptz `db:"last_login" json:"last_login"`
	ID                  pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdateLoginAttempts(ctx context.Context, arg UpdateLoginAttemptsParams) (User, error) {
	row := q.db.QueryRow(ctx, updateLoginAttempts,
		arg.FailedLoginAttempts,
		arg.LockedUntil,
		arg.LastLogin,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Status,
		&i.EmailVerified,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreName,
		&i.ConfirmedEmail,
	)
	return i, err
}

const updatePassword = `-- name: UpdatePassword :one
UPDATE users
SET
  password = $1,
  updated_at = now()
WHERE id = $2
RETURNING id, name, email, password, phone, status, email_verified, last_login, failed_login_attempts, locked_until, created_at, updated_at, store_name, confirmed_email
`

type UpdatePasswordParams struct {
	Password string      `db:"password" json:"password"`
	ID       pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdatePassword(ctx context.Context, arg UpdatePasswordParams) (User, error) {
	row := q.db.QueryRow(ctx, updatePassword, arg.Password, arg.ID)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Status,
		&i.EmailVerified,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreName,
		&i.ConfirmedEmail,
	)
	return i, err
}

const updateUser = `-- name: UpdateUser :one
UPDATE users
SET
  name = COALESCE($1, name),
  email = COALESCE($2, email),
  password = COALESCE($3, password),
  phone = COALESCE($4, phone),
  status = COALESCE($5, status),
  email_verified = COALESCE($6, email_verified),
  last_login = COALESCE($7, last_login),
  failed_login_attempts = COALESCE($8, failed_login_attempts),
  locked_until = COALESCE($9, locked_until),
  updated_at = now()
WHERE id = $10
RETURNING id, name, email, password, phone, status, email_verified, last_login, failed_login_attempts, locked_until, created_at, updated_at, store_name, confirmed_email
`

type UpdateUserParams struct {
	Name                string             `db:"name" json:"name"`
	Email               string             `db:"email" json:"email"`
	Password            string             `db:"password" json:"password"`
	Phone               pgtype.Text        `db:"phone" json:"phone"`
	Status              string             `db:"status" json:"status"`
	EmailVerified       bool               `db:"email_verified" json:"email_verified"`
	LastLogin           pgtype.Timestamptz `db:"last_login" json:"last_login"`
	FailedLoginAttempts int32              `db:"failed_login_attempts" json:"failed_login_attempts"`
	LockedUntil         pgtype.Timestamptz `db:"locked_until" json:"locked_until"`
	ID                  pgtype.UUID        `db:"id" json:"id"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.Name,
		arg.Email,
		arg.Password,
		arg.Phone,
		arg.Status,
		arg.EmailVerified,
		arg.LastLogin,
		arg.FailedLoginAttempts,
		arg.LockedUntil,
		arg.ID,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Status,
		&i.EmailVerified,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreName,
		&i.ConfirmedEmail,
	)
	return i, err
}

const verifyEmail = `-- name: VerifyEmail :one
UPDATE users
SET
  email_verified = true,
  updated_at = now()
WHERE id = $1
RETURNING id, name, email, password, phone, status, email_verified, last_login, failed_login_attempts, locked_until, created_at, updated_at, store_name, confirmed_email
`

func (q *Queries) VerifyEmail(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, verifyEmail, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Email,
		&i.Password,
		&i.Phone,
		&i.Status,
		&i.EmailVerified,
		&i.LastLogin,
		&i.FailedLoginAttempts,
		&i.LockedUntil,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.StoreName,
		&i.ConfirmedEmail,
	)
	return i, err
}
